For Week 6, include concepts such as decision trees and random forests. Complete your Jupyter Notebook homework by 11:59pm ET on Sunday.

In [1]:
import pandas as pd
from imblearn.under_sampling import RandomUnderSampler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm 
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
import seaborn as sns
from sklearn.metrics import mean_absolute_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import average_precision_score

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Credit Card

In [2]:
random_state = 42
classification_reports = []
classification_report_keys = []

### Import Data

In [3]:
# Import credit card datasaet
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/credit_card_cleaned.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

### Undersampling due to heavy class imbalance

In [4]:
from collections import Counter


X = df.drop(columns='Class')
y = df['Class']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(sampling_strategy=0.1, random_state=random_state)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 284315, 1: 492})
Resampled dataset shape: Counter({0: 4920, 1: 492})

### Split Data

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Decision Tree Classifier
#### (No feature scaling)

In [6]:
model = DecisionTreeClassifier(random_state=random_state)

In [7]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [8]:
y_pred = model.predict(X_test)

In [9]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Decision Tree Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       985
           1       0.82      0.88      0.85        98

    accuracy                           0.97      1083
   macro avg       0.90      0.93      0.92      1083
weighted avg       0.97      0.97      0.97      1083

In [10]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.729836406268087

### Feature Scaling + Decision Tree Classifier

In [11]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
model = DecisionTreeClassifier(random_state=random_state)

In [13]:
model.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [14]:
y_pred = model.predict(X_test_scaled)

In [15]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Decision Tree Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       985
           1       0.82      0.88      0.85        98

    accuracy                           0.97      1083
   macro avg       0.90      0.93      0.92      1083
weighted avg       0.97      0.97      0.97      1083

In [16]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.729836406268087

### Baseline Random Forest Classifier
#### (No feature scaling)

In [17]:
model = RandomForestClassifier(random_state=random_state)

In [18]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [19]:
y_pred = model.predict(X_test)

In [20]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Random Forest Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.87      0.92        98

    accuracy                           0.99      1083
   macro avg       0.99      0.93      0.96      1083
weighted avg       0.99      0.99      0.99      1083

In [21]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.8692652026990013

### Feature Scaling + Random Forest Tree Classifier

In [22]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
model = RandomForestClassifier(random_state=random_state)

In [24]:
model.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

In [25]:
y_pred = model.predict(X_test_scaled)

In [26]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.87      0.92        98

    accuracy                           0.99      1083
   macro avg       0.99      0.93      0.96      1083
weighted avg       0.99      0.99      0.99      1083

In [27]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.8692652026990013

### Parameter Tuning Random Forest (optimized for recall)

In [28]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [29]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_recall_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_recall_df)

[I 2026-06-26 17:32:57,481] A new study created in memory with name: no-name-2b351eb0-cd5a-433f-b953-4fd2130cd685
[I 2026-06-26 17:33:00,634] Trial 0 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 197, 'max_depth': 12, 'min_samples_split': 5}. Best is trial 0 with value: 0.8475819539110677.
[I 2026-06-26 17:33:02,431] Trial 1 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 29, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:04,528] Trial 2 finished with value: 0.8349237260629666 and parameters: {'n_estimators': 46, 'max_depth': 30, 'min_samples_split': 6}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:06,403] Trial 3 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 48, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:06,530] Trial 4 finished with value: 0.8552093476144108 and parameters: {'n_estimators': 23, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:06,682] Trial 5 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 20, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:08,468] Trial 6 finished with value: 0.850113599480688 and parameters: {'n_estimators': 156, 'max_depth': 24, 'min_samples_split': 9}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:09,010] Trial 7 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 48, 'max_depth': 17, 'min_samples_split': 8}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:11,155] Trial 8 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 188, 'max_depth': 13, 'min_samples_split': 7}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:12,870] Trial 9 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 147, 'max_depth': 15, 'min_samples_split': 6}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:13,256] Trial 10 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 104, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:13,903] Trial 11 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 88, 'max_depth': 5, 'min_samples_split': 4}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:14,028] Trial 12 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 18, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:14,776] Trial 13 finished with value: 0.8450503083414475 and parameters: {'n_estimators': 75, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:14,870] Trial 14 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 14, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:15,156] Trial 15 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 67, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:15,235] Trial 16 finished with value: 0.8552418046088931 and parameters: {'n_estimators': 10, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:16,400] Trial 17 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 120, 'max_depth': 7, 'min_samples_split': 10}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:16,622] Trial 18 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 36, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:16,850] Trial 19 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 36, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:17,566] Trial 20 finished with value: 0.8450503083414477 and parameters: {'n_estimators': 66, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 1 with value: 0.8628042843232716.
[I 2026-06-26 17:33:17,814] Trial 21 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 42, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:18,128] Trial 22 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 38, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:18,383] Trial 23 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 59, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:18,852] Trial 24 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 87, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:19,115] Trial 25 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 33, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:19,536] Trial 26 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 114, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:19,993] Trial 27 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 85, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:20,380] Trial 28 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 56, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:20,512] Trial 29 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 29, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:21,406] Trial 30 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 103, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:21,484] Trial 31 finished with value: 0.8526777020447905 and parameters: {'n_estimators': 10, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:21,712] Trial 32 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 38, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:22,043] Trial 33 finished with value: 0.860240181759169 and parameters: {'n_estimators': 48, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:22,153] Trial 34 finished with value: 0.8552093476144108 and parameters: {'n_estimators': 24, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:22,439] Trial 35 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 44, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:22,609] Trial 36 finished with value: 0.8627718273287893 and parameters: {'n_estimators': 19, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:22,887] Trial 37 finished with value: 0.8475819539110679 and parameters: {'n_estimators': 28, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:23,313] Trial 38 finished with value: 0.8501135994806882 and parameters: {'n_estimators': 56, 'max_depth': 5, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:23,615] Trial 39 finished with value: 0.8349237260629666 and parameters: {'n_estimators': 26, 'max_depth': 10, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:24,097] Trial 40 finished with value: 0.860240181759169 and parameters: {'n_estimators': 73, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:24,204] Trial 41 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:24,296] Trial 42 finished with value: 0.8526777020447905 and parameters: {'n_estimators': 18, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:24,582] Trial 43 finished with value: 0.860240181759169 and parameters: {'n_estimators': 43, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:24,831] Trial 44 finished with value: 0.8475494969165854 and parameters: {'n_estimators': 21, 'max_depth': 28, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:25,532] Trial 45 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 138, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:25,753] Trial 46 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 55, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:26,744] Trial 47 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 171, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:26,908] Trial 48 finished with value: 0.8450503083414475 and parameters: {'n_estimators': 33, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:27,018] Trial 49 finished with value: 0.8577409931840311 and parameters: {'n_estimators': 15, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:27,533] Trial 50 finished with value: 0.8374553716325869 and parameters: {'n_estimators': 44, 'max_depth': 20, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:27,629] Trial 51 finished with value: 0.8577409931840311 and parameters: {'n_estimators': 13, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:27,769] Trial 52 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 21, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:27,979] Trial 53 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 31, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:28,051] Trial 54 finished with value: 0.8526777020447905 and parameters: {'n_estimators': 10, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:28,316] Trial 55 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 50, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:28,620] Trial 56 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 38, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:28,971] Trial 57 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 67, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:29,244] Trial 58 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 64, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:29,643] Trial 59 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 75, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:29,863] Trial 60 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 54, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:30,219] Trial 61 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 51, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:30,570] Trial 62 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 64, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:30,889] Trial 63 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 61, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:31,339] Trial 64 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 83, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:31,628] Trial 65 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 69, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:32,123] Trial 66 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 93, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:32,547] Trial 67 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 79, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:32,929] Trial 68 finished with value: 0.8475819539110679 and parameters: {'n_estimators': 41, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:33,280] Trial 69 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 94, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:33,644] Trial 70 finished with value: 0.860240181759169 and parameters: {'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:33,955] Trial 71 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 62, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:34,275] Trial 72 finished with value: 0.8577409931840311 and parameters: {'n_estimators': 60, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:34,626] Trial 73 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 70, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:35,739] Trial 74 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 199, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:35,947] Trial 75 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 35, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:36,115] Trial 76 finished with value: 0.8450503083414475 and parameters: {'n_estimators': 35, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:36,428] Trial 77 finished with value: 0.8399870172022071 and parameters: {'n_estimators': 28, 'max_depth': 13, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:36,630] Trial 78 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 41, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:36,947] Trial 79 finished with value: 0.8627718273287893 and parameters: {'n_estimators': 50, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-26 17:33:37,100] Trial 80 finished with value: 0.8678675754625121 and parameters: {'n_estimators': 26, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:37,259] Trial 81 finished with value: 0.8678675754625121 and parameters: {'n_estimators': 27, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:37,411] Trial 82 finished with value: 0.8678675754625121 and parameters: {'n_estimators': 26, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:37,577] Trial 83 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 24, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:37,821] Trial 84 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 33, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:37,947] Trial 85 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 16, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:38,053] Trial 86 finished with value: 0.8552093476144108 and parameters: {'n_estimators': 25, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:38,221] Trial 87 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 20, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:38,397] Trial 88 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 30, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:38,534] Trial 89 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 30, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:38,733] Trial 90 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 26, 'max_depth': 5, 'min_samples_split': 6}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:38,943] Trial 91 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 38, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:39,197] Trial 92 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 46, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:39,398] Trial 93 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 35, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:39,607] Trial 94 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 37, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:39,900] Trial 95 finished with value: 0.8627718273287893 and parameters: {'n_estimators': 44, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 80 with value: 0.8678675754625121.
[I 2026-06-26 17:33:40,077] Trial 96 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 80 with value: 0.8678675754625121.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
81,81,0.867868,2026-06-26 17:33:37.100321,2026-06-26 17:33:37.259830,0 days 00:00:00.159509,3,6,27,COMPLETE
82,82,0.867868,2026-06-26 17:33:37.259830,2026-06-26 17:33:37.411763,0 days 00:00:00.151933,3,6,26,COMPLETE
80,80,0.867868,2026-06-26 17:33:36.947026,2026-06-26 17:33:37.100321,0 days 00:00:00.153295,3,6,26,COMPLETE
21,21,0.865336,2026-06-26 17:33:17.566577,2026-06-26 17:33:17.814064,0 days 00:00:00.247487,3,5,42,COMPLETE
75,75,0.865336,2026-06-26 17:33:35.739343,2026-06-26 17:33:35.947623,0 days 00:00:00.208280,3,5,35,COMPLETE

In [30]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_recall_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_recall_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_recall_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for Recall')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       985
           1       0.91      0.89      0.90        98

    accuracy                           0.98      1083
   macro avg       0.95      0.94      0.94      1083
weighted avg       0.98      0.98      0.98      1083

In [31]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.8146850326002978

### Parameter Tuning Random Forest (Optimized for F1)

In [32]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_f1_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_f1_df)

[I 2026-06-26 17:33:41,430] A new study created in memory with name: no-name-bdaea017-a70b-45c4-aa96-76dac5f6c08d
[I 2026-06-26 17:33:42,590] Trial 0 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 106, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 0 with value: 0.9093597612199407.
[I 2026-06-26 17:33:42,674] Trial 1 finished with value: 0.8724398336469543 and parameters: {'n_estimators': 12, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 0 with value: 0.9093597612199407.
[I 2026-06-26 17:33:44,115] Trial 2 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 198, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:46,008] Trial 3 finished with value: 0.9096363657281739 and parameters: {'n_estimators': 179, 'max_depth': 22, 'min_samples_split': 7}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:46,293] Trial 4 finished with value: 0.9056849443599226 and parameters: {'n_estimators': 23, 'max_depth': 11, 'min_samples_split': 8}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:47,959] Trial 5 finished with value: 0.9099043842936483 and parameters: {'n_estimators': 182, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:49,009] Trial 6 finished with value: 0.908223562196165 and parameters: {'n_estimators': 110, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:49,589] Trial 7 finished with value: 0.9068458625021171 and parameters: {'n_estimators': 108, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:50,627] Trial 8 finished with value: 0.9078603457981262 and parameters: {'n_estimators': 122, 'max_depth': 6, 'min_samples_split': 9}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:52,148] Trial 9 finished with value: 0.9080930260656288 and parameters: {'n_estimators': 134, 'max_depth': 24, 'min_samples_split': 6}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:52,579] Trial 10 finished with value: 0.90116927374991 and parameters: {'n_estimators': 62, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:54,180] Trial 11 finished with value: 0.9103647293763354 and parameters: {'n_estimators': 197, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:55,333] Trial 12 finished with value: 0.9032259529998546 and parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:57,068] Trial 13 finished with value: 0.9078670829015657 and parameters: {'n_estimators': 162, 'max_depth': 12, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:57,636] Trial 14 finished with value: 0.8982132918003725 and parameters: {'n_estimators': 154, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:58,076] Trial 15 finished with value: 0.9024054768404177 and parameters: {'n_estimators': 68, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:33:59,675] Trial 16 finished with value: 0.9103647293763354 and parameters: {'n_estimators': 196, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:01,236] Trial 17 finished with value: 0.9087166448300469 and parameters: {'n_estimators': 149, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:01,622] Trial 18 finished with value: 0.8983766791947438 and parameters: {'n_estimators': 77, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:02,791] Trial 19 finished with value: 0.9081016802701445 and parameters: {'n_estimators': 171, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:04,262] Trial 20 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 141, 'max_depth': 32, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:05,793] Trial 21 finished with value: 0.9103647293763354 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:07,641] Trial 22 finished with value: 0.9050975070421936 and parameters: {'n_estimators': 190, 'max_depth': 9, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:09,423] Trial 23 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 166, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:10,351] Trial 24 finished with value: 0.9020415520315709 and parameters: {'n_estimators': 186, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:11,610] Trial 25 finished with value: 0.9091131422187079 and parameters: {'n_estimators': 170, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:13,424] Trial 26 finished with value: 0.9084320145238227 and parameters: {'n_estimators': 192, 'max_depth': 8, 'min_samples_split': 5}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:14,440] Trial 27 finished with value: 0.9076801656179461 and parameters: {'n_estimators': 127, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:15,479] Trial 28 finished with value: 0.9094513181125892 and parameters: {'n_estimators': 149, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:16,459] Trial 29 finished with value: 0.9069015468809317 and parameters: {'n_estimators': 87, 'max_depth': 15, 'min_samples_split': 7}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:17,279] Trial 30 finished with value: 0.9009016366059412 and parameters: {'n_estimators': 177, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:18,895] Trial 31 finished with value: 0.9103647293763354 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:20,693] Trial 32 finished with value: 0.9111087354979995 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:22,509] Trial 33 finished with value: 0.9096363657281739 and parameters: {'n_estimators': 186, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:23,461] Trial 34 finished with value: 0.9031821206685142 and parameters: {'n_estimators': 159, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:25,036] Trial 35 finished with value: 0.9096363657281739 and parameters: {'n_estimators': 178, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:25,146] Trial 36 finished with value: 0.870455967498662 and parameters: {'n_estimators': 23, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:27,086] Trial 37 finished with value: 0.9108321309897665 and parameters: {'n_estimators': 189, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:28,916] Trial 38 finished with value: 0.9079458909738557 and parameters: {'n_estimators': 180, 'max_depth': 10, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:29,456] Trial 39 finished with value: 0.9043387249884578 and parameters: {'n_estimators': 46, 'max_depth': 18, 'min_samples_split': 7}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:31,365] Trial 40 finished with value: 0.9092622263894243 and parameters: {'n_estimators': 171, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:33,296] Trial 41 finished with value: 0.9069611131187486 and parameters: {'n_estimators': 191, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:34,681] Trial 42 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 195, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:35,965] Trial 43 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 183, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:37,258] Trial 44 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 179, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:38,539] Trial 45 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 178, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:39,628] Trial 46 finished with value: 0.9031821206685142 and parameters: {'n_estimators': 176, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:40,824] Trial 47 finished with value: 0.9091131422187079 and parameters: {'n_estimators': 159, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:41,440] Trial 48 finished with value: 0.9044703945363148 and parameters: {'n_estimators': 118, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:42,347] Trial 49 finished with value: 0.9008355229655628 and parameters: {'n_estimators': 136, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:43,459] Trial 50 finished with value: 0.9103008816823095 and parameters: {'n_estimators': 148, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:45,123] Trial 51 finished with value: 0.9096363657281739 and parameters: {'n_estimators': 183, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:46,470] Trial 52 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 193, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:47,654] Trial 53 finished with value: 0.9091131422187079 and parameters: {'n_estimators': 165, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:48,670] Trial 54 finished with value: 0.9032614892919405 and parameters: {'n_estimators': 173, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 2 with value: 0.9116940705367986.
[I 2026-06-26 17:34:49,991] Trial 55 finished with value: 0.912219602459821 and parameters: {'n_estimators': 183, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 55 with value: 0.912219602459821.
[I 2026-06-26 17:34:51,110] Trial 56 finished with value: 0.9020265899630815 and parameters: {'n_estimators': 182, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 55 with value: 0.912219602459821.
[I 2026-06-26 17:34:51,879] Trial 57 finished with value: 0.9044703945363148 and parameters: {'n_estimators': 156, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 55 with value: 0.912219602459821.
[I 2026-06-26 17:34:52,681] Trial 58 finished with value: 0.9064285784603185 and parameters: {'n_estimators': 98, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 55 with value: 0.912219602459821.
[I 2026-06-26 17:34:53,793] Trial 59 finished with value: 0.9020265899630815 and parameters: {'n_estimators': 185, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 55 with value: 0.912219602459821.
[I 2026-06-26 17:34:54,932] Trial 60 finished with value: 0.9094948691246337 and parameters: {'n_estimators': 164, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 55 with value: 0.912219602459821.
[I 2026-06-26 17:34:56,334] Trial 61 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 194, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 55 with value: 0.912219602459821.
[I 2026-06-26 17:34:57,840] Trial 62 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 194, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 62 with value: 0.9127898337754544.
[I 2026-06-26 17:34:59,193] Trial 63 finished with value: 0.9130621137938089 and parameters: {'n_estimators': 171, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:00,759] Trial 64 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 188, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:02,353] Trial 65 finished with value: 0.9094513181125892 and parameters: {'n_estimators': 194, 'max_depth': 6, 'min_samples_split': 10}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:04,155] Trial 66 finished with value: 0.9111087354979995 and parameters: {'n_estimators': 169, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:05,809] Trial 67 finished with value: 0.9111087354979995 and parameters: {'n_estimators': 187, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:07,364] Trial 68 finished with value: 0.9103647293763354 and parameters: {'n_estimators': 196, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:09,210] Trial 69 finished with value: 0.9111087354979995 and parameters: {'n_estimators': 188, 'max_depth': 8, 'min_samples_split': 6}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:10,805] Trial 70 finished with value: 0.9099043842936483 and parameters: {'n_estimators': 173, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:12,295] Trial 71 finished with value: 0.9115524688399368 and parameters: {'n_estimators': 180, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:13,510] Trial 72 finished with value: 0.9031821206685142 and parameters: {'n_estimators': 199, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:14,875] Trial 73 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 184, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:16,378] Trial 74 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 190, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:17,857] Trial 75 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 191, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:19,761] Trial 76 finished with value: 0.9111087354979995 and parameters: {'n_estimators': 191, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:21,330] Trial 77 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 195, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:23,091] Trial 78 finished with value: 0.9078603457981262 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 9}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:24,671] Trial 79 finished with value: 0.9103647293763354 and parameters: {'n_estimators': 190, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:26,371] Trial 80 finished with value: 0.9096363657281739 and parameters: {'n_estimators': 175, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:27,977] Trial 81 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 194, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:29,643] Trial 82 finished with value: 0.9096363657281739 and parameters: {'n_estimators': 188, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:31,308] Trial 83 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 196, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:32,918] Trial 84 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 195, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:34,551] Trial 85 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 196, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:36,046] Trial 86 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 192, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:38,020] Trial 87 finished with value: 0.906693094553274 and parameters: {'n_estimators': 200, 'max_depth': 9, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:39,625] Trial 88 finished with value: 0.9111087354979995 and parameters: {'n_estimators': 187, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:41,256] Trial 89 finished with value: 0.9096363657281739 and parameters: {'n_estimators': 167, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:41,737] Trial 90 finished with value: 0.9091131422187079 and parameters: {'n_estimators': 55, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:43,320] Trial 91 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 196, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:44,927] Trial 92 finished with value: 0.9127898337754544 and parameters: {'n_estimators': 195, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:46,569] Trial 93 finished with value: 0.9111087354979995 and parameters: {'n_estimators': 190, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:47,993] Trial 94 finished with value: 0.9115524688399368 and parameters: {'n_estimators': 177, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:49,724] Trial 95 finished with value: 0.9096363657281739 and parameters: {'n_estimators': 196, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 63 with value: 0.9130621137938089.
[I 2026-06-26 17:35:51,493] Trial 96 finished with value: 0.9069611131187486 and parameters: {'n_estimators': 183, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 63 with value: 0.9130621137938089.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
63,63,0.913062,2026-06-26 17:34:57.840463,2026-06-26 17:34:59.193828,0 days 00:00:01.353365,6,2,171,COMPLETE
83,83,0.912790,2026-06-26 17:35:29.643512,2026-06-26 17:35:31.308759,0 days 00:00:01.665247,6,2,196,COMPLETE
62,62,0.912790,2026-06-26 17:34:56.334909,2026-06-26 17:34:57.840463,0 days 00:00:01.505554,6,2,194,COMPLETE
64,64,0.912790,2026-06-26 17:34:59.193828,2026-06-26 17:35:00.759733,0 days 00:00:01.565905,6,2,188,COMPLETE
91,91,0.912790,2026-06-26 17:35:41.737783,2026-06-26 17:35:43.320946,0 days 00:00:01.583163,6,2,196,COMPLETE

In [33]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_f1_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_f1_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_f1_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for F1')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.97      0.87      0.91        98

    accuracy                           0.99      1083
   macro avg       0.98      0.93      0.95      1083
weighted avg       0.99      0.99      0.98      1083

In [34]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.8497819865795726

### Conclusions

In [35]:
pd.concat(classification_reports, keys=classification_report_keys)

                                                                 precision  \
Baseline Decision Tree Classifier                  0              0.987730
                                                   1              0.819048
                                                   accuracy       0.971376
                                                   macro avg      0.903389
                                                   weighted avg   0.972466
Decision Tree Classifier with Standard Scaling     0              0.987730
                                                   1              0.819048
                                                   accuracy       0.971376
                                                   macro avg      0.903389
                                                   weighted avg   0.972466
Baseline Random Forest Classifier                  0              0.986961
                                                   1              0.988372
                                                   accuracy       0.987073
                                                   macro avg      0.987666
                                                   weighted avg   0.987089
Random Forest Classifier with Standard Scaling     0              0.986961
                                                   1              0.988372
                                                   accuracy       0.987073
                                                   macro avg      0.987666
                                                   weighted avg   0.987089
Random Forest Classifier with Parameter Tuning ... 0              0.988855
                                                   1              0.906250
                                                   accuracy       0.981533
                                                   macro avg      0.947553
                                                   weighted avg   0.981380
Random Forest Classifier with Parameter Tuning ... 0              0.986935
                                                   1              0.965909
                                                   accuracy       0.985226
                                                   macro avg      0.976422
                                                   weighted avg   0.985032

                                                                   recall  \
Baseline Decision Tree Classifier                  0             0.980711
                                                   1             0.877551
                                                   accuracy      0.971376
                                                   macro avg     0.929131
                                                   weighted avg  0.971376
Decision Tree Classifier with Standard Scaling     0             0.980711
                                                   1             0.877551
                                                   accuracy      0.971376
                                                   macro avg     0.929131
                                                   weighted avg  0.971376
Baseline Random Forest Classifier                  0             0.998985
                                                   1             0.867347
                                                   accuracy      0.987073
                                                   macro avg     0.933166
                                                   weighted avg  0.987073
Random Forest Classifier with Standard Scaling     0             0.998985
                                                   1             0.867347
                                                   accuracy      0.987073
                                                   macro avg     0.933166
                                                   weighted avg  0.987073
Random Forest Classifier with Parameter Tuning ... 0             0.990863
                                                   1             0.887755
                                                   accuracy      0.981533
                                                   macro avg     0.939309
                                                   weighted avg  0.981533
Random Forest Classifier with Parameter Tuning ... 0             0.996954
                                                   1             0.867347
                                                   accuracy      0.985226
                                                   macro avg     0.932151
                                                   weighted avg  0.985226

                                                                 f1-score  \
Baseline Decision Tree Classifier                  0             0.984208
                                                   1             0.847291
                                                   accuracy      0.971376
                                                   macro avg     0.915749
                                                   weighted avg  0.971818
Decision Tree Classifier with Standard Scaling     0             0.984208
                                                   1             0.847291
                                                   accuracy      0.971376
                                                   macro avg     0.915749
                                                   weighted avg  0.971818
Baseline Random Forest Classifier                  0             0.992936
                                                   1             0.923913
                                                   accuracy      0.987073
                                                   macro avg     0.958425
                                                   weighted avg  0.986691
Random Forest Classifier with Standard Scaling     0             0.992936
                                                   1             0.923913
                                                   accuracy      0.987073
                                                   macro avg     0.958425
                                                   weighted avg  0.986691
Random Forest Classifier with Parameter Tuning ... 0             0.989858
                                                   1             0.896907
                                                   accuracy      0.981533
                                                   macro avg     0.943383
                                                   weighted avg  0.981447
Random Forest Classifier with Parameter Tuning ... 0             0.991919
                                                   1             0.913978
                                                   accuracy      0.985226
                                                   macro avg     0.952949
                                                   weighted avg  0.984866

                                                                     support
Baseline Decision Tree Classifier                  0              985.000000
                                                   1               98.000000
                                                   accuracy         0.971376
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Decision Tree Classifier with Standard Scaling     0              985.000000
                                                   1               98.000000
                                                   accuracy         0.971376
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Baseline Random Forest Classifier                  0              985.000000
                                                   1               98.000000
                                                   accuracy         0.987073
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Standard Scaling     0              985.000000
                                                   1               98.000000
                                                   accuracy         0.987073
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Parameter Tuning ... 0              985.000000
                                                   1               98.000000
                                                   accuracy         0.981533
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Parameter Tuning ... 0              985.000000
                                                   1               98.000000
                                                   accuracy         0.985226
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000

We can see the scaling does not affect the results since these are tree based methods. The Random Forest model is the better out of the two variants. The base random forest achieves 0.933166 macro avg recall and 0.958425 macro avg f1

The recall optimized model sees a lift on macro avg recall to 0.938801, with less recall on negative and higher on positive class. 

The f1 optimized model sees 0.955234 macro avg f1, slightly less than the baseline model

## IBM

In [36]:
random_state = 42
classification_reports = []
classification_report_keys = []

### Import Data

In [37]:
df = pd.read_csv('ibm_hi_small_trans_cleaned_semester3.csv')
df

,Is Laundering,Amount_Received_USD,Amount_Paid_USD,Receiving Currency_Bitcoin,Receiving Currency_Brazil Real,Receiving Currency_Canadian Dollar,Receiving Currency_Euro,Receiving Currency_Mexican Peso,Receiving Currency_Ruble,Receiving Currency_Rupee,...,Payment Currency_Yen,Payment Currency_Yuan,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
0,0,3697.340000,3697.340000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
1,0,0.010000,0.010000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
2,0,14675.570000,14675.570000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
3,0,2806.970000,2806.970000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
4,0,36682.970000,36682.970000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078340,0,3107.386389,3107.386389,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078341,0,2168.020464,2168.020464,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078342,0,100.011894,100.011894,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078343,0,770.280058,770.280058,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1
5078344,0,5653.900141,5653.900141,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0

### Undersampling due to heavy class imbalance

In [38]:
from collections import Counter


X = df.drop(columns='Is Laundering')
y = df['Is Laundering']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(sampling_strategy=0.1, random_state=random_state)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 5073168, 1: 5177})
Resampled dataset shape: Counter({0: 51770, 1: 5177})

### Split Data

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Decision Tree Classifier
#### (No feature scaling)

In [40]:
model = DecisionTreeClassifier(random_state=random_state)

In [41]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [42]:
y_pred = model.predict(X_test)

In [43]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Decision Tree Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96     10355
           1       0.60      0.59      0.60      1035

    accuracy                           0.93     11390
   macro avg       0.78      0.78      0.78     11390
weighted avg       0.93      0.93      0.93     11390

In [44]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.3926443982064739

### Feature Scaling + Decision Tree Classifier

In [45]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [46]:
model = DecisionTreeClassifier(random_state=random_state)

In [47]:
model.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [48]:
y_pred = model.predict(X_test_scaled)

In [49]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Decision Tree Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96     10355
           1       0.60      0.59      0.60      1035

    accuracy                           0.93     11390
   macro avg       0.78      0.78      0.78     11390
weighted avg       0.93      0.93      0.93     11390

In [50]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.3943943704225581

### Baseline Random Forest Classifier
#### (No feature scaling)

In [51]:
model = RandomForestClassifier(random_state=random_state)

In [52]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [53]:
y_pred = model.predict(X_test)

In [54]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Random Forest Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96     10355
           1       0.62      0.60      0.61      1035

    accuracy                           0.93     11390
   macro avg       0.79      0.78      0.78     11390
weighted avg       0.93      0.93      0.93     11390

In [55]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.4041496038216109

### Feature Scaling + Decision Tree Classifier

In [56]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [57]:
model = RandomForestClassifier(random_state=random_state)

In [58]:
model.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

In [59]:
y_pred = model.predict(X_test_scaled)

In [60]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96     10355
           1       0.62      0.60      0.61      1035

    accuracy                           0.93     11390
   macro avg       0.79      0.78      0.79     11390
weighted avg       0.93      0.93      0.93     11390

In [61]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.4082138932660996

### Parameter Tuning Random Forest (optimized for recall)

In [62]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [63]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_recall_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_recall_df)

[I 2026-06-26 17:36:11,822] A new study created in memory with name: no-name-b622a0da-cc10-4b26-8f07-317949ed92b1
[I 2026-06-26 17:36:16,780] Trial 0 finished with value: 0.7974458488487963 and parameters: {'n_estimators': 166, 'max_depth': 19, 'min_samples_split': 2}. Best is trial 0 with value: 0.7974458488487963.
[I 2026-06-26 17:36:19,616] Trial 1 finished with value: 0.8351095260572368 and parameters: {'n_estimators': 126, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:19,994] Trial 2 finished with value: 0.8174816291090483 and parameters: {'n_estimators': 24, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:20,396] Trial 3 finished with value: 0.817722592262373 and parameters: {'n_estimators': 28, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:22,667] Trial 4 finished with value: 0.8049273614097656 and parameters: {'n_estimators': 194, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:24,189] Trial 5 finished with value: 0.8150702493546149 and parameters: {'n_estimators': 91, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:26,498] Trial 6 finished with value: 0.8046858155160457 and parameters: {'n_estimators': 198, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:27,197] Trial 7 finished with value: 0.8109639691613783 and parameters: {'n_estimators': 91, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:28,026] Trial 8 finished with value: 0.8312418780557451 and parameters: {'n_estimators': 107, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:29,078] Trial 9 finished with value: 0.811930444106455 and parameters: {'n_estimators': 156, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:32,770] Trial 10 finished with value: 0.7617136646795218 and parameters: {'n_estimators': 125, 'max_depth': 26, 'min_samples_split': 7}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:35,482] Trial 11 finished with value: 0.8339017965886377 and parameters: {'n_estimators': 118, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:36,895] Trial 12 finished with value: 0.8307646136722552 and parameters: {'n_estimators': 55, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 1 with value: 0.8351095260572368.
[I 2026-06-26 17:36:39,754] Trial 13 finished with value: 0.8372831477305176 and parameters: {'n_estimators': 135, 'max_depth': 12, 'min_samples_split': 4}. Best is trial 13 with value: 0.8372831477305176.
[I 2026-06-26 17:36:42,229] Trial 14 finished with value: 0.8396954015955433 and parameters: {'n_estimators': 139, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:36:45,020] Trial 15 finished with value: 0.8377633258159822 and parameters: {'n_estimators': 151, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:36:47,545] Trial 16 finished with value: 0.8295554273526686 and parameters: {'n_estimators': 161, 'max_depth': 8, 'min_samples_split': 7}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:36:49,948] Trial 17 finished with value: 0.8300382277699108 and parameters: {'n_estimators': 146, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:36:55,617] Trial 18 finished with value: 0.6769727219221109 and parameters: {'n_estimators': 174, 'max_depth': 31, 'min_samples_split': 4}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:36:56,628] Trial 19 finished with value: 0.8051683245630903 and parameters: {'n_estimators': 72, 'max_depth': 5, 'min_samples_split': 6}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:36:59,663] Trial 20 finished with value: 0.8375235281434474 and parameters: {'n_estimators': 145, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:02,411] Trial 21 finished with value: 0.8384888376077342 and parameters: {'n_estimators': 146, 'max_depth': 10, 'min_samples_split': 3}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:07,363] Trial 22 finished with value: 0.8008245776588987 and parameters: {'n_estimators': 178, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:09,552] Trial 23 finished with value: 0.8394541470720209 and parameters: {'n_estimators': 136, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:11,022] Trial 24 finished with value: 0.8013070867059433 and parameters: {'n_estimators': 103, 'max_depth': 6, 'min_samples_split': 6}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:14,907] Trial 25 finished with value: 0.8058958759462247 and parameters: {'n_estimators': 135, 'max_depth': 18, 'min_samples_split': 3}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:18,215] Trial 26 finished with value: 0.8375238195136449 and parameters: {'n_estimators': 181, 'max_depth': 10, 'min_samples_split': 9}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:19,399] Trial 27 finished with value: 0.8039617605752813 and parameters: {'n_estimators': 110, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:22,643] Trial 28 finished with value: 0.8276242256837001 and parameters: {'n_estimators': 136, 'max_depth': 15, 'min_samples_split': 3}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:27,650] Trial 29 finished with value: 0.7769237717289325 and parameters: {'n_estimators': 168, 'max_depth': 21, 'min_samples_split': 2}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:29,056] Trial 30 finished with value: 0.8165195247169338 and parameters: {'n_estimators': 93, 'max_depth': 7, 'min_samples_split': 6}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:31,794] Trial 31 finished with value: 0.8392126011783011 and parameters: {'n_estimators': 152, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:34,859] Trial 32 finished with value: 0.8384891289779317 and parameters: {'n_estimators': 160, 'max_depth': 10, 'min_samples_split': 5}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:37,823] Trial 33 finished with value: 0.8380066199308869 and parameters: {'n_estimators': 166, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:39,592] Trial 34 finished with value: 0.8034783774176442 and parameters: {'n_estimators': 127, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:44,210] Trial 35 finished with value: 0.8295565928334586 and parameters: {'n_estimators': 188, 'max_depth': 15, 'min_samples_split': 6}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:45,872] Trial 36 finished with value: 0.8037210887921541 and parameters: {'n_estimators': 159, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:47,907] Trial 37 finished with value: 0.8297963905059935 and parameters: {'n_estimators': 123, 'max_depth': 8, 'min_samples_split': 5}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:49,660] Trial 38 finished with value: 0.802995577000402 and parameters: {'n_estimators': 138, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:50,125] Trial 39 finished with value: 0.8343840142654848 and parameters: {'n_estimators': 14, 'max_depth': 11, 'min_samples_split': 5}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:52,093] Trial 40 finished with value: 0.8037205060517589 and parameters: {'n_estimators': 187, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:54,938] Trial 41 finished with value: 0.838730383501454 and parameters: {'n_estimators': 148, 'max_depth': 10, 'min_samples_split': 3}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:57,706] Trial 42 finished with value: 0.8392128925484986 and parameters: {'n_estimators': 154, 'max_depth': 9, 'min_samples_split': 2}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:37:59,410] Trial 43 finished with value: 0.8160346847083094 and parameters: {'n_estimators': 114, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:38:02,690] Trial 44 finished with value: 0.8358344551085937 and parameters: {'n_estimators': 151, 'max_depth': 12, 'min_samples_split': 2}. Best is trial 14 with value: 0.8396954015955433.
[I 2026-06-26 17:38:04,870] Trial 45 finished with value: 0.8399372388594605 and parameters: {'n_estimators': 127, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:06,841] Trial 46 finished with value: 0.8295554273526686 and parameters: {'n_estimators': 128, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:08,047] Trial 47 finished with value: 0.8051689073034854 and parameters: {'n_estimators': 102, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:10,810] Trial 48 finished with value: 0.8339023793290327 and parameters: {'n_estimators': 119, 'max_depth': 13, 'min_samples_split': 4}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:14,420] Trial 49 finished with value: 0.8131396304260414 and parameters: {'n_estimators': 140, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:17,400] Trial 50 finished with value: 0.8387295093908614 and parameters: {'n_estimators': 171, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:19,696] Trial 51 finished with value: 0.8143444461926658 and parameters: {'n_estimators': 153, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:22,200] Trial 52 finished with value: 0.8389719293951737 and parameters: {'n_estimators': 143, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:24,441] Trial 53 finished with value: 0.8288310810417066 and parameters: {'n_estimators': 133, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:27,517] Trial 54 finished with value: 0.8370416018367978 and parameters: {'n_estimators': 142, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:28,127] Trial 55 finished with value: 0.7996165568201021 and parameters: {'n_estimators': 39, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:30,345] Trial 56 finished with value: 0.8396956929657406 and parameters: {'n_estimators': 130, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:32,940] Trial 57 finished with value: 0.8370407277262053 and parameters: {'n_estimators': 128, 'max_depth': 11, 'min_samples_split': 2}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:35,914] Trial 58 finished with value: 0.8319714690302618 and parameters: {'n_estimators': 115, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:37,058] Trial 59 finished with value: 0.8039632174262688 and parameters: {'n_estimators': 81, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:39,971] Trial 60 finished with value: 0.8389710552845813 and parameters: {'n_estimators': 164, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:42,618] Trial 61 finished with value: 0.8384888376077342 and parameters: {'n_estimators': 157, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:44,690] Trial 62 finished with value: 0.8162765219722266 and parameters: {'n_estimators': 132, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:47,041] Trial 63 finished with value: 0.8365576359387656 and parameters: {'n_estimators': 121, 'max_depth': 11, 'min_samples_split': 2}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:49,180] Trial 64 finished with value: 0.8317284662855545 and parameters: {'n_estimators': 142, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:51,919] Trial 65 finished with value: 0.8372828563603202 and parameters: {'n_estimators': 151, 'max_depth': 10, 'min_samples_split': 4}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:53,778] Trial 66 finished with value: 0.8367991818324854 and parameters: {'n_estimators': 99, 'max_depth': 9, 'min_samples_split': 2}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:55,916] Trial 67 finished with value: 0.8160346847083092 and parameters: {'n_estimators': 144, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:38:58,746] Trial 68 finished with value: 0.8370416018367977 and parameters: {'n_estimators': 131, 'max_depth': 12, 'min_samples_split': 5}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:39:01,517] Trial 69 finished with value: 0.8259348612786489 and parameters: {'n_estimators': 174, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 45 with value: 0.8399372388594605.
[I 2026-06-26 17:39:04,475] Trial 70 finished with value: 0.8401782020127854 and parameters: {'n_estimators': 155, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:07,383] Trial 71 finished with value: 0.838731548982244 and parameters: {'n_estimators': 156, 'max_depth': 10, 'min_samples_split': 9}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:09,684] Trial 72 finished with value: 0.8293130073483563 and parameters: {'n_estimators': 136, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:12,277] Trial 73 finished with value: 0.8346273083803896 and parameters: {'n_estimators': 111, 'max_depth': 13, 'min_samples_split': 8}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:15,076] Trial 74 finished with value: 0.8367991818324855 and parameters: {'n_estimators': 147, 'max_depth': 10, 'min_samples_split': 7}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:18,229] Trial 75 finished with value: 0.8389719293951737 and parameters: {'n_estimators': 152, 'max_depth': 11, 'min_samples_split': 9}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:21,025] Trial 76 finished with value: 0.8384879634971417 and parameters: {'n_estimators': 163, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:24,138] Trial 77 finished with value: 0.8290729183056241 and parameters: {'n_estimators': 124, 'max_depth': 15, 'min_samples_split': 6}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:26,412] Trial 78 finished with value: 0.8326931930094462 and parameters: {'n_estimators': 140, 'max_depth': 8, 'min_samples_split': 4}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:27,573] Trial 79 finished with value: 0.8112063891656905 and parameters: {'n_estimators': 168, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:29,880] Trial 80 finished with value: 0.8049273614097656 and parameters: {'n_estimators': 178, 'max_depth': 6, 'min_samples_split': 8}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:33,078] Trial 81 finished with value: 0.8382478744544093 and parameters: {'n_estimators': 155, 'max_depth': 11, 'min_samples_split': 9}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:36,280] Trial 82 finished with value: 0.8387309662418488 and parameters: {'n_estimators': 149, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:39,000] Trial 83 finished with value: 0.8396962757061356 and parameters: {'n_estimators': 159, 'max_depth': 9, 'min_samples_split': 9}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:41,829] Trial 84 finished with value: 0.8392128925484986 and parameters: {'n_estimators': 159, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:43,957] Trial 85 finished with value: 0.8162771047126215 and parameters: {'n_estimators': 162, 'max_depth': 7, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:46,545] Trial 86 finished with value: 0.8370395622454154 and parameters: {'n_estimators': 182, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:48,954] Trial 87 finished with value: 0.8382487485650019 and parameters: {'n_estimators': 157, 'max_depth': 10, 'min_samples_split': 9}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:51,993] Trial 88 finished with value: 0.8375246936242373 and parameters: {'n_estimators': 169, 'max_depth': 12, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:53,630] Trial 89 finished with value: 0.8172427055471058 and parameters: {'n_estimators': 137, 'max_depth': 7, 'min_samples_split': 9}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:55,558] Trial 90 finished with value: 0.8293135900887514 and parameters: {'n_estimators': 130, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:39:58,030] Trial 91 finished with value: 0.8394541470720209 and parameters: {'n_estimators': 145, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:40:00,884] Trial 92 finished with value: 0.8399369474892631 and parameters: {'n_estimators': 147, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:40:03,396] Trial 93 finished with value: 0.8399369474892631 and parameters: {'n_estimators': 146, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:40:06,063] Trial 94 finished with value: 0.8399369474892631 and parameters: {'n_estimators': 146, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.
[I 2026-06-26 17:40:09,280] Trial 95 finished with value: 0.835593491955269 and parameters: {'n_estimators': 147, 'max_depth': 13, 'min_samples_split': 10}. Best is trial 70 with value: 0.8401782020127854.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
96,96,0.840661,2026-06-26 17:40:09.280563,2026-06-26 17:40:11.388681,0 days 00:00:02.108118,10,10,125,COMPLETE
97,97,0.840180,2026-06-26 17:40:11.388681,2026-06-26 17:40:13.530977,0 days 00:00:02.142296,10,9,116,COMPLETE
70,70,0.840178,2026-06-26 17:39:01.517268,2026-06-26 17:39:04.475439,0 days 00:00:02.958171,10,10,155,COMPLETE
99,99,0.839939,2026-06-26 17:40:16.183683,2026-06-26 17:40:17.849529,0 days 00:00:01.665846,10,9,107,COMPLETE
45,45,0.839937,2026-06-26 17:38:02.690475,2026-06-26 17:38:04.870844,0 days 00:00:02.180369,9,3,127,COMPLETE

In [64]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_recall_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_recall_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_recall_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for Recall')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.93      0.96     10355
           1       0.56      0.86      0.68      1035

    accuracy                           0.93     11390
   macro avg       0.77      0.90      0.82     11390
weighted avg       0.95      0.93      0.93     11390

In [65]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.49764059120896414

### Parameter Tuning Random Forest (Optimized for F1)

In [66]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_f1_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_f1_df)

[I 2026-06-26 17:40:19,956] A new study created in memory with name: no-name-d2f8a2c9-bf72-498c-884d-9adf37b2d65a
[I 2026-06-26 17:40:22,281] Trial 0 finished with value: 0.6839184273276918 and parameters: {'n_estimators': 86, 'max_depth': 17, 'min_samples_split': 8}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:24,404] Trial 1 finished with value: 0.6831693843590534 and parameters: {'n_estimators': 89, 'max_depth': 13, 'min_samples_split': 9}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:25,216] Trial 2 finished with value: 0.39212821748450255 and parameters: {'n_estimators': 102, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:25,996] Trial 3 finished with value: 0.44476098449738827 and parameters: {'n_estimators': 77, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:29,738] Trial 4 finished with value: 0.6768425596027914 and parameters: {'n_estimators': 129, 'max_depth': 21, 'min_samples_split': 10}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:30,305] Trial 5 finished with value: 0.41461673934568505 and parameters: {'n_estimators': 58, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:32,831] Trial 6 finished with value: 0.6684055334310376 and parameters: {'n_estimators': 135, 'max_depth': 10, 'min_samples_split': 6}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:33,280] Trial 7 finished with value: 0.43664060682858014 and parameters: {'n_estimators': 39, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:34,637] Trial 8 finished with value: 0.5615240024933741 and parameters: {'n_estimators': 141, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:39,645] Trial 9 finished with value: 0.652706062523541 and parameters: {'n_estimators': 159, 'max_depth': 27, 'min_samples_split': 6}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:39,991] Trial 10 finished with value: 0.6042299784772844 and parameters: {'n_estimators': 15, 'max_depth': 7, 'min_samples_split': 8}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:41,782] Trial 11 finished with value: 0.6836827938212323 and parameters: {'n_estimators': 92, 'max_depth': 14, 'min_samples_split': 9}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:45,939] Trial 12 finished with value: 0.6839001966347894 and parameters: {'n_estimators': 183, 'max_depth': 15, 'min_samples_split': 7}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:51,309] Trial 13 finished with value: 0.6800907061716307 and parameters: {'n_estimators': 195, 'max_depth': 19, 'min_samples_split': 7}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:56,893] Trial 14 finished with value: 0.644584482625844 and parameters: {'n_estimators': 199, 'max_depth': 31, 'min_samples_split': 7}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:40:59,614] Trial 15 finished with value: 0.663785423548431 and parameters: {'n_estimators': 169, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 0 with value: 0.6839184273276918.
[I 2026-06-26 17:41:02,833] Trial 16 finished with value: 0.6841103841243455 and parameters: {'n_estimators': 121, 'max_depth': 16, 'min_samples_split': 8}. Best is trial 16 with value: 0.6841103841243455.
[I 2026-06-26 17:41:04,571] Trial 17 finished with value: 0.6460016279395707 and parameters: {'n_estimators': 119, 'max_depth': 7, 'min_samples_split': 10}. Best is trial 16 with value: 0.6841103841243455.
[I 2026-06-26 17:41:06,484] Trial 18 finished with value: 0.6739526472257724 and parameters: {'n_estimators': 60, 'max_depth': 22, 'min_samples_split': 8}. Best is trial 16 with value: 0.6841103841243455.
[I 2026-06-26 17:41:07,782] Trial 19 finished with value: 0.5855455110529257 and parameters: {'n_estimators': 111, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 16 with value: 0.6841103841243455.
[I 2026-06-26 17:41:10,439] Trial 20 finished with value: 0.6796806547830561 and parameters: {'n_estimators': 155, 'max_depth': 12, 'min_samples_split': 9}. Best is trial 16 with value: 0.6841103841243455.
[I 2026-06-26 17:41:14,281] Trial 21 finished with value: 0.6827001118201688 and parameters: {'n_estimators': 184, 'max_depth': 17, 'min_samples_split': 7}. Best is trial 16 with value: 0.6841103841243455.
[I 2026-06-26 17:41:15,891] Trial 22 finished with value: 0.6849313613976892 and parameters: {'n_estimators': 73, 'max_depth': 16, 'min_samples_split': 5}. Best is trial 22 with value: 0.6849313613976892.
[I 2026-06-26 17:41:17,085] Trial 23 finished with value: 0.6695287495586194 and parameters: {'n_estimators': 71, 'max_depth': 10, 'min_samples_split': 5}. Best is trial 22 with value: 0.6849313613976892.
[I 2026-06-26 17:41:18,236] Trial 24 finished with value: 0.6613799137902532 and parameters: {'n_estimators': 39, 'max_depth': 25, 'min_samples_split': 5}. Best is trial 22 with value: 0.6849313613976892.
[I 2026-06-26 17:41:20,552] Trial 25 finished with value: 0.678619853105872 and parameters: {'n_estimators': 102, 'max_depth': 19, 'min_samples_split': 5}. Best is trial 22 with value: 0.6849313613976892.
[I 2026-06-26 17:41:21,892] Trial 26 finished with value: 0.6654256226042752 and parameters: {'n_estimators': 88, 'max_depth': 9, 'min_samples_split': 8}. Best is trial 22 with value: 0.6849313613976892.
[I 2026-06-26 17:41:23,222] Trial 27 finished with value: 0.6519956070003409 and parameters: {'n_estimators': 45, 'max_depth': 32, 'min_samples_split': 9}. Best is trial 22 with value: 0.6849313613976892.
[I 2026-06-26 17:41:25,636] Trial 28 finished with value: 0.6849974655663871 and parameters: {'n_estimators': 118, 'max_depth': 16, 'min_samples_split': 7}. Best is trial 28 with value: 0.6849974655663871.
[I 2026-06-26 17:41:27,764] Trial 29 finished with value: 0.679076497856374 and parameters: {'n_estimators': 123, 'max_depth': 12, 'min_samples_split': 5}. Best is trial 28 with value: 0.6849974655663871.
[I 2026-06-26 17:41:29,270] Trial 30 finished with value: 0.6242289127306189 and parameters: {'n_estimators': 141, 'max_depth': 6, 'min_samples_split': 6}. Best is trial 28 with value: 0.6849974655663871.
[I 2026-06-26 17:41:31,503] Trial 31 finished with value: 0.6844125305290033 and parameters: {'n_estimators': 92, 'max_depth': 16, 'min_samples_split': 8}. Best is trial 28 with value: 0.6849974655663871.
[I 2026-06-26 17:41:33,526] Trial 32 finished with value: 0.6826595672325377 and parameters: {'n_estimators': 78, 'max_depth': 17, 'min_samples_split': 7}. Best is trial 28 with value: 0.6849974655663871.
[I 2026-06-26 17:41:36,082] Trial 33 finished with value: 0.6853416204604165 and parameters: {'n_estimators': 106, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:41:38,161] Trial 34 finished with value: 0.6794838351187332 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 9}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:41:41,442] Trial 35 finished with value: 0.6597279768531787 and parameters: {'n_estimators': 109, 'max_depth': 25, 'min_samples_split': 6}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:41:43,467] Trial 36 finished with value: 0.6760069858600646 and parameters: {'n_estimators': 68, 'max_depth': 21, 'min_samples_split': 7}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:41:45,566] Trial 37 finished with value: 0.6836456077893155 and parameters: {'n_estimators': 91, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:41:47,239] Trial 38 finished with value: 0.6740290244280828 and parameters: {'n_estimators': 82, 'max_depth': 11, 'min_samples_split': 10}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:41:48,247] Trial 39 finished with value: 0.6563446557484459 and parameters: {'n_estimators': 57, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:41:50,762] Trial 40 finished with value: 0.6814204092459032 and parameters: {'n_estimators': 97, 'max_depth': 18, 'min_samples_split': 3}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:41:53,518] Trial 41 finished with value: 0.6844105724402079 and parameters: {'n_estimators': 116, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:41:56,181] Trial 42 finished with value: 0.6845901231254959 and parameters: {'n_estimators': 112, 'max_depth': 14, 'min_samples_split': 8}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:00,074] Trial 43 finished with value: 0.669656449958642 and parameters: {'n_estimators': 137, 'max_depth': 23, 'min_samples_split': 8}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:02,987] Trial 44 finished with value: 0.6810245210343512 and parameters: {'n_estimators': 126, 'max_depth': 13, 'min_samples_split': 7}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:03,879] Trial 45 finished with value: 0.33569060961392927 and parameters: {'n_estimators': 109, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:07,464] Trial 46 finished with value: 0.6792245578285826 and parameters: {'n_estimators': 130, 'max_depth': 20, 'min_samples_split': 9}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:11,817] Trial 47 finished with value: 0.6550279565463357 and parameters: {'n_estimators': 147, 'max_depth': 27, 'min_samples_split': 7}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:12,301] Trial 48 finished with value: 0.6667207994641424 and parameters: {'n_estimators': 16, 'max_depth': 10, 'min_samples_split': 4}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:14,704] Trial 49 finished with value: 0.6839509928743397 and parameters: {'n_estimators': 96, 'max_depth': 16, 'min_samples_split': 6}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:16,674] Trial 50 finished with value: 0.6824351256810377 and parameters: {'n_estimators': 84, 'max_depth': 13, 'min_samples_split': 7}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:19,539] Trial 51 finished with value: 0.6844062388710204 and parameters: {'n_estimators': 115, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:22,009] Trial 52 finished with value: 0.6847368584310198 and parameters: {'n_estimators': 104, 'max_depth': 15, 'min_samples_split': 8}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:23,992] Trial 53 finished with value: 0.6750699980829562 and parameters: {'n_estimators': 104, 'max_depth': 11, 'min_samples_split': 9}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:26,017] Trial 54 finished with value: 0.6829406518593986 and parameters: {'n_estimators': 72, 'max_depth': 18, 'min_samples_split': 8}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:28,090] Trial 55 finished with value: 0.6849537667328744 and parameters: {'n_estimators': 92, 'max_depth': 14, 'min_samples_split': 7}. Best is trial 33 with value: 0.6853416204604165.
[I 2026-06-26 17:42:29,674] Trial 56 finished with value: 0.6866751086170879 and parameters: {'n_estimators': 63, 'max_depth': 14, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:30,766] Trial 57 finished with value: 0.675863689663183 and parameters: {'n_estimators': 50, 'max_depth': 11, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:32,014] Trial 58 finished with value: 0.6469168182052492 and parameters: {'n_estimators': 75, 'max_depth': 8, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:33,737] Trial 59 finished with value: 0.6738652766139607 and parameters: {'n_estimators': 60, 'max_depth': 22, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:35,795] Trial 60 finished with value: 0.6448453989643828 and parameters: {'n_estimators': 66, 'max_depth': 28, 'min_samples_split': 5}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:37,718] Trial 61 finished with value: 0.6852373947809787 and parameters: {'n_estimators': 83, 'max_depth': 14, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:39,685] Trial 62 finished with value: 0.681987620329712 and parameters: {'n_estimators': 88, 'max_depth': 13, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:41,915] Trial 63 finished with value: 0.6793480375723344 and parameters: {'n_estimators': 80, 'max_depth': 19, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:43,271] Trial 64 finished with value: 0.6853085817676587 and parameters: {'n_estimators': 52, 'max_depth': 14, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:44,031] Trial 65 finished with value: 0.6661746900353105 and parameters: {'n_estimators': 36, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:44,688] Trial 66 finished with value: 0.670603101716441 and parameters: {'n_estimators': 26, 'max_depth': 12, 'min_samples_split': 5}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:45,997] Trial 67 finished with value: 0.6848299638106259 and parameters: {'n_estimators': 49, 'max_depth': 14, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:47,663] Trial 68 finished with value: 0.6841053966162427 and parameters: {'n_estimators': 63, 'max_depth': 17, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:48,721] Trial 69 finished with value: 0.6752722115521512 and parameters: {'n_estimators': 54, 'max_depth': 10, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:49,160] Trial 70 finished with value: 0.5528947488535634 and parameters: {'n_estimators': 32, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:50,393] Trial 71 finished with value: 0.6846716087562101 and parameters: {'n_estimators': 51, 'max_depth': 14, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:51,603] Trial 72 finished with value: 0.6852589902495914 and parameters: {'n_estimators': 45, 'max_depth': 16, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:52,956] Trial 73 finished with value: 0.6782454846022866 and parameters: {'n_estimators': 44, 'max_depth': 20, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:54,853] Trial 74 finished with value: 0.6824576635681308 and parameters: {'n_estimators': 73, 'max_depth': 17, 'min_samples_split': 5}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:56,406] Trial 75 finished with value: 0.6800724484513594 and parameters: {'n_estimators': 68, 'max_depth': 12, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:42:59,420] Trial 76 finished with value: 0.6674564329496956 and parameters: {'n_estimators': 94, 'max_depth': 24, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:00,259] Trial 77 finished with value: 0.6857125833465196 and parameters: {'n_estimators': 28, 'max_depth': 16, 'min_samples_split': 5}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:01,068] Trial 78 finished with value: 0.6803283125473967 and parameters: {'n_estimators': 26, 'max_depth': 18, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:01,505] Trial 79 finished with value: 0.675836353598524 and parameters: {'n_estimators': 11, 'max_depth': 15, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:02,349] Trial 80 finished with value: 0.6782974980731258 and parameters: {'n_estimators': 44, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:03,335] Trial 81 finished with value: 0.6840758255167265 and parameters: {'n_estimators': 34, 'max_depth': 16, 'min_samples_split': 5}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:04,112] Trial 82 finished with value: 0.6810555794421693 and parameters: {'n_estimators': 28, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:05,708] Trial 83 finished with value: 0.6800882461062551 and parameters: {'n_estimators': 57, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:06,336] Trial 84 finished with value: 0.6813988463067877 and parameters: {'n_estimators': 21, 'max_depth': 16, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:07,352] Trial 85 finished with value: 0.6833013176942015 and parameters: {'n_estimators': 42, 'max_depth': 13, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:09,655] Trial 86 finished with value: 0.6774181455411303 and parameters: {'n_estimators': 85, 'max_depth': 20, 'min_samples_split': 2}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:11,126] Trial 87 finished with value: 0.6843970096541443 and parameters: {'n_estimators': 60, 'max_depth': 14, 'min_samples_split': 8}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:13,328] Trial 88 finished with value: 0.6698513019498177 and parameters: {'n_estimators': 78, 'max_depth': 22, 'min_samples_split': 5}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:16,336] Trial 89 finished with value: 0.6825674423525092 and parameters: {'n_estimators': 119, 'max_depth': 17, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:18,036] Trial 90 finished with value: 0.6837807457640904 and parameters: {'n_estimators': 65, 'max_depth': 15, 'min_samples_split': 4}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:19,337] Trial 91 finished with value: 0.6849534044813963 and parameters: {'n_estimators': 50, 'max_depth': 14, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:21,644] Trial 92 finished with value: 0.6792713318548811 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:23,191] Trial 93 finished with value: 0.6832296247918972 and parameters: {'n_estimators': 51, 'max_depth': 15, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:24,273] Trial 94 finished with value: 0.6738460203017709 and parameters: {'n_estimators': 40, 'max_depth': 11, 'min_samples_split': 6}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:25,797] Trial 95 finished with value: 0.6846438303294006 and parameters: {'n_estimators': 55, 'max_depth': 16, 'min_samples_split': 7}. Best is trial 56 with value: 0.6866751086170879.
[I 2026-06-26 17:43:27,453] Trial 96 finished with value: 0.6828092530520888 and parameters: {'n_estimators': 70, 'max_depth': 13, 'min_samples_split': 8}. Best is trial 56 with value: 0.6866751086170879.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
56,56,0.686675,2026-06-26 17:42:28.090331,2026-06-26 17:42:29.674602,0 days 00:00:01.584271,14,7,63,COMPLETE
77,77,0.685713,2026-06-26 17:42:59.420191,2026-06-26 17:43:00.259509,0 days 00:00:00.839318,16,5,28,COMPLETE
98,98,0.685376,2026-06-26 17:43:29.182622,2026-06-26 17:43:30.306105,0 days 00:00:01.123483,14,7,47,COMPLETE
33,33,0.685342,2026-06-26 17:41:33.526504,2026-06-26 17:41:36.082948,0 days 00:00:02.556444,15,8,106,COMPLETE
64,64,0.685309,2026-06-26 17:42:41.915816,2026-06-26 17:42:43.271985,0 days 00:00:01.356169,14,7,52,COMPLETE

In [67]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_f1_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_f1_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_f1_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for F1')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.98      0.94      0.96     10355
           1       0.59      0.84      0.69      1035

    accuracy                           0.93     11390
   macro avg       0.79      0.89      0.83     11390
weighted avg       0.95      0.93      0.94     11390

In [68]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.5121409043270325

### Conclusions

In [69]:
pd.concat(classification_reports, keys=classification_report_keys)

                                                                 precision  \
Baseline Decision Tree Classifier                  0              0.959302
                                                   1              0.600392
                                                   accuracy       0.927129
                                                   macro avg      0.779847
                                                   weighted avg   0.926688
Decision Tree Classifier with Standard Scaling     0              0.959321
                                                   1              0.603346
                                                   accuracy       0.927568
                                                   macro avg      0.781334
                                                   weighted avg   0.926974
Baseline Random Forest Classifier                  0              0.959850
                                                   1              0.615538
                                                   accuracy       0.929500
                                                   macro avg      0.787694
                                                   weighted avg   0.928562
Random Forest Classifier with Standard Scaling     0              0.959977
                                                   1              0.621486
                                                   accuracy       0.930378
                                                   macro avg      0.790731
                                                   weighted avg   0.929219
Random Forest Classifier with Parameter Tuning ... 0              0.985125
                                                   1              0.564444
                                                   accuracy       0.926953
                                                   macro avg      0.774785
                                                   weighted avg   0.946898
Random Forest Classifier with Parameter Tuning ... 0              0.983751
                                                   1              0.589744
                                                   accuracy       0.932485
                                                   macro avg      0.786747
                                                   weighted avg   0.947947

                                                                   recall  \
Baseline Decision Tree Classifier                  0             0.960599
                                                   1             0.592271
                                                   accuracy      0.927129
                                                   macro avg     0.776435
                                                   weighted avg  0.927129
Decision Tree Classifier with Standard Scaling     0             0.961082
                                                   1             0.592271
                                                   accuracy      0.927568
                                                   macro avg     0.776676
                                                   weighted avg  0.927568
Baseline Random Forest Classifier                  0             0.962723
                                                   1             0.597101
                                                   accuracy      0.929500
                                                   macro avg     0.779912
                                                   weighted avg  0.929500
Random Forest Classifier with Standard Scaling     0             0.963592
                                                   1             0.598068
                                                   accuracy      0.930378
                                                   macro avg     0.780830
                                                   weighted avg  0.930378
Random Forest Classifier with Parameter Tuning ... 0             0.933752
                                                   1             0.858937
                                                   accuracy      0.926953
                                                   macro avg     0.896345
                                                   weighted avg  0.926953
Random Forest Classifier with Parameter Tuning ... 0             0.941284
                                                   1             0.844444
                                                   accuracy      0.932485
                                                   macro avg     0.892864
                                                   weighted avg  0.932485

                                                                 f1-score  \
Baseline Decision Tree Classifier                  0             0.959950
                                                   1             0.596304
                                                   accuracy      0.927129
                                                   macro avg     0.778127
                                                   weighted avg  0.926906
Decision Tree Classifier with Standard Scaling     0             0.960201
                                                   1             0.597757
                                                   accuracy      0.927568
                                                   macro avg     0.778979
                                                   weighted avg  0.927266
Baseline Random Forest Classifier                  0             0.961284
                                                   1             0.606179
                                                   accuracy      0.929500
                                                   macro avg     0.783732
                                                   weighted avg  0.929016
Random Forest Classifier with Standard Scaling     0             0.961781
                                                   1             0.609552
                                                   accuracy      0.930378
                                                   macro avg     0.785667
                                                   weighted avg  0.929774
Random Forest Classifier with Parameter Tuning ... 0             0.958751
                                                   1             0.681226
                                                   accuracy      0.926953
                                                   macro avg     0.819988
                                                   weighted avg  0.933532
Random Forest Classifier with Parameter Tuning ... 0             0.962049
                                                   1             0.694478
                                                   accuracy      0.932485
                                                   macro avg     0.828263
                                                   weighted avg  0.937735

                                                                      support
Baseline Decision Tree Classifier                  0             10355.000000
                                                   1              1035.000000
                                                   accuracy          0.927129
                                                   macro avg     11390.000000
                                                   weighted avg  11390.000000
Decision Tree Classifier with Standard Scaling     0             10355.000000
                                                   1              1035.000000
                                                   accuracy          0.927568
                                                   macro avg     11390.000000
                                                   weighted avg  11390.000000
Baseline Random Forest Classifier                  0             10355.000000
                                                   1              1035.000000
                                                   accuracy          0.929500
                                                   macro avg     11390.000000
                                                   weighted avg  11390.000000
Random Forest Classifier with Standard Scaling     0             10355.000000
                                                   1              1035.000000
                                                   accuracy          0.930378
                                                   macro avg     11390.000000
                                                   weighted avg  11390.000000
Random Forest Classifier with Parameter Tuning ... 0             10355.000000
                                                   1              1035.000000
                                                   accuracy          0.926953
                                                   macro avg     11390.000000
                                                   weighted avg  11390.000000
Random Forest Classifier with Parameter Tuning ... 0             10355.000000
                                                   1              1035.000000
                                                   accuracy          0.932485
                                                   macro avg     11390.000000
                                                   weighted avg  11390.000000

## PPP

In [70]:
random_state = 42
classification_reports = []
classification_report_keys = []

### Import Data

In [71]:
# Import credit card datasaet
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/ppp_cleaned.csv')
df

,ProcessingMethod,BorrowerState,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,ServicingLenderState,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,...,MORTGAGE_INTEREST_PROCEED_pct,RENT_PROCEED_pct,REFINANCE_EIDL_PROCEED_pct,HEALTH_CARE_PROCEED_pct,DEBT_INTEREST_PROCEED_pct,PROCEED_Per_Job,Fraud,DateApproved_int,ForgivenessDate_int,LoanStatusDate_int
0,0.0,48.0,2.0,24,769358.78,769358.78,11.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,12409.01,0,1588291200,1605830400,1608249600
1,0.0,48.0,2.0,24,736927.79,736927.79,11.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,10094.90,0,1588291200,1628726400,1632787200
2,0.0,48.0,2.0,24,691355.00,691355.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9218.07,0,1588291200,1612915200,1615939200
3,0.0,48.0,2.0,24,499871.00,499871.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,23803.38,0,1588291200,1631232000,1634342400
4,0.0,48.0,2.0,24,367437.00,367437.00,37.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,14697.48,0,1588291200,1617840000,1629158400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968527,0.0,56.0,2.0,24,150000.00,150000.00,54.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10000.00,0,1585872000,1607472000,1610496000
968528,0.0,56.0,2.0,24,150000.00,150000.00,31.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3452.38,0,1586822400,1604361600,1607385600
968529,1.0,56.0,2.0,60,150000.00,150000.00,54.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,29999.40,0,1613088000,1629158400,1631664000
968530,0.0,56.0,2.0,60,150000.00,150000.00,18.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,21428.57,0,1586908800,1645574400,1646697600
968531,0.0,56.0,2.0,24,150000.00,150000.00,54.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,13636.36,0,1586390400,1632268800,1634860800

### Undersampling due to heavy class imbalance

In [72]:
from collections import Counter


X = df.drop(columns='Fraud')
y = df['Fraud']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(sampling_strategy=0.1, random_state=random_state)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 968437, 1: 95})
Resampled dataset shape: Counter({0: 950, 1: 95})

### Split Data

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Decision Tree Classifier
#### (No feature scaling)

In [74]:
model = DecisionTreeClassifier(random_state=random_state)

In [75]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [76]:
y_pred = model.predict(X_test)

In [77]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Decision Tree Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98       190
           1       0.78      0.74      0.76        19

    accuracy                           0.96       209
   macro avg       0.88      0.86      0.87       209
weighted avg       0.96      0.96      0.96       209

In [78]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.5970228601807549

### Feature Scaling + Decision Tree Classifier

In [79]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [80]:
model = DecisionTreeClassifier(random_state=random_state)

In [81]:
model.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [82]:
y_pred = model.predict(X_test_scaled)

In [83]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Decision Tree Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98       190
           1       0.78      0.74      0.76        19

    accuracy                           0.96       209
   macro avg       0.88      0.86      0.87       209
weighted avg       0.96      0.96      0.96       209

In [84]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.5970228601807549

### Baseline Random Forest Classifier
#### (No feature scaling)

In [85]:
model = RandomForestClassifier(random_state=random_state)

In [86]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [87]:
y_pred = model.predict(X_test)

In [88]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Random Forest Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98       190
           1       0.78      0.74      0.76        19

    accuracy                           0.96       209
   macro avg       0.88      0.86      0.87       209
weighted avg       0.96      0.96      0.96       209

In [89]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.5970228601807549

### Feature Scaling + Decision Tree Classifier

In [90]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [91]:
model = RandomForestClassifier(random_state=random_state)

In [92]:
model.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

In [93]:
y_pred = model.predict(X_test_scaled)

In [94]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98       190
           1       0.78      0.74      0.76        19

    accuracy                           0.96       209
   macro avg       0.88      0.86      0.87       209
weighted avg       0.96      0.96      0.96       209

In [95]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.5970228601807549

### Parameter Tuning Random Forest (optimized for recall)

In [96]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [97]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_recall_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_recall_df)

[I 2026-06-26 17:43:35,242] A new study created in memory with name: no-name-c0d360fb-b3a4-4941-b5c4-6840b60256cd
[I 2026-06-26 17:43:35,474] Trial 0 finished with value: 0.8300000000000001 and parameters: {'n_estimators': 166, 'max_depth': 28, 'min_samples_split': 3}. Best is trial 0 with value: 0.8300000000000001.
[I 2026-06-26 17:43:35,646] Trial 1 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 139, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:35,834] Trial 2 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 149, 'max_depth': 27, 'min_samples_split': 10}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:36,055] Trial 3 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 178, 'max_depth': 27, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:36,166] Trial 4 finished with value: 0.8425 and parameters: {'n_estimators': 79, 'max_depth': 27, 'min_samples_split': 4}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:36,245] Trial 5 finished with value: 0.9225000000000001 and parameters: {'n_estimators': 49, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:36,404] Trial 6 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 111, 'max_depth': 9, 'min_samples_split': 10}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:36,546] Trial 7 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 113, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:36,765] Trial 8 finished with value: 0.8425 and parameters: {'n_estimators': 149, 'max_depth': 29, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:36,983] Trial 9 finished with value: 0.8425 and parameters: {'n_estimators': 157, 'max_depth': 16, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:37,240] Trial 10 finished with value: 0.8691666666666666 and parameters: {'n_estimators': 200, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:37,366] Trial 11 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 114, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:37,476] Trial 12 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 84, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:37,507] Trial 13 finished with value: 0.8825 and parameters: {'n_estimators': 16, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:37,682] Trial 14 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 127, 'max_depth': 6, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:37,792] Trial 15 finished with value: 0.9225000000000001 and parameters: {'n_estimators': 82, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:37,965] Trial 16 finished with value: 0.9091666666666667 and parameters: {'n_estimators': 128, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:38,061] Trial 17 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 58, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:38,188] Trial 18 finished with value: 0.8958333333333334 and parameters: {'n_estimators': 97, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:38,364] Trial 19 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 136, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:38,613] Trial 20 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 189, 'max_depth': 11, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:38,771] Trial 21 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 112, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:38,896] Trial 22 finished with value: 0.9225000000000001 and parameters: {'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:39,055] Trial 23 finished with value: 0.8691666666666666 and parameters: {'n_estimators': 125, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:39,229] Trial 24 finished with value: 0.9091666666666667 and parameters: {'n_estimators': 139, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:39,324] Trial 25 finished with value: 0.9225000000000001 and parameters: {'n_estimators': 61, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:39,484] Trial 26 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 114, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:39,687] Trial 27 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 168, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:39,750] Trial 28 finished with value: 0.8825 and parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:39,862] Trial 29 finished with value: 0.9225000000000001 and parameters: {'n_estimators': 89, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:40,080] Trial 30 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 164, 'max_depth': 5, 'min_samples_split': 4}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:40,262] Trial 31 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 139, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:40,444] Trial 32 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 139, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:40,625] Trial 33 finished with value: 0.8958333333333334 and parameters: {'n_estimators': 121, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:40,830] Trial 34 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 147, 'max_depth': 17, 'min_samples_split': 10}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:40,940] Trial 35 finished with value: 0.9225000000000001 and parameters: {'n_estimators': 98, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:41,082] Trial 36 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 134, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:41,191] Trial 37 finished with value: 0.8825 and parameters: {'n_estimators': 73, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:41,381] Trial 38 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 179, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:41,555] Trial 39 finished with value: 0.8691666666666666 and parameters: {'n_estimators': 155, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:41,681] Trial 40 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 108, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:41,823] Trial 41 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 119, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:41,932] Trial 42 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 108, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:42,074] Trial 43 finished with value: 0.8958333333333334 and parameters: {'n_estimators': 118, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:42,233] Trial 44 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 148, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:42,360] Trial 45 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 95, 'max_depth': 19, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:42,557] Trial 46 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 130, 'max_depth': 11, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:42,697] Trial 47 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 112, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:42,808] Trial 48 finished with value: 0.8825 and parameters: {'n_estimators': 74, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:42,963] Trial 49 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 104, 'max_depth': 23, 'min_samples_split': 10}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:43,121] Trial 50 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 154, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:43,292] Trial 51 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 178, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:43,451] Trial 52 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 166, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:43,595] Trial 53 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 135, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:43,800] Trial 54 finished with value: 0.8958333333333334 and parameters: {'n_estimators': 189, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:43,991] Trial 55 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 162, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:44,180] Trial 56 finished with value: 0.8958333333333334 and parameters: {'n_estimators': 172, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:44,349] Trial 57 finished with value: 0.8691666666666666 and parameters: {'n_estimators': 125, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:44,491] Trial 58 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 90, 'max_depth': 8, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:44,679] Trial 59 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 143, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:44,847] Trial 60 finished with value: 0.8958333333333334 and parameters: {'n_estimators': 130, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:45,034] Trial 61 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 140, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:45,174] Trial 62 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 114, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:45,300] Trial 63 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 104, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:45,471] Trial 64 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 124, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:45,647] Trial 65 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 146, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:45,822] Trial 66 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 136, 'max_depth': 32, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:46,044] Trial 67 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 199, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:46,203] Trial 68 finished with value: 0.8958333333333334 and parameters: {'n_estimators': 153, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:46,393] Trial 69 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 160, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:46,552] Trial 70 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 132, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:46,693] Trial 71 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 117, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:46,896] Trial 72 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 139, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:47,059] Trial 73 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 122, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:47,284] Trial 74 finished with value: 0.8691666666666666 and parameters: {'n_estimators': 171, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:47,426] Trial 75 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 110, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:47,625] Trial 76 finished with value: 0.8958333333333334 and parameters: {'n_estimators': 151, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:47,764] Trial 77 finished with value: 0.9225000000000001 and parameters: {'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:47,885] Trial 78 finished with value: 0.9225000000000001 and parameters: {'n_estimators': 91, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:48,074] Trial 79 finished with value: 0.9091666666666667 and parameters: {'n_estimators': 144, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:48,261] Trial 80 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 130, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:48,404] Trial 81 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 118, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:48,546] Trial 82 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 136, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:48,705] Trial 83 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 127, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:48,865] Trial 84 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 143, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:49,065] Trial 85 finished with value: 0.9091666666666667 and parameters: {'n_estimators': 157, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:49,221] Trial 86 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 134, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:49,283] Trial 87 finished with value: 0.9225000000000001 and parameters: {'n_estimators': 22, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:49,426] Trial 88 finished with value: 0.8958333333333334 and parameters: {'n_estimators': 113, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:49,583] Trial 89 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 149, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:49,710] Trial 90 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 107, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:49,964] Trial 91 finished with value: 0.8558333333333333 and parameters: {'n_estimators': 191, 'max_depth': 10, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:50,128] Trial 92 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 123, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:50,346] Trial 93 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 180, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:50,553] Trial 94 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 168, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:50,758] Trial 95 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 140, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.
[I 2026-06-26 17:43:50,958] Trial 96 finished with value: 0.9350000000000002 and parameters: {'n_estimators': 160, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 1 with value: 0.9350000000000002.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
1,1,0.935,2026-06-26 17:43:35.474046,2026-06-26 17:43:35.646130,0 days 00:00:00.172084,2,7,139,COMPLETE
19,19,0.935,2026-06-26 17:43:38.188882,2026-06-26 17:43:38.364519,0 days 00:00:00.175637,2,6,136,COMPLETE
11,11,0.935,2026-06-26 17:43:37.240260,2026-06-26 17:43:37.366131,0 days 00:00:00.125871,2,8,114,COMPLETE
7,7,0.935,2026-06-26 17:43:36.404097,2026-06-26 17:43:36.546114,0 days 00:00:00.142017,2,9,113,COMPLETE
31,31,0.935,2026-06-26 17:43:40.081324,2026-06-26 17:43:40.262924,0 days 00:00:00.181600,2,6,139,COMPLETE

In [98]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_recall_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_recall_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_recall_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for Recall')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.88      0.93       190
           1       0.44      0.89      0.59        19

    accuracy                           0.89       209
   macro avg       0.71      0.89      0.76       209
weighted avg       0.94      0.89      0.90       209

In [99]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.3995828732670838

### Parameter Tuning Random Forest (Optimized for F1)

In [100]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_f1_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_f1_df)

[I 2026-06-26 17:43:51,704] A new study created in memory with name: no-name-61162d61-e7b6-440b-aeec-725772734115
[I 2026-06-26 17:43:51,866] Trial 0 finished with value: 0.8258399664851279 and parameters: {'n_estimators': 117, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:52,020] Trial 1 finished with value: 0.8229064039408869 and parameters: {'n_estimators': 123, 'max_depth': 30, 'min_samples_split': 3}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:52,222] Trial 2 finished with value: 0.722058422058422 and parameters: {'n_estimators': 170, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:52,322] Trial 3 finished with value: 0.8161519533488388 and parameters: {'n_estimators': 61, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:52,432] Trial 4 finished with value: 0.7308589906647317 and parameters: {'n_estimators': 61, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:52,564] Trial 5 finished with value: 0.8161519533488388 and parameters: {'n_estimators': 82, 'max_depth': 16, 'min_samples_split': 8}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:52,813] Trial 6 finished with value: 0.8229064039408869 and parameters: {'n_estimators': 178, 'max_depth': 14, 'min_samples_split': 3}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:53,013] Trial 7 finished with value: 0.8161519533488388 and parameters: {'n_estimators': 162, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:53,278] Trial 8 finished with value: 0.65860808395318 and parameters: {'n_estimators': 174, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:53,483] Trial 9 finished with value: 0.8049153942090538 and parameters: {'n_estimators': 114, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:53,561] Trial 10 finished with value: 0.8115173722436694 and parameters: {'n_estimators': 28, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:53,809] Trial 11 finished with value: 0.80623973727422 and parameters: {'n_estimators': 127, 'max_depth': 32, 'min_samples_split': 2}. Best is trial 0 with value: 0.8258399664851279.
[I 2026-06-26 17:43:54,074] Trial 12 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 135, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:54,341] Trial 13 finished with value: 0.8257202567547395 and parameters: {'n_estimators': 141, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:54,541] Trial 14 finished with value: 0.8148418878118544 and parameters: {'n_estimators': 89, 'max_depth': 9, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:54,802] Trial 15 finished with value: 0.8148171368861025 and parameters: {'n_estimators': 140, 'max_depth': 20, 'min_samples_split': 5}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:54,995] Trial 16 finished with value: 0.8197432452604867 and parameters: {'n_estimators': 98, 'max_depth': 11, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:55,292] Trial 17 finished with value: 0.65860808395318 and parameters: {'n_estimators': 194, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:55,572] Trial 18 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 149, 'max_depth': 23, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:55,844] Trial 19 finished with value: 0.8195790416480072 and parameters: {'n_estimators': 146, 'max_depth': 24, 'min_samples_split': 5}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:56,196] Trial 20 finished with value: 0.8245051500223914 and parameters: {'n_estimators': 198, 'max_depth': 25, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:56,481] Trial 21 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 157, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:56,772] Trial 22 finished with value: 0.8245051500223914 and parameters: {'n_estimators': 155, 'max_depth': 13, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:57,026] Trial 23 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 134, 'max_depth': 24, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:57,311] Trial 24 finished with value: 0.8148171368861025 and parameters: {'n_estimators': 155, 'max_depth': 23, 'min_samples_split': 6}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:57,511] Trial 25 finished with value: 0.8195790416480072 and parameters: {'n_estimators': 105, 'max_depth': 18, 'min_samples_split': 5}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:57,796] Trial 26 finished with value: 0.8245051500223914 and parameters: {'n_estimators': 158, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:58,141] Trial 27 finished with value: 0.8229064039408869 and parameters: {'n_estimators': 189, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:58,471] Trial 28 finished with value: 0.8195790416480072 and parameters: {'n_estimators': 181, 'max_depth': 10, 'min_samples_split': 5}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:58,693] Trial 29 finished with value: 0.8148171368861025 and parameters: {'n_estimators': 115, 'max_depth': 20, 'min_samples_split': 6}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:58,954] Trial 30 finished with value: 0.8148418878118544 and parameters: {'n_estimators': 145, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:59,199] Trial 31 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 130, 'max_depth': 25, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:59,442] Trial 32 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 133, 'max_depth': 26, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:59,746] Trial 33 finished with value: 0.8229064039408869 and parameters: {'n_estimators': 168, 'max_depth': 21, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:43:59,979] Trial 34 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 119, 'max_depth': 29, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:00,251] Trial 35 finished with value: 0.8161519533488388 and parameters: {'n_estimators': 148, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:00,504] Trial 36 finished with value: 0.8161519533488388 and parameters: {'n_estimators': 133, 'max_depth': 14, 'min_samples_split': 10}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:00,658] Trial 37 finished with value: 0.8181444991789821 and parameters: {'n_estimators': 71, 'max_depth': 28, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:00,742] Trial 38 finished with value: 0.8166215106732349 and parameters: {'n_estimators': 26, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:01,039] Trial 39 finished with value: 0.8161519533488388 and parameters: {'n_estimators': 166, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:01,246] Trial 40 finished with value: 0.8195790416480072 and parameters: {'n_estimators': 104, 'max_depth': 16, 'min_samples_split': 5}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:01,488] Trial 41 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 130, 'max_depth': 22, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:01,720] Trial 42 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 120, 'max_depth': 26, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:01,982] Trial 43 finished with value: 0.80623973727422 and parameters: {'n_estimators': 136, 'max_depth': 29, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:02,258] Trial 44 finished with value: 0.8245051500223914 and parameters: {'n_estimators': 151, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:02,469] Trial 45 finished with value: 0.8229064039408869 and parameters: {'n_estimators': 111, 'max_depth': 23, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:02,542] Trial 46 finished with value: 0.7898923554095968 and parameters: {'n_estimators': 14, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:02,779] Trial 47 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 126, 'max_depth': 31, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:03,076] Trial 48 finished with value: 0.725229669415716 and parameters: {'n_estimators': 180, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:03,267] Trial 49 finished with value: 0.8161519533488388 and parameters: {'n_estimators': 93, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:03,561] Trial 50 finished with value: 0.8229064039408869 and parameters: {'n_estimators': 165, 'max_depth': 26, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:03,816] Trial 51 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 136, 'max_depth': 27, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:04,058] Trial 52 finished with value: 0.80623973727422 and parameters: {'n_estimators': 125, 'max_depth': 21, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:04,331] Trial 53 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 142, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:04,616] Trial 54 finished with value: 0.8245051500223914 and parameters: {'n_estimators': 158, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:04,925] Trial 55 finished with value: 0.8195790416480072 and parameters: {'n_estimators': 173, 'max_depth': 24, 'min_samples_split': 5}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:05,182] Trial 56 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 134, 'max_depth': 26, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:05,422] Trial 57 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 125, 'max_depth': 15, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:05,693] Trial 58 finished with value: 0.8148418878118544 and parameters: {'n_estimators': 149, 'max_depth': 11, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:05,915] Trial 59 finished with value: 0.8105605554993763 and parameters: {'n_estimators': 111, 'max_depth': 5, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:06,168] Trial 60 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 139, 'max_depth': 18, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:06,398] Trial 61 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 119, 'max_depth': 28, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:06,645] Trial 62 finished with value: 0.8257202567547395 and parameters: {'n_estimators': 130, 'max_depth': 29, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:06,847] Trial 63 finished with value: 0.8148171368861025 and parameters: {'n_estimators': 99, 'max_depth': 23, 'min_samples_split': 5}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:07,086] Trial 64 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 118, 'max_depth': 32, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:07,372] Trial 65 finished with value: 0.8245051500223914 and parameters: {'n_estimators': 160, 'max_depth': 21, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:07,647] Trial 66 finished with value: 0.8195790416480072 and parameters: {'n_estimators': 152, 'max_depth': 25, 'min_samples_split': 5}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:07,904] Trial 67 finished with value: 0.80623973727422 and parameters: {'n_estimators': 140, 'max_depth': 29, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:08,180] Trial 68 finished with value: 0.8148171368861025 and parameters: {'n_estimators': 145, 'max_depth': 19, 'min_samples_split': 6}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:08,387] Trial 69 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 109, 'max_depth': 24, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:08,502] Trial 70 finished with value: 0.8120032840722496 and parameters: {'n_estimators': 48, 'max_depth': 22, 'min_samples_split': 5}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:08,750] Trial 71 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 130, 'max_depth': 22, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:08,989] Trial 72 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 131, 'max_depth': 27, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:09,233] Trial 73 finished with value: 0.80623973727422 and parameters: {'n_estimators': 124, 'max_depth': 17, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:09,511] Trial 74 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 143, 'max_depth': 30, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:09,805] Trial 75 finished with value: 0.8245051500223914 and parameters: {'n_estimators': 154, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:10,033] Trial 76 finished with value: 0.8229064039408869 and parameters: {'n_estimators': 117, 'max_depth': 13, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:10,202] Trial 77 finished with value: 0.8229064039408869 and parameters: {'n_estimators': 81, 'max_depth': 26, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:10,405] Trial 78 finished with value: 0.8161519533488388 and parameters: {'n_estimators': 106, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:10,669] Trial 79 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 136, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:10,902] Trial 80 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 122, 'max_depth': 30, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:11,121] Trial 81 finished with value: 0.8229064039408869 and parameters: {'n_estimators': 115, 'max_depth': 27, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:11,354] Trial 82 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 121, 'max_depth': 21, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:11,598] Trial 83 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 129, 'max_depth': 25, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:11,872] Trial 84 finished with value: 0.8148418878118544 and parameters: {'n_estimators': 149, 'max_depth': 23, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:12,131] Trial 85 finished with value: 0.8257202567547395 and parameters: {'n_estimators': 139, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:12,434] Trial 86 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 163, 'max_depth': 28, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:12,663] Trial 87 finished with value: 0.65860808395318 and parameters: {'n_estimators': 134, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:12,969] Trial 88 finished with value: 0.80623973727422 and parameters: {'n_estimators': 171, 'max_depth': 18, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:13,185] Trial 89 finished with value: 0.8195790416480072 and parameters: {'n_estimators': 101, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:13,461] Trial 90 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 147, 'max_depth': 25, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:13,697] Trial 91 finished with value: 0.8229064039408869 and parameters: {'n_estimators': 127, 'max_depth': 30, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:13,927] Trial 92 finished with value: 0.8229064039408869 and parameters: {'n_estimators': 114, 'max_depth': 30, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:14,164] Trial 93 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 124, 'max_depth': 22, 'min_samples_split': 3}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:14,425] Trial 94 finished with value: 0.8304821615166442 and parameters: {'n_estimators': 137, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 12 with value: 0.8304821615166442.
[I 2026-06-26 17:44:14,670] Trial 95 finished with value: 0.80623973727422 and parameters: {'n_estimators': 132, 'max_depth': 27, 'min_samples_split': 2}. Best is trial 12 with value: 0.8304821615166442.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
34,34,0.830482,2026-06-26 17:43:59.747382,2026-06-26 17:43:59.978559,0 days 00:00:00.231177,29,4,119,COMPLETE
23,23,0.830482,2026-06-26 17:43:56.773147,2026-06-26 17:43:57.026290,0 days 00:00:00.253143,24,3,134,COMPLETE
12,12,0.830482,2026-06-26 17:43:53.810370,2026-06-26 17:43:54.074505,0 days 00:00:00.264135,32,4,135,COMPLETE
18,18,0.830482,2026-06-26 17:43:55.294144,2026-06-26 17:43:55.572150,0 days 00:00:00.278006,23,4,149,COMPLETE
31,31,0.830482,2026-06-26 17:43:58.954612,2026-06-26 17:43:59.199526,0 days 00:00:00.244914,25,3,130,COMPLETE

In [101]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_f1_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_f1_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_f1_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for F1')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.98       190
           1       0.82      0.74      0.78        19

    accuracy                           0.96       209
   macro avg       0.90      0.86      0.88       209
weighted avg       0.96      0.96      0.96       209

In [102]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.6307345904869124

### Conclusions

In [103]:
pd.concat(classification_reports, keys=classification_report_keys)

                                                                 precision  \
Baseline Decision Tree Classifier                  0              0.973822
                                                   1              0.777778
                                                   accuracy       0.956938
                                                   macro avg      0.875800
                                                   weighted avg   0.956000
Decision Tree Classifier with Standard Scaling     0              0.973822
                                                   1              0.777778
                                                   accuracy       0.956938
                                                   macro avg      0.875800
                                                   weighted avg   0.956000
Baseline Random Forest Classifier                  0              0.973822
                                                   1              0.777778
                                                   accuracy       0.956938
                                                   macro avg      0.875800
                                                   weighted avg   0.956000
Random Forest Classifier with Standard Scaling     0              0.973822
                                                   1              0.777778
                                                   accuracy       0.956938
                                                   macro avg      0.875800
                                                   weighted avg   0.956000
Random Forest Classifier with Parameter Tuning ... 0              0.988235
                                                   1              0.435897
                                                   accuracy       0.885167
                                                   macro avg      0.712066
                                                   weighted avg   0.938023
Random Forest Classifier with Parameter Tuning ... 0              0.973958
                                                   1              0.823529
                                                   accuracy       0.961722
                                                   macro avg      0.898744
                                                   weighted avg   0.960283

                                                                   recall  \
Baseline Decision Tree Classifier                  0             0.978947
                                                   1             0.736842
                                                   accuracy      0.956938
                                                   macro avg     0.857895
                                                   weighted avg  0.956938
Decision Tree Classifier with Standard Scaling     0             0.978947
                                                   1             0.736842
                                                   accuracy      0.956938
                                                   macro avg     0.857895
                                                   weighted avg  0.956938
Baseline Random Forest Classifier                  0             0.978947
                                                   1             0.736842
                                                   accuracy      0.956938
                                                   macro avg     0.857895
                                                   weighted avg  0.956938
Random Forest Classifier with Standard Scaling     0             0.978947
                                                   1             0.736842
                                                   accuracy      0.956938
                                                   macro avg     0.857895
                                                   weighted avg  0.956938
Random Forest Classifier with Parameter Tuning ... 0             0.884211
                                                   1             0.894737
                                                   accuracy      0.885167
                                                   macro avg     0.889474
                                                   weighted avg  0.885167
Random Forest Classifier with Parameter Tuning ... 0             0.984211
                                                   1             0.736842
                                                   accuracy      0.961722
                                                   macro avg     0.860526
                                                   weighted avg  0.961722

                                                                 f1-score  \
Baseline Decision Tree Classifier                  0             0.976378
                                                   1             0.756757
                                                   accuracy      0.956938
                                                   macro avg     0.866567
                                                   weighted avg  0.956412
Decision Tree Classifier with Standard Scaling     0             0.976378
                                                   1             0.756757
                                                   accuracy      0.956938
                                                   macro avg     0.866567
                                                   weighted avg  0.956412
Baseline Random Forest Classifier                  0             0.976378
                                                   1             0.756757
                                                   accuracy      0.956938
                                                   macro avg     0.866567
                                                   weighted avg  0.956412
Random Forest Classifier with Standard Scaling     0             0.976378
                                                   1             0.756757
                                                   accuracy      0.956938
                                                   macro avg     0.866567
                                                   weighted avg  0.956412
Random Forest Classifier with Parameter Tuning ... 0             0.933333
                                                   1             0.586207
                                                   accuracy      0.885167
                                                   macro avg     0.759770
                                                   weighted avg  0.901776
Random Forest Classifier with Parameter Tuning ... 0             0.979058
                                                   1             0.777778
                                                   accuracy      0.961722
                                                   macro avg     0.878418
                                                   weighted avg  0.960759

                                                                    support
Baseline Decision Tree Classifier                  0             190.000000
                                                   1              19.000000
                                                   accuracy        0.956938
                                                   macro avg     209.000000
                                                   weighted avg  209.000000
Decision Tree Classifier with Standard Scaling     0             190.000000
                                                   1              19.000000
                                                   accuracy        0.956938
                                                   macro avg     209.000000
                                                   weighted avg  209.000000
Baseline Random Forest Classifier                  0             190.000000
                                                   1              19.000000
                                                   accuracy        0.956938
                                                   macro avg     209.000000
                                                   weighted avg  209.000000
Random Forest Classifier with Standard Scaling     0             190.000000
                                                   1              19.000000
                                                   accuracy        0.956938
                                                   macro avg     209.000000
                                                   weighted avg  209.000000
Random Forest Classifier with Parameter Tuning ... 0             190.000000
                                                   1              19.000000
                                                   accuracy        0.885167
                                                   macro avg     209.000000
                                                   weighted avg  209.000000
Random Forest Classifier with Parameter Tuning ... 0             190.000000
                                                   1              19.000000
                                                   accuracy        0.961722
                                                   macro avg     209.000000
                                                   weighted avg  209.000000