For Week 6, include concepts such as decision trees and random forests. Complete your Jupyter Notebook homework by 11:59pm ET on Sunday.

In [1]:
import pandas as pd
from imblearn.under_sampling import RandomUnderSampler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm 
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
import seaborn as sns
from sklearn.metrics import mean_absolute_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Credit Card

In [2]:
random_state = 42
classification_reports = []
classification_report_keys = []

### Import Data

In [3]:
# Import credit card datasaet
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/credit_card_cleaned.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

### Undersampling due to heavy class imbalance

In [4]:
from collections import Counter


X = df.drop(columns='Class')
y = df['Class']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(sampling_strategy=0.1, random_state=random_state)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 284315, 1: 492})
Resampled dataset shape: Counter({0: 4920, 1: 492})

### Split Data

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Decision Tree Classifier
#### (No feature scaling)

In [6]:
model = DecisionTreeClassifier(random_state=random_state)

In [7]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [8]:
y_pred = model.predict(X_test)

In [9]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Decision Tree Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       985
           1       0.82      0.88      0.85        98

    accuracy                           0.97      1083
   macro avg       0.90      0.93      0.92      1083
weighted avg       0.97      0.97      0.97      1083

### Feature Scaling + Decision Tree Classifier

In [10]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [11]:
model = DecisionTreeClassifier(random_state=random_state)

In [12]:
model.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [13]:
y_pred = model.predict(X_test_scaled)

In [14]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Decision Tree Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       985
           1       0.82      0.88      0.85        98

    accuracy                           0.97      1083
   macro avg       0.90      0.93      0.92      1083
weighted avg       0.97      0.97      0.97      1083

### Baseline Random Forest Classifier
#### (No feature scaling)

In [15]:
model = RandomForestClassifier(random_state=random_state)

In [16]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [17]:
y_pred = model.predict(X_test)

In [18]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Random Forest Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.87      0.92        98

    accuracy                           0.99      1083
   macro avg       0.99      0.93      0.96      1083
weighted avg       0.99      0.99      0.99      1083

### Feature Scaling + Decision Tree Classifier

In [19]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
model = RandomForestClassifier(random_state=random_state)

In [21]:
model.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

In [22]:
y_pred = model.predict(X_test_scaled)

In [23]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.87      0.92        98

    accuracy                           0.99      1083
   macro avg       0.99      0.93      0.96      1083
weighted avg       0.99      0.99      0.99      1083

### Parameter Tuning Random Forest (optimized for recall)

In [24]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [25]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_recall_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_recall_df)

[I 2026-06-24 20:20:27,249] A new study created in memory with name: no-name-4fdfbf83-605f-4235-90c2-2e9219738aab
[I 2026-06-24 20:20:29,023] Trial 0 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 93, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 0 with value: 0.8425186627718274.
[I 2026-06-24 20:20:30,770] Trial 1 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 107, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 1 with value: 0.8551768906199285.
[I 2026-06-24 20:20:32,395] Trial 2 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 88, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 1 with value: 0.8551768906199285.
[I 2026-06-24 20:20:34,186] Trial 3 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 77, 'max_depth': 17, 'min_samples_split': 8}. Best is trial 1 with value: 0.8551768906199285.
[I 2026-06-24 20:20:34,419] Trial 4 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 25, 'max_depth': 32, 'min_samples_split': 7}. Best is trial 1 with value: 0.8551768906199285.
[I 2026-06-24 20:20:35,456] Trial 5 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 166, 'max_depth': 6, 'min_samples_split': 10}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:35,608] Trial 6 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 50, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:35,979] Trial 7 finished with value: 0.8399870172022071 and parameters: {'n_estimators': 42, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:37,059] Trial 8 finished with value: 0.8450503083414475 and parameters: {'n_estimators': 123, 'max_depth': 21, 'min_samples_split': 5}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:37,211] Trial 9 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 44, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:38,734] Trial 10 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 187, 'max_depth': 10, 'min_samples_split': 10}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:39,545] Trial 11 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 148, 'max_depth': 5, 'min_samples_split': 6}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:40,756] Trial 12 finished with value: 0.850113599480688 and parameters: {'n_estimators': 167, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:41,451] Trial 13 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 146, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:42,643] Trial 14 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 146, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:43,396] Trial 15 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 194, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:44,723] Trial 16 finished with value: 0.8450503083414475 and parameters: {'n_estimators': 158, 'max_depth': 12, 'min_samples_split': 5}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:45,204] Trial 17 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 125, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:46,484] Trial 18 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 179, 'max_depth': 7, 'min_samples_split': 6}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:47,104] Trial 19 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 130, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:48,034] Trial 20 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 168, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:48,593] Trial 21 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 145, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:49,299] Trial 22 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 149, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:50,142] Trial 23 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 132, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:50,944] Trial 24 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 173, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:51,796] Trial 25 finished with value: 0.850113599480688 and parameters: {'n_estimators': 112, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:53,122] Trial 26 finished with value: 0.850113599480688 and parameters: {'n_estimators': 155, 'max_depth': 13, 'min_samples_split': 9}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:53,855] Trial 27 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 197, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:54,709] Trial 28 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 138, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:55,158] Trial 29 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 89, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:55,688] Trial 30 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 180, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:56,427] Trial 31 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 199, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:57,236] Trial 32 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 188, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:58,159] Trial 33 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 160, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:58,901] Trial 34 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 110, 'max_depth': 6, 'min_samples_split': 7}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:59,459] Trial 35 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 189, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 5 with value: 0.8577085361895488.
[I 2026-06-24 20:20:59,868] Trial 36 finished with value: 0.860240181759169 and parameters: {'n_estimators': 75, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:00,234] Trial 37 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 68, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:00,699] Trial 38 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 76, 'max_depth': 5, 'min_samples_split': 9}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:01,271] Trial 39 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 97, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:01,406] Trial 40 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 14, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:01,888] Trial 41 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 118, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:02,205] Trial 42 finished with value: 0.8501135994806882 and parameters: {'n_estimators': 58, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:02,622] Trial 43 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 139, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:03,728] Trial 44 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 165, 'max_depth': 6, 'min_samples_split': 6}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:05,257] Trial 45 finished with value: 0.850113599480688 and parameters: {'n_estimators': 176, 'max_depth': 31, 'min_samples_split': 9}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:05,853] Trial 46 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 154, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:06,416] Trial 47 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 99, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:07,910] Trial 48 finished with value: 0.850113599480688 and parameters: {'n_estimators': 184, 'max_depth': 10, 'min_samples_split': 6}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:08,158] Trial 49 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 81, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:09,058] Trial 50 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 193, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:09,576] Trial 51 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 132, 'max_depth': 3, 'min_samples_split': 8}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:10,056] Trial 52 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 124, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:10,727] Trial 53 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 142, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:11,422] Trial 54 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 121, 'max_depth': 5, 'min_samples_split': 9}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:11,696] Trial 55 finished with value: 0.850113599480688 and parameters: {'n_estimators': 35, 'max_depth': 7, 'min_samples_split': 6}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:12,141] Trial 56 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 151, 'max_depth': 2, 'min_samples_split': 10}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:12,965] Trial 57 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 170, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:13,606] Trial 58 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 162, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:14,422] Trial 59 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 127, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:14,941] Trial 60 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 135, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:15,869] Trial 61 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 167, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:16,685] Trial 62 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 148, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:17,917] Trial 63 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 173, 'max_depth': 7, 'min_samples_split': 7}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:18,764] Trial 64 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 181, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:19,983] Trial 65 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 158, 'max_depth': 8, 'min_samples_split': 9}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:20,487] Trial 66 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 103, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:21,222] Trial 67 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 113, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:21,765] Trial 68 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 141, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:22,494] Trial 69 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 155, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:22,886] Trial 70 finished with value: 0.8475819539110679 and parameters: {'n_estimators': 61, 'max_depth': 6, 'min_samples_split': 6}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:23,487] Trial 71 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 148, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:24,043] Trial 72 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 143, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:24,513] Trial 73 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 163, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:25,168] Trial 74 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 135, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:25,896] Trial 75 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 193, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:26,874] Trial 76 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 177, 'max_depth': 5, 'min_samples_split': 9}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:27,433] Trial 77 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 118, 'max_depth': 4, 'min_samples_split': 10}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:27,906] Trial 78 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 171, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:28,404] Trial 79 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 130, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:29,389] Trial 80 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 153, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:30,093] Trial 81 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 146, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:30,984] Trial 82 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 159, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:31,741] Trial 83 finished with value: 0.860240181759169 and parameters: {'n_estimators': 137, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:32,533] Trial 84 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 143, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:33,304] Trial 85 finished with value: 0.860240181759169 and parameters: {'n_estimators': 138, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:34,209] Trial 86 finished with value: 0.850113599480688 and parameters: {'n_estimators': 129, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:34,765] Trial 87 finished with value: 0.850113599480688 and parameters: {'n_estimators': 87, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:35,516] Trial 88 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 135, 'max_depth': 5, 'min_samples_split': 6}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:36,503] Trial 89 finished with value: 0.850113599480688 and parameters: {'n_estimators': 124, 'max_depth': 9, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:37,270] Trial 90 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 167, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:38,013] Trial 91 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 139, 'max_depth': 5, 'min_samples_split': 4}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:38,720] Trial 92 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 151, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:39,159] Trial 93 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 116, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:40,084] Trial 94 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 146, 'max_depth': 6, 'min_samples_split': 10}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:40,813] Trial 95 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 184, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 36 with value: 0.860240181759169.
[I 2026-06-24 20:21:41,484] Trial 96 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 135, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 36 with value: 0.860240181759169.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
83,83,0.860240,2026-06-24 20:21:30.984456,2026-06-24 20:21:31.741437,0 days 00:00:00.756981,5,3,137,COMPLETE
85,85,0.860240,2026-06-24 20:21:32.533932,2026-06-24 20:21:33.304702,0 days 00:00:00.770770,5,3,138,COMPLETE
36,36,0.860240,2026-06-24 20:20:59.459991,2026-06-24 20:20:59.868930,0 days 00:00:00.408939,4,10,75,COMPLETE
13,13,0.857709,2026-06-24 20:20:40.757951,2026-06-24 20:20:41.451368,0 days 00:00:00.693417,4,3,146,COMPLETE
29,29,0.857709,2026-06-24 20:20:54.709229,2026-06-24 20:20:55.158352,0 days 00:00:00.449123,4,2,89,COMPLETE

In [26]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_recall_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_recall_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_recall_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for Recall')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.96      0.88      0.91        98

    accuracy                           0.99      1083
   macro avg       0.97      0.94      0.95      1083
weighted avg       0.98      0.99      0.98      1083

### Parameter Tuning Random Forest (Optimized for F1)

In [27]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_f1_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_f1_df)

[I 2026-06-24 20:21:45,123] A new study created in memory with name: no-name-5752acd6-e52b-4870-911c-8aabe5ebbb7d
[I 2026-06-24 20:21:46,147] Trial 0 finished with value: 0.9130621137938089 and parameters: {'n_estimators': 161, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:46,448] Trial 1 finished with value: 0.906336084128674 and parameters: {'n_estimators': 49, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:46,990] Trial 2 finished with value: 0.9081654643230997 and parameters: {'n_estimators': 63, 'max_depth': 18, 'min_samples_split': 8}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:47,506] Trial 3 finished with value: 0.8993688225058053 and parameters: {'n_estimators': 177, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:47,677] Trial 4 finished with value: 0.8850890907445932 and parameters: {'n_estimators': 53, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:47,771] Trial 5 finished with value: 0.9066660401345998 and parameters: {'n_estimators': 13, 'max_depth': 5, 'min_samples_split': 8}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:49,121] Trial 6 finished with value: 0.9099705079647047 and parameters: {'n_estimators': 160, 'max_depth': 30, 'min_samples_split': 9}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:49,741] Trial 7 finished with value: 0.9030261528000544 and parameters: {'n_estimators': 132, 'max_depth': 4, 'min_samples_split': 9}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:49,990] Trial 8 finished with value: 0.9090733544724353 and parameters: {'n_estimators': 42, 'max_depth': 5, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:50,517] Trial 9 finished with value: 0.9081654643230997 and parameters: {'n_estimators': 59, 'max_depth': 17, 'min_samples_split': 8}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:52,188] Trial 10 finished with value: 0.9079458909738557 and parameters: {'n_estimators': 197, 'max_depth': 11, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:53,426] Trial 11 finished with value: 0.9096959319659905 and parameters: {'n_estimators': 146, 'max_depth': 11, 'min_samples_split': 5}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:54,378] Trial 12 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 110, 'max_depth': 27, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:55,727] Trial 13 finished with value: 0.9080930260656288 and parameters: {'n_estimators': 160, 'max_depth': 32, 'min_samples_split': 6}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:56,556] Trial 14 finished with value: 0.9095782678551085 and parameters: {'n_estimators': 108, 'max_depth': 8, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:57,278] Trial 15 finished with value: 0.902108172006025 and parameters: {'n_estimators': 193, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:58,520] Trial 16 finished with value: 0.908896825010227 and parameters: {'n_estimators': 166, 'max_depth': 8, 'min_samples_split': 10}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:21:59,684] Trial 17 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 135, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:00,448] Trial 18 finished with value: 0.9069015468809317 and parameters: {'n_estimators': 90, 'max_depth': 12, 'min_samples_split': 7}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:00,935] Trial 19 finished with value: 0.9044703945363148 and parameters: {'n_estimators': 123, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:02,449] Trial 20 finished with value: 0.9107549047077995 and parameters: {'n_estimators': 180, 'max_depth': 24, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:03,996] Trial 21 finished with value: 0.9107549047077995 and parameters: {'n_estimators': 180, 'max_depth': 26, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:05,484] Trial 22 finished with value: 0.9107549047077995 and parameters: {'n_estimators': 176, 'max_depth': 22, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:07,030] Trial 23 finished with value: 0.9092031805698685 and parameters: {'n_estimators': 183, 'max_depth': 14, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:08,264] Trial 24 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 149, 'max_depth': 23, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:09,678] Trial 25 finished with value: 0.9113568571746926 and parameters: {'n_estimators': 198, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:11,061] Trial 26 finished with value: 0.9113568571746926 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:12,459] Trial 27 finished with value: 0.9113568571746926 and parameters: {'n_estimators': 198, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:14,067] Trial 28 finished with value: 0.9073038412980379 and parameters: {'n_estimators': 199, 'max_depth': 9, 'min_samples_split': 5}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:14,641] Trial 29 finished with value: 0.9078217673148078 and parameters: {'n_estimators': 89, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:15,453] Trial 30 finished with value: 0.904388656068598 and parameters: {'n_estimators': 169, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:16,692] Trial 31 finished with value: 0.9103647293763354 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:17,988] Trial 32 finished with value: 0.9101691177110911 and parameters: {'n_estimators': 188, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:18,970] Trial 33 finished with value: 0.9076801656179461 and parameters: {'n_estimators': 155, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:19,766] Trial 34 finished with value: 0.904388656068598 and parameters: {'n_estimators': 171, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:21,290] Trial 35 finished with value: 0.9096363657281739 and parameters: {'n_estimators': 187, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:22,361] Trial 36 finished with value: 0.9080820655926247 and parameters: {'n_estimators': 189, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:22,944] Trial 37 finished with value: 0.9044703945363148 and parameters: {'n_estimators': 141, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:24,118] Trial 38 finished with value: 0.9087166448300469 and parameters: {'n_estimators': 159, 'max_depth': 7, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:24,287] Trial 39 finished with value: 0.9008301215699606 and parameters: {'n_estimators': 28, 'max_depth': 4, 'min_samples_split': 7}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:25,680] Trial 40 finished with value: 0.906693094553274 and parameters: {'n_estimators': 170, 'max_depth': 9, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:26,197] Trial 41 finished with value: 0.8993688225058053 and parameters: {'n_estimators': 180, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:27,912] Trial 42 finished with value: 0.9079836802983715 and parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:28,975] Trial 43 finished with value: 0.9105063310731971 and parameters: {'n_estimators': 188, 'max_depth': 5, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:30,417] Trial 44 finished with value: 0.9064532126554805 and parameters: {'n_estimators': 175, 'max_depth': 10, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:32,091] Trial 45 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 192, 'max_depth': 14, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:33,163] Trial 46 finished with value: 0.9091131422187079 and parameters: {'n_estimators': 163, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:33,763] Trial 47 finished with value: 0.9081838928471295 and parameters: {'n_estimators': 72, 'max_depth': 8, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:34,125] Trial 48 finished with value: 0.9017280310293974 and parameters: {'n_estimators': 122, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:35,157] Trial 49 finished with value: 0.910709957505949 and parameters: {'n_estimators': 179, 'max_depth': 5, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:36,477] Trial 50 finished with value: 0.9096959319659905 and parameters: {'n_estimators': 151, 'max_depth': 11, 'min_samples_split': 5}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:38,043] Trial 51 finished with value: 0.9107549047077995 and parameters: {'n_estimators': 181, 'max_depth': 22, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:39,682] Trial 52 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 193, 'max_depth': 26, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:41,342] Trial 53 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 192, 'max_depth': 28, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:43,047] Trial 54 finished with value: 0.9079836802983715 and parameters: {'n_estimators': 196, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:44,710] Trial 55 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 192, 'max_depth': 16, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:46,343] Trial 56 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 183, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:47,639] Trial 57 finished with value: 0.9096363657281739 and parameters: {'n_estimators': 175, 'max_depth': 7, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:49,029] Trial 58 finished with value: 0.9082720074123956 and parameters: {'n_estimators': 164, 'max_depth': 32, 'min_samples_split': 5}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:50,722] Trial 59 finished with value: 0.9096858776584804 and parameters: {'n_estimators': 199, 'max_depth': 12, 'min_samples_split': 6}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:51,813] Trial 60 finished with value: 0.9069611131187486 and parameters: {'n_estimators': 142, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:53,423] Trial 61 finished with value: 0.9107549047077995 and parameters: {'n_estimators': 184, 'max_depth': 27, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:54,915] Trial 62 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 172, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:56,563] Trial 63 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 193, 'max_depth': 20, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:58,113] Trial 64 finished with value: 0.9107549047077995 and parameters: {'n_estimators': 184, 'max_depth': 25, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:22:59,518] Trial 65 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 157, 'max_depth': 30, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:00,781] Trial 66 finished with value: 0.9103647293763354 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:02,356] Trial 67 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 176, 'max_depth': 20, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:03,004] Trial 68 finished with value: 0.902108172006025 and parameters: {'n_estimators': 168, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:04,675] Trial 69 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 194, 'max_depth': 25, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:05,985] Trial 70 finished with value: 0.9101691177110911 and parameters: {'n_estimators': 187, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:07,504] Trial 71 finished with value: 0.9107549047077995 and parameters: {'n_estimators': 176, 'max_depth': 22, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:09,107] Trial 72 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 188, 'max_depth': 27, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:10,541] Trial 73 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 167, 'max_depth': 22, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:11,399] Trial 74 finished with value: 0.9066132197669077 and parameters: {'n_estimators': 99, 'max_depth': 16, 'min_samples_split': 3}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:12,934] Trial 75 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 178, 'max_depth': 30, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:14,499] Trial 76 finished with value: 0.9096858776584804 and parameters: {'n_estimators': 182, 'max_depth': 29, 'min_samples_split': 5}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:16,157] Trial 77 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 195, 'max_depth': 31, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:17,399] Trial 78 finished with value: 0.9081654643230997 and parameters: {'n_estimators': 152, 'max_depth': 10, 'min_samples_split': 4}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:18,399] Trial 79 finished with value: 0.9079416731587173 and parameters: {'n_estimators': 162, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:19,403] Trial 80 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 188, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:20,483] Trial 81 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 188, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:21,514] Trial 82 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 188, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:22,398] Trial 83 finished with value: 0.9031821206685142 and parameters: {'n_estimators': 190, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:23,293] Trial 84 finished with value: 0.9031821206685142 and parameters: {'n_estimators': 195, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:24,307] Trial 85 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 186, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:25,341] Trial 86 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 186, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:26,389] Trial 87 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 186, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:27,365] Trial 88 finished with value: 0.9103008816823095 and parameters: {'n_estimators': 172, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:28,408] Trial 89 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 187, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:29,438] Trial 90 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 185, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:30,530] Trial 91 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 187, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:31,551] Trial 92 finished with value: 0.9116940705367986 and parameters: {'n_estimators': 185, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:32,440] Trial 93 finished with value: 0.9031821206685142 and parameters: {'n_estimators': 186, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:33,409] Trial 94 finished with value: 0.9103008816823095 and parameters: {'n_estimators': 173, 'max_depth': 5, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:34,608] Trial 95 finished with value: 0.9115524688399368 and parameters: {'n_estimators': 179, 'max_depth': 6, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.
[I 2026-06-24 20:23:35,463] Trial 96 finished with value: 0.9031821206685142 and parameters: {'n_estimators': 182, 'max_depth': 4, 'min_samples_split': 2}. Best is trial 0 with value: 0.9130621137938089.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
0,0,0.913062,2026-06-24 20:21:45.123957,2026-06-24 20:21:46.147466,0 days 00:00:01.023509,6,2,161,COMPLETE
87,87,0.911694,2026-06-24 20:23:25.341789,2026-06-24 20:23:26.389737,0 days 00:00:01.047948,5,2,186,COMPLETE
86,86,0.911694,2026-06-24 20:23:24.307778,2026-06-24 20:23:25.341789,0 days 00:00:01.034011,5,2,186,COMPLETE
85,85,0.911694,2026-06-24 20:23:23.293361,2026-06-24 20:23:24.307778,0 days 00:00:01.014417,5,2,186,COMPLETE
90,90,0.911694,2026-06-24 20:23:28.408061,2026-06-24 20:23:29.438792,0 days 00:00:01.030731,5,2,185,COMPLETE

In [28]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_f1_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_f1_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_f1_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for F1')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.96      0.87      0.91        98

    accuracy                           0.98      1083
   macro avg       0.97      0.93      0.95      1083
weighted avg       0.98      0.98      0.98      1083

### Conclusions

In [29]:
pd.concat(classification_reports, keys=classification_report_keys)

                                                                 precision  \
Baseline Decision Tree Classifier                  0              0.987730
                                                   1              0.819048
                                                   accuracy       0.971376
                                                   macro avg      0.903389
                                                   weighted avg   0.972466
Decision Tree Classifier with Standard Scaling     0              0.987730
                                                   1              0.819048
                                                   accuracy       0.971376
                                                   macro avg      0.903389
                                                   weighted avg   0.972466
Baseline Random Forest Classifier                  0              0.986961
                                                   1              0.988372
                                                   accuracy       0.987073
                                                   macro avg      0.987666
                                                   weighted avg   0.987089
Random Forest Classifier with Standard Scaling     0              0.986961
                                                   1              0.988372
                                                   accuracy       0.987073
                                                   macro avg      0.987666
                                                   weighted avg   0.987089
Random Forest Classifier with Parameter Tuning ... 0              0.987915
                                                   1              0.955556
                                                   accuracy       0.985226
                                                   macro avg      0.971735
                                                   weighted avg   0.984987
Random Forest Classifier with Parameter Tuning ... 0              0.986922
                                                   1              0.955056
                                                   accuracy       0.984303
                                                   macro avg      0.970989
                                                   weighted avg   0.984038

                                                                   recall  \
Baseline Decision Tree Classifier                  0             0.980711
                                                   1             0.877551
                                                   accuracy      0.971376
                                                   macro avg     0.929131
                                                   weighted avg  0.971376
Decision Tree Classifier with Standard Scaling     0             0.980711
                                                   1             0.877551
                                                   accuracy      0.971376
                                                   macro avg     0.929131
                                                   weighted avg  0.971376
Baseline Random Forest Classifier                  0             0.998985
                                                   1             0.867347
                                                   accuracy      0.987073
                                                   macro avg     0.933166
                                                   weighted avg  0.987073
Random Forest Classifier with Standard Scaling     0             0.998985
                                                   1             0.867347
                                                   accuracy      0.987073
                                                   macro avg     0.933166
                                                   weighted avg  0.987073
Random Forest Classifier with Parameter Tuning ... 0             0.995939
                                                   1             0.877551
                                                   accuracy      0.985226
                                                   macro avg     0.936745
                                                   weighted avg  0.985226
Random Forest Classifier with Parameter Tuning ... 0             0.995939
                                                   1             0.867347
                                                   accuracy      0.984303
                                                   macro avg     0.931643
                                                   weighted avg  0.984303

                                                                 f1-score  \
Baseline Decision Tree Classifier                  0             0.984208
                                                   1             0.847291
                                                   accuracy      0.971376
                                                   macro avg     0.915749
                                                   weighted avg  0.971818
Decision Tree Classifier with Standard Scaling     0             0.984208
                                                   1             0.847291
                                                   accuracy      0.971376
                                                   macro avg     0.915749
                                                   weighted avg  0.971818
Baseline Random Forest Classifier                  0             0.992936
                                                   1             0.923913
                                                   accuracy      0.987073
                                                   macro avg     0.958425
                                                   weighted avg  0.986691
Random Forest Classifier with Standard Scaling     0             0.992936
                                                   1             0.923913
                                                   accuracy      0.987073
                                                   macro avg     0.958425
                                                   weighted avg  0.986691
Random Forest Classifier with Parameter Tuning ... 0             0.991911
                                                   1             0.914894
                                                   accuracy      0.985226
                                                   macro avg     0.953402
                                                   weighted avg  0.984942
Random Forest Classifier with Parameter Tuning ... 0             0.991410
                                                   1             0.909091
                                                   accuracy      0.984303
                                                   macro avg     0.950250
                                                   weighted avg  0.983961

                                                                     support
Baseline Decision Tree Classifier                  0              985.000000
                                                   1               98.000000
                                                   accuracy         0.971376
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Decision Tree Classifier with Standard Scaling     0              985.000000
                                                   1               98.000000
                                                   accuracy         0.971376
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Baseline Random Forest Classifier                  0              985.000000
                                                   1               98.000000
                                                   accuracy         0.987073
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Standard Scaling     0              985.000000
                                                   1               98.000000
                                                   accuracy         0.987073
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Parameter Tuning ... 0              985.000000
                                                   1               98.000000
                                                   accuracy         0.985226
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Parameter Tuning ... 0              985.000000
                                                   1               98.000000
                                                   accuracy         0.984303
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000

We can see the scaling does not affect the results since these are tree based methods. The Random Forest model is the better out of the two variants. The base random forest achieves 0.933166 macro avg recall and 0.958425 macro avg f1

The recall optimized model sees a lift on macro avg recall to 0.938801, with less recall on negative and higher on positive class. 

The f1 optimized model sees 0.955234 macro avg f1, slightly less than the baseline model

## IBM

In [30]:
random_state = 42
classification_reports = []
classification_report_keys = []

### Import Data

In [31]:
# Import credit card datasaet
df = pd.read_csv('ibm_hi_small_trans_cleaned_semester3')
df

FileNotFoundError: [Errno 2] No such file or directory: 'ibm_hi_small_trans_cleaned_semester3'

### Undersampling due to heavy class imbalance

In [ ]:
from collections import Counter


X = df.drop(columns='Is Laundering')
y = df['Is Laundering']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(sampling_strategy=0.1, random_state=random_state)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 284315, 1: 492})
Resampled dataset shape: Counter({0: 4920, 1: 492})

### Split Data

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Decision Tree Classifier
#### (No feature scaling)

In [ ]:
model = DecisionTreeClassifier(random_state=random_state)

In [ ]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Decision Tree Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       985
           1       0.82      0.88      0.85        98

    accuracy                           0.97      1083
   macro avg       0.90      0.93      0.92      1083
weighted avg       0.97      0.97      0.97      1083

### Feature Scaling + Decision Tree Classifier

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
model = DecisionTreeClassifier(random_state=random_state)

In [ ]:
model.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test_scaled)

In [ ]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Decision Tree Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       985
           1       0.82      0.88      0.85        98

    accuracy                           0.97      1083
   macro avg       0.90      0.93      0.92      1083
weighted avg       0.97      0.97      0.97      1083

### Baseline Random Forest Classifier
#### (No feature scaling)

In [ ]:
model = RandomForestClassifier(random_state=random_state)

In [ ]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Random Forest Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.87      0.92        98

    accuracy                           0.99      1083
   macro avg       0.99      0.93      0.96      1083
weighted avg       0.99      0.99      0.99      1083

### Feature Scaling + Decision Tree Classifier

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
model = RandomForestClassifier(random_state=random_state)

In [ ]:
model.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test_scaled)

In [ ]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.87      0.92        98

    accuracy                           0.99      1083
   macro avg       0.99      0.93      0.96      1083
weighted avg       0.99      0.99      0.99      1083

### Parameter Tuning Random Forest (optimized for recall)

In [ ]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [ ]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_recall_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_recall_df)

[I 2026-06-23 17:41:33,956] A new study created in memory with name: no-name-61e32d59-1f41-4ac7-b3ed-936a6daf8fc9
[I 2026-06-23 17:41:36,044] Trial 0 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 97, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:38,247] Trial 1 finished with value: 0.850113599480688 and parameters: {'n_estimators': 120, 'max_depth': 19, 'min_samples_split': 9}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:40,577] Trial 2 finished with value: 0.850113599480688 and parameters: {'n_estimators': 162, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:42,954] Trial 3 finished with value: 0.850113599480688 and parameters: {'n_estimators': 143, 'max_depth': 29, 'min_samples_split': 8}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:43,913] Trial 4 finished with value: 0.850113599480688 and parameters: {'n_estimators': 110, 'max_depth': 20, 'min_samples_split': 10}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:43,991] Trial 5 finished with value: 0.8450503083414477 and parameters: {'n_estimators': 14, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:45,549] Trial 6 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 180, 'max_depth': 14, 'min_samples_split': 7}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:45,876] Trial 7 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 112, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:45,970] Trial 8 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 18, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:46,080] Trial 9 finished with value: 0.822233041220383 and parameters: {'n_estimators': 10, 'max_depth': 17, 'min_samples_split': 3}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:46,424] Trial 10 finished with value: 0.860240181759169 and parameters: {'n_estimators': 66, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:46,704] Trial 11 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 54, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:47,022] Trial 12 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 58, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:47,478] Trial 13 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 55, 'max_depth': 8, 'min_samples_split': 4}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:47,793] Trial 14 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 77, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:47,934] Trial 15 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 31, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:48,058] Trial 16 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 36, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:48,340] Trial 17 finished with value: 0.8450503083414475 and parameters: {'n_estimators': 30, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:48,698] Trial 18 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 84, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:48,927] Trial 19 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 9}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:49,098] Trial 20 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 38, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:49,256] Trial 21 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 35, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:49,367] Trial 22 finished with value: 0.850113599480688 and parameters: {'n_estimators': 28, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:49,647] Trial 23 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 46, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:49,743] Trial 24 finished with value: 0.8577409931840311 and parameters: {'n_estimators': 17, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:49,978] Trial 25 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 74, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:50,524] Trial 26 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 93, 'max_depth': 5, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:50,729] Trial 27 finished with value: 0.8374553716325869 and parameters: {'n_estimators': 22, 'max_depth': 10, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:50,948] Trial 28 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 52, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:51,216] Trial 29 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 42, 'max_depth': 5, 'min_samples_split': 9}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:51,606] Trial 30 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 129, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:51,810] Trial 31 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 47, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:51,888] Trial 32 finished with value: 0.8501135994806882 and parameters: {'n_estimators': 10, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:52,188] Trial 33 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 66, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:52,298] Trial 34 finished with value: 0.8552093476144108 and parameters: {'n_estimators': 25, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:52,920] Trial 35 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 95, 'max_depth': 6, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:53,121] Trial 36 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 46, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:53,214] Trial 37 finished with value: 0.8552093476144108 and parameters: {'n_estimators': 23, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:54,166] Trial 38 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 195, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:54,730] Trial 39 finished with value: 0.850113599480688 and parameters: {'n_estimators': 65, 'max_depth': 12, 'min_samples_split': 8}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:55,652] Trial 40 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 138, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:55,838] Trial 41 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 40, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:55,995] Trial 42 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 37, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:56,105] Trial 43 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 18, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:56,619] Trial 44 finished with value: 0.8349237260629666 and parameters: {'n_estimators': 54, 'max_depth': 26, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:57,089] Trial 45 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 160, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:57,246] Trial 46 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 31, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:57,444] Trial 47 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 60, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:57,631] Trial 48 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 34, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:57,850] Trial 49 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 50, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:58,307] Trial 50 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 77, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:58,400] Trial 51 finished with value: 0.8577409931840311 and parameters: {'n_estimators': 15, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:58,542] Trial 52 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:58,684] Trial 53 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 29, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:58,901] Trial 54 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 39, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:59,009] Trial 55 finished with value: 0.850113599480688 and parameters: {'n_estimators': 28, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:59,446] Trial 56 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 107, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:59,540] Trial 57 finished with value: 0.8552093476144108 and parameters: {'n_estimators': 21, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:59,837] Trial 58 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 57, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:59,993] Trial 59 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 35, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,227] Trial 60 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 73, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,368] Trial 61 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 29, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,556] Trial 62 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 42, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,633] Trial 63 finished with value: 0.8577734501785134 and parameters: {'n_estimators': 11, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,786] Trial 64 finished with value: 0.860240181759169 and parameters: {'n_estimators': 27, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,956] Trial 65 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 51, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:01,174] Trial 66 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 34, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:01,376] Trial 67 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 45, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:01,532] Trial 68 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 18, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:01,735] Trial 69 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 62, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:02,189] Trial 70 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 115, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:02,330] Trial 71 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 30, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:02,470] Trial 72 finished with value: 0.8678675754625121 and parameters: {'n_estimators': 26, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:02,626] Trial 73 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 25, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:02,768] Trial 74 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 31, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:02,910] Trial 75 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 30, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,016] Trial 76 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 16, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,112] Trial 77 finished with value: 0.8552093476144108 and parameters: {'n_estimators': 23, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,252] Trial 78 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 31, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,426] Trial 79 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 41, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,568] Trial 80 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 20, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,708] Trial 81 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 30, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,786] Trial 82 finished with value: 0.8628367413177539 and parameters: {'n_estimators': 13, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,910] Trial 83 finished with value: 0.8678675754625121 and parameters: {'n_estimators': 26, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,081] Trial 84 finished with value: 0.860240181759169 and parameters: {'n_estimators': 27, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,206] Trial 85 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 36, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,409] Trial 86 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 45, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,518] Trial 87 finished with value: 0.8197013956507627 and parameters: {'n_estimators': 10, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,627] Trial 88 finished with value: 0.8577409931840311 and parameters: {'n_estimators': 23, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,908] Trial 89 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 88, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,173] Trial 90 finished with value: 0.860240181759169 and parameters: {'n_estimators': 49, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,330] Trial 91 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 33, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,471] Trial 92 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 30, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,641] Trial 93 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 40, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,750] Trial 94 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 21, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,924] Trial 95 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 27, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:06,096] Trial 96 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 38, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
72,72,0.867868,2026-06-23 17:42:02.330374,2026-06-23 17:42:02.470593,0 days 00:00:00.140219,3,5,26,COMPLETE
83,83,0.867868,2026-06-23 17:42:03.786319,2026-06-23 17:42:03.910870,0 days 00:00:00.124551,3,5,26,COMPLETE
21,21,0.865336,2026-06-23 17:41:49.098421,2026-06-23 17:41:49.256988,0 days 00:00:00.158567,3,5,35,COMPLETE
53,53,0.865336,2026-06-23 17:41:58.542672,2026-06-23 17:41:58.684352,0 days 00:00:00.141680,3,3,29,COMPLETE
78,78,0.865336,2026-06-23 17:42:03.112271,2026-06-23 17:42:03.252197,0 days 00:00:00.139926,3,5,31,COMPLETE

In [ ]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_recall_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_recall_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_recall_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for Recall')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       985
           1       0.90      0.89      0.89        98

    accuracy                           0.98      1083
   macro avg       0.94      0.94      0.94      1083
weighted avg       0.98      0.98      0.98      1083

### Parameter Tuning Random Forest (Optimized for F1)

In [ ]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_f1_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_f1_df)

[I 2026-06-23 17:42:06,586] A new study created in memory with name: no-name-6ba02d91-df2b-47a8-a2d1-b2640eeea4cd
[I 2026-06-23 17:42:06,694] Trial 0 finished with value: 0.8807512071696536 and parameters: {'n_estimators': 26, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 0 with value: 0.8807512071696536.
[I 2026-06-23 17:42:07,197] Trial 1 finished with value: 0.9044703945363148 and parameters: {'n_estimators': 130, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 1 with value: 0.9044703945363148.
[I 2026-06-23 17:42:07,338] Trial 2 finished with value: 0.8826923363743286 and parameters: {'n_estimators': 45, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9044703945363148.
[I 2026-06-23 17:42:08,404] Trial 3 finished with value: 0.9091131422187079 and parameters: {'n_estimators': 168, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 3 with value: 0.9091131422187079.
[I 2026-06-23 17:42:09,551] Trial 4 finished with value: 0.9069214437697131 and parameters: {'n_estimators': 150, 'max_depth': 8, 'min_samples_split': 8}. Best is trial 3 with value: 0.9091131422187079.
[I 2026-06-23 17:42:11,167] Trial 5 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 186, 'max_depth': 24, 'min_samples_split': 3}. Best is trial 5 with value: 0.9093597612199407.
[I 2026-06-23 17:42:11,539] Trial 6 finished with value: 0.9074562633945487 and parameters: {'n_estimators': 41, 'max_depth': 32, 'min_samples_split': 9}. Best is trial 5 with value: 0.9093597612199407.
[I 2026-06-23 17:42:11,836] Trial 7 finished with value: 0.9080407782170934 and parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 5}. Best is trial 5 with value: 0.9093597612199407.
[I 2026-06-23 17:42:12,384] Trial 8 finished with value: 0.8995063197303192 and parameters: {'n_estimators': 115, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 5 with value: 0.9093597612199407.
[I 2026-06-23 17:42:13,399] Trial 9 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 119, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:14,121] Trial 10 finished with value: 0.9036870062732131 and parameters: {'n_estimators': 81, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:15,816] Trial 11 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 195, 'max_depth': 32, 'min_samples_split': 2}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:16,553] Trial 12 finished with value: 0.911022923273274 and parameters: {'n_estimators': 86, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:17,232] Trial 13 finished with value: 0.9097208947093322 and parameters: {'n_estimators': 81, 'max_depth': 14, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:17,926] Trial 14 finished with value: 0.9095805438321392 and parameters: {'n_estimators': 85, 'max_depth': 19, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:18,740] Trial 15 finished with value: 0.9096959319659905 and parameters: {'n_estimators': 107, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:19,290] Trial 16 finished with value: 0.901235827664399 and parameters: {'n_estimators': 61, 'max_depth': 12, 'min_samples_split': 6}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:20,489] Trial 17 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 138, 'max_depth': 21, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:21,287] Trial 18 finished with value: 0.9108445069670784 and parameters: {'n_estimators': 137, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:22,711] Trial 19 finished with value: 0.9087166448300469 and parameters: {'n_estimators': 161, 'max_depth': 25, 'min_samples_split': 10}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:23,776] Trial 20 finished with value: 0.9068221925128264 and parameters: {'n_estimators': 127, 'max_depth': 11, 'min_samples_split': 6}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:24,546] Trial 21 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 92, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:25,346] Trial 22 finished with value: 0.9096858776584804 and parameters: {'n_estimators': 97, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:26,522] Trial 23 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 145, 'max_depth': 25, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:27,510] Trial 24 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 118, 'max_depth': 13, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:28,007] Trial 25 finished with value: 0.9054490739998874 and parameters: {'n_estimators': 62, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:28,820] Trial 26 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 98, 'max_depth': 22, 'min_samples_split': 2}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:30,293] Trial 27 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 175, 'max_depth': 15, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:31,517] Trial 28 finished with value: 0.9082720074123956 and parameters: {'n_estimators': 148, 'max_depth': 27, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:32,081] Trial 29 finished with value: 0.9036883771160378 and parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:32,997] Trial 30 finished with value: 0.9084519114126041 and parameters: {'n_estimators': 112, 'max_depth': 10, 'min_samples_split': 7}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:33,124] Trial 31 finished with value: 0.9065312074173273 and parameters: {'n_estimators': 13, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:33,894] Trial 32 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 91, 'max_depth': 22, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:34,930] Trial 33 finished with value: 0.9097443771822211 and parameters: {'n_estimators': 126, 'max_depth': 29, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:35,282] Trial 34 finished with value: 0.9055750871970781 and parameters: {'n_estimators': 96, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:35,658] Trial 35 finished with value: 0.8993688225058053 and parameters: {'n_estimators': 135, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:36,258] Trial 36 finished with value: 0.9069214437697131 and parameters: {'n_estimators': 71, 'max_depth': 22, 'min_samples_split': 7}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:37,246] Trial 37 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 119, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:38,222] Trial 38 finished with value: 0.9079416731587173 and parameters: {'n_estimators': 160, 'max_depth': 6, 'min_samples_split': 8}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:38,634] Trial 39 finished with value: 0.9080238857357024 and parameters: {'n_estimators': 48, 'max_depth': 23, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:39,495] Trial 40 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 104, 'max_depth': 28, 'min_samples_split': 2}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:40,471] Trial 41 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 118, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:41,514] Trial 42 finished with value: 0.9078080370820096 and parameters: {'n_estimators': 126, 'max_depth': 14, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:42,641] Trial 43 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 137, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:43,545] Trial 44 finished with value: 0.9097443771822211 and parameters: {'n_estimators': 109, 'max_depth': 21, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:44,321] Trial 45 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 93, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:44,945] Trial 46 finished with value: 0.9109756873199977 and parameters: {'n_estimators': 75, 'max_depth': 18, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:45,921] Trial 47 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 120, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:46,655] Trial 48 finished with value: 0.9036870062732131 and parameters: {'n_estimators': 89, 'max_depth': 25, 'min_samples_split': 2}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:47,497] Trial 49 finished with value: 0.9109487283865724 and parameters: {'n_estimators': 103, 'max_depth': 15, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:48,795] Trial 50 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 158, 'max_depth': 21, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:49,770] Trial 51 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 119, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:50,898] Trial 52 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 133, 'max_depth': 13, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:51,850] Trial 53 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 113, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:52,711] Trial 54 finished with value: 0.9109487283865724 and parameters: {'n_estimators': 103, 'max_depth': 20, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:53,862] Trial 55 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 139, 'max_depth': 27, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:54,475] Trial 56 finished with value: 0.9085500169854892 and parameters: {'n_estimators': 79, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:55,493] Trial 57 finished with value: 0.9080930260656288 and parameters: {'n_estimators': 123, 'max_depth': 24, 'min_samples_split': 6}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:56,457] Trial 58 finished with value: 0.9075451757700563 and parameters: {'n_estimators': 145, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:57,172] Trial 59 finished with value: 0.9093796581087222 and parameters: {'n_estimators': 88, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:58,208] Trial 60 finished with value: 0.9063555642009653 and parameters: {'n_estimators': 130, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:59,185] Trial 61 finished with value: 0.9109487283865724 and parameters: {'n_estimators': 120, 'max_depth': 15, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:00,149] Trial 62 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 113, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:01,386] Trial 63 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 152, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:02,295] Trial 64 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 108, 'max_depth': 18, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:03,647] Trial 65 finished with value: 0.9087166448300469 and parameters: {'n_estimators': 170, 'max_depth': 20, 'min_samples_split': 10}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:04,623] Trial 66 finished with value: 0.9066132197669077 and parameters: {'n_estimators': 117, 'max_depth': 29, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:05,435] Trial 67 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 98, 'max_depth': 23, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:06,599] Trial 68 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 142, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:07,678] Trial 69 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 131, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:08,909] Trial 70 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 153, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:09,606] Trial 71 finished with value: 0.9125533909161649 and parameters: {'n_estimators': 82, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:10,152] Trial 72 finished with value: 0.9081554100155895 and parameters: {'n_estimators': 66, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:10,606] Trial 73 finished with value: 0.9079458909738557 and parameters: {'n_estimators': 54, 'max_depth': 26, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:11,370] Trial 74 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 93, 'max_depth': 21, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:12,073] Trial 75 finished with value: 0.9037479433538547 and parameters: {'n_estimators': 82, 'max_depth': 23, 'min_samples_split': 3}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:12,661] Trial 76 finished with value: 0.9081294282870637 and parameters: {'n_estimators': 70, 'max_depth': 18, 'min_samples_split': 5}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:13,110] Trial 77 finished with value: 0.9021307312154049 and parameters: {'n_estimators': 99, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:14,001] Trial 78 finished with value: 0.9097443771822211 and parameters: {'n_estimators': 109, 'max_depth': 30, 'min_samples_split': 5}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:14,983] Trial 79 finished with value: 0.9094182607436814 and parameters: {'n_estimators': 123, 'max_depth': 10, 'min_samples_split': 3}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:15,620] Trial 80 finished with value: 0.905200416234899 and parameters: {'n_estimators': 76, 'max_depth': 15, 'min_samples_split': 2}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:16,359] Trial 81 finished with value: 0.9109487283865724 and parameters: {'n_estimators': 87, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:17,050] Trial 82 finished with value: 0.9125533909161649 and parameters: {'n_estimators': 82, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:17,808] Trial 83 finished with value: 0.9099705079647047 and parameters: {'n_estimators': 92, 'max_depth': 22, 'min_samples_split': 9}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:18,493] Trial 84 finished with value: 0.9125533909161649 and parameters: {'n_estimators': 82, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:19,190] Trial 85 finished with value: 0.9125533909161649 and parameters: {'n_estimators': 83, 'max_depth': 25, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:19,663] Trial 86 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 56, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:20,378] Trial 87 finished with value: 0.9037479433538547 and parameters: {'n_estimators': 84, 'max_depth': 30, 'min_samples_split': 3}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:20,997] Trial 88 finished with value: 0.9095805438321392 and parameters: {'n_estimators': 74, 'max_depth': 25, 'min_samples_split': 5}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:21,573] Trial 89 finished with value: 0.9067029371345452 and parameters: {'n_estimators': 68, 'max_depth': 26, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:22,233] Trial 90 finished with value: 0.9095805438321392 and parameters: {'n_estimators': 81, 'max_depth': 32, 'min_samples_split': 5}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:23,088] Trial 91 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 103, 'max_depth': 22, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:23,870] Trial 92 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 93, 'max_depth': 27, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:24,707] Trial 93 finished with value: 0.9081554100155895 and parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:25,349] Trial 94 finished with value: 0.9051607468858635 and parameters: {'n_estimators': 76, 'max_depth': 21, 'min_samples_split': 3}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:26,059] Trial 95 finished with value: 0.911022923273274 and parameters: {'n_estimators': 86, 'max_depth': 18, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:26,822] Trial 96 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 91, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
71,71,0.912553,2026-06-23 17:43:08.909295,2026-06-23 17:43:09.606481,0 days 00:00:00.697186,19,4,82,COMPLETE
82,82,0.912553,2026-06-23 17:43:16.359662,2026-06-23 17:43:17.050746,0 days 00:00:00.691084,24,4,82,COMPLETE
85,85,0.912553,2026-06-23 17:43:18.493525,2026-06-23 17:43:19.190370,0 days 00:00:00.696845,25,4,83,COMPLETE
84,84,0.912553,2026-06-23 17:43:17.808516,2026-06-23 17:43:18.493525,0 days 00:00:00.685009,24,4,82,COMPLETE
96,96,0.912363,2026-06-23 17:43:26.059093,2026-06-23 17:43:26.822892,0 days 00:00:00.763799,24,4,91,COMPLETE

In [ ]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_f1_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_f1_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_f1_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for F1')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.86      0.92        98

    accuracy                           0.99      1083
   macro avg       0.99      0.93      0.96      1083
weighted avg       0.99      0.99      0.99      1083

### Conclusions

In [ ]:
pd.concat(classification_reports, keys=classification_report_keys)

                                                                 precision  \
Baseline Decision Tree Classifier                  0              0.987730
                                                   1              0.819048
                                                   accuracy       0.971376
                                                   macro avg      0.903389
                                                   weighted avg   0.972466
Decision Tree Classifier with Standard Scaling     0              0.987730
                                                   1              0.819048
                                                   accuracy       0.971376
                                                   macro avg      0.903389
                                                   weighted avg   0.972466
Baseline Random Forest Classifier                  0              0.986961
                                                   1              0.988372
                                                   accuracy       0.987073
                                                   macro avg      0.987666
                                                   weighted avg   0.987089
Random Forest Classifier with Standard Scaling     0              0.986961
                                                   1              0.988372
                                                   accuracy       0.987073
                                                   macro avg      0.987666
                                                   weighted avg   0.987089
Random Forest Classifier with Parameter Tuning ... 0              0.988844
                                                   1              0.896907
                                                   accuracy       0.980609
                                                   macro avg      0.942876
                                                   weighted avg   0.980525
Random Forest Classifier with Parameter Tuning ... 0              0.985972
                                                   1              0.988235
                                                   accuracy       0.986150
                                                   macro avg      0.987104
                                                   weighted avg   0.986177

                                                                   recall  \
Baseline Decision Tree Classifier                  0             0.980711
                                                   1             0.877551
                                                   accuracy      0.971376
                                                   macro avg     0.929131
                                                   weighted avg  0.971376
Decision Tree Classifier with Standard Scaling     0             0.980711
                                                   1             0.877551
                                                   accuracy      0.971376
                                                   macro avg     0.929131
                                                   weighted avg  0.971376
Baseline Random Forest Classifier                  0             0.998985
                                                   1             0.867347
                                                   accuracy      0.987073
                                                   macro avg     0.933166
                                                   weighted avg  0.987073
Random Forest Classifier with Standard Scaling     0             0.998985
                                                   1             0.867347
                                                   accuracy      0.987073
                                                   macro avg     0.933166
                                                   weighted avg  0.987073
Random Forest Classifier with Parameter Tuning ... 0             0.989848
                                                   1             0.887755
                                                   accuracy      0.980609
                                                   macro avg     0.938801
                                                   weighted avg  0.980609
Random Forest Classifier with Parameter Tuning ... 0             0.998985
                                                   1             0.857143
                                                   accuracy      0.986150
                                                   macro avg     0.928064
                                                   weighted avg  0.986150

                                                                 f1-score  \
Baseline Decision Tree Classifier                  0             0.984208
                                                   1             0.847291
                                                   accuracy      0.971376
                                                   macro avg     0.915749
                                                   weighted avg  0.971818
Decision Tree Classifier with Standard Scaling     0             0.984208
                                                   1             0.847291
                                                   accuracy      0.971376
                                                   macro avg     0.915749
                                                   weighted avg  0.971818
Baseline Random Forest Classifier                  0             0.992936
                                                   1             0.923913
                                                   accuracy      0.987073
                                                   macro avg     0.958425
                                                   weighted avg  0.986691
Random Forest Classifier with Standard Scaling     0             0.992936
                                                   1             0.923913
                                                   accuracy      0.987073
                                                   macro avg     0.958425
                                                   weighted avg  0.986691
Random Forest Classifier with Parameter Tuning ... 0             0.989346
                                                   1             0.892308
                                                   accuracy      0.980609
                                                   macro avg     0.940827
                                                   weighted avg  0.980565
Random Forest Classifier with Parameter Tuning ... 0             0.992436
                                                   1             0.918033
                                                   accuracy      0.986150
                                                   macro avg     0.955234
                                                   weighted avg  0.985703

                                                                     support
Baseline Decision Tree Classifier                  0              985.000000
                                                   1               98.000000
                                                   accuracy         0.971376
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Decision Tree Classifier with Standard Scaling     0              985.000000
                                                   1               98.000000
                                                   accuracy         0.971376
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Baseline Random Forest Classifier                  0              985.000000
                                                   1               98.000000
                                                   accuracy         0.987073
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Standard Scaling     0              985.000000
                                                   1               98.000000
                                                   accuracy         0.987073
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Parameter Tuning ... 0              985.000000
                                                   1               98.000000
                                                   accuracy         0.980609
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Parameter Tuning ... 0              985.000000
                                                   1               98.000000
                                                   accuracy         0.986150
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000

## PPP

In [ ]:
random_state = 42
classification_reports = []
classification_report_keys = []

### Import Data

In [ ]:
# Import credit card datasaet
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/ppp_cleaned.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

### Undersampling due to heavy class imbalance

In [ ]:
from collections import Counter


X = df.drop(columns='Fraud')
y = df['Fraud']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(sampling_strategy=0.1, random_state=random_state)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 284315, 1: 492})
Resampled dataset shape: Counter({0: 4920, 1: 492})

### Split Data

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Decision Tree Classifier
#### (No feature scaling)

In [ ]:
model = DecisionTreeClassifier(random_state=random_state)

In [ ]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Decision Tree Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       985
           1       0.82      0.88      0.85        98

    accuracy                           0.97      1083
   macro avg       0.90      0.93      0.92      1083
weighted avg       0.97      0.97      0.97      1083

### Feature Scaling + Decision Tree Classifier

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
model = DecisionTreeClassifier(random_state=random_state)

In [ ]:
model.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test_scaled)

In [ ]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Decision Tree Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       985
           1       0.82      0.88      0.85        98

    accuracy                           0.97      1083
   macro avg       0.90      0.93      0.92      1083
weighted avg       0.97      0.97      0.97      1083

### Baseline Random Forest Classifier
#### (No feature scaling)

In [ ]:
model = RandomForestClassifier(random_state=random_state)

In [ ]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Random Forest Classifier')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.87      0.92        98

    accuracy                           0.99      1083
   macro avg       0.99      0.93      0.96      1083
weighted avg       0.99      0.99      0.99      1083

### Feature Scaling + Decision Tree Classifier

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
model = RandomForestClassifier(random_state=random_state)

In [ ]:
model.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_pred = model.predict(X_test_scaled)

In [ ]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.87      0.92        98

    accuracy                           0.99      1083
   macro avg       0.99      0.93      0.96      1083
weighted avg       0.99      0.99      0.99      1083

### Parameter Tuning Random Forest (optimized for recall)

In [ ]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [ ]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_recall_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_recall_df)

[I 2026-06-23 17:41:33,956] A new study created in memory with name: no-name-61e32d59-1f41-4ac7-b3ed-936a6daf8fc9
[I 2026-06-23 17:41:36,044] Trial 0 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 97, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:38,247] Trial 1 finished with value: 0.850113599480688 and parameters: {'n_estimators': 120, 'max_depth': 19, 'min_samples_split': 9}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:40,577] Trial 2 finished with value: 0.850113599480688 and parameters: {'n_estimators': 162, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:42,954] Trial 3 finished with value: 0.850113599480688 and parameters: {'n_estimators': 143, 'max_depth': 29, 'min_samples_split': 8}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:43,913] Trial 4 finished with value: 0.850113599480688 and parameters: {'n_estimators': 110, 'max_depth': 20, 'min_samples_split': 10}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:43,991] Trial 5 finished with value: 0.8450503083414477 and parameters: {'n_estimators': 14, 'max_depth': 2, 'min_samples_split': 2}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:45,549] Trial 6 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 180, 'max_depth': 14, 'min_samples_split': 7}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:45,876] Trial 7 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 112, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 0 with value: 0.8577085361895488.
[I 2026-06-23 17:41:45,970] Trial 8 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 18, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:46,080] Trial 9 finished with value: 0.822233041220383 and parameters: {'n_estimators': 10, 'max_depth': 17, 'min_samples_split': 3}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:46,424] Trial 10 finished with value: 0.860240181759169 and parameters: {'n_estimators': 66, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:46,704] Trial 11 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 54, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:47,022] Trial 12 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 58, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:47,478] Trial 13 finished with value: 0.8475819539110677 and parameters: {'n_estimators': 55, 'max_depth': 8, 'min_samples_split': 4}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:47,793] Trial 14 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 77, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 8 with value: 0.8602726387536513.
[I 2026-06-23 17:41:47,934] Trial 15 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 31, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:48,058] Trial 16 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 36, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:48,340] Trial 17 finished with value: 0.8450503083414475 and parameters: {'n_estimators': 30, 'max_depth': 9, 'min_samples_split': 7}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:48,698] Trial 18 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 84, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:48,927] Trial 19 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 32, 'max_depth': 6, 'min_samples_split': 9}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:49,098] Trial 20 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 38, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 15 with value: 0.8628042843232716.
[I 2026-06-23 17:41:49,256] Trial 21 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 35, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:49,367] Trial 22 finished with value: 0.850113599480688 and parameters: {'n_estimators': 28, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:49,647] Trial 23 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 46, 'max_depth': 5, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:49,743] Trial 24 finished with value: 0.8577409931840311 and parameters: {'n_estimators': 17, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:49,978] Trial 25 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 74, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:50,524] Trial 26 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 93, 'max_depth': 5, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:50,729] Trial 27 finished with value: 0.8374553716325869 and parameters: {'n_estimators': 22, 'max_depth': 10, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:50,948] Trial 28 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 52, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:51,216] Trial 29 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 42, 'max_depth': 5, 'min_samples_split': 9}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:51,606] Trial 30 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 129, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:51,810] Trial 31 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 47, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:51,888] Trial 32 finished with value: 0.8501135994806882 and parameters: {'n_estimators': 10, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:52,188] Trial 33 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 66, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:52,298] Trial 34 finished with value: 0.8552093476144108 and parameters: {'n_estimators': 25, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:52,920] Trial 35 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 95, 'max_depth': 6, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:53,121] Trial 36 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 46, 'max_depth': 3, 'min_samples_split': 10}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:53,214] Trial 37 finished with value: 0.8552093476144108 and parameters: {'n_estimators': 23, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:54,166] Trial 38 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 195, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:54,730] Trial 39 finished with value: 0.850113599480688 and parameters: {'n_estimators': 65, 'max_depth': 12, 'min_samples_split': 8}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:55,652] Trial 40 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 138, 'max_depth': 6, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:55,838] Trial 41 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 40, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:55,995] Trial 42 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 37, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:56,105] Trial 43 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 18, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:56,619] Trial 44 finished with value: 0.8349237260629666 and parameters: {'n_estimators': 54, 'max_depth': 26, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:57,089] Trial 45 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 160, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:57,246] Trial 46 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 31, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:57,444] Trial 47 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 60, 'max_depth': 2, 'min_samples_split': 9}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:57,631] Trial 48 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 34, 'max_depth': 4, 'min_samples_split': 8}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:57,850] Trial 49 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 50, 'max_depth': 3, 'min_samples_split': 9}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:58,307] Trial 50 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 77, 'max_depth': 5, 'min_samples_split': 10}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:58,400] Trial 51 finished with value: 0.8577409931840311 and parameters: {'n_estimators': 15, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:58,542] Trial 52 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 32, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:58,684] Trial 53 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 29, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:58,901] Trial 54 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 39, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:59,009] Trial 55 finished with value: 0.850113599480688 and parameters: {'n_estimators': 28, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:59,446] Trial 56 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 107, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:59,540] Trial 57 finished with value: 0.8552093476144108 and parameters: {'n_estimators': 21, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:59,837] Trial 58 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 57, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:41:59,993] Trial 59 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 35, 'max_depth': 3, 'min_samples_split': 2}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,227] Trial 60 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 73, 'max_depth': 2, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,368] Trial 61 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 29, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,556] Trial 62 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 42, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,633] Trial 63 finished with value: 0.8577734501785134 and parameters: {'n_estimators': 11, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,786] Trial 64 finished with value: 0.860240181759169 and parameters: {'n_estimators': 27, 'max_depth': 4, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:00,956] Trial 65 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 51, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:01,174] Trial 66 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 34, 'max_depth': 5, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:01,376] Trial 67 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 45, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:01,532] Trial 68 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 18, 'max_depth': 7, 'min_samples_split': 3}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:01,735] Trial 69 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 62, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:02,189] Trial 70 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 115, 'max_depth': 3, 'min_samples_split': 6}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:02,330] Trial 71 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 30, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 21 with value: 0.8653359298928919.
[I 2026-06-23 17:42:02,470] Trial 72 finished with value: 0.8678675754625121 and parameters: {'n_estimators': 26, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:02,626] Trial 73 finished with value: 0.8577085361895488 and parameters: {'n_estimators': 25, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:02,768] Trial 74 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 31, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:02,910] Trial 75 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 30, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,016] Trial 76 finished with value: 0.8526452450503083 and parameters: {'n_estimators': 16, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,112] Trial 77 finished with value: 0.8552093476144108 and parameters: {'n_estimators': 23, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,252] Trial 78 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 31, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,426] Trial 79 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 41, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,568] Trial 80 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 20, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,708] Trial 81 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 30, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,786] Trial 82 finished with value: 0.8628367413177539 and parameters: {'n_estimators': 13, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:03,910] Trial 83 finished with value: 0.8678675754625121 and parameters: {'n_estimators': 26, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,081] Trial 84 finished with value: 0.860240181759169 and parameters: {'n_estimators': 27, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,206] Trial 85 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 36, 'max_depth': 2, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,409] Trial 86 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 45, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,518] Trial 87 finished with value: 0.8197013956507627 and parameters: {'n_estimators': 10, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,627] Trial 88 finished with value: 0.8577409931840311 and parameters: {'n_estimators': 23, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:04,908] Trial 89 finished with value: 0.8425186627718274 and parameters: {'n_estimators': 88, 'max_depth': 2, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,173] Trial 90 finished with value: 0.860240181759169 and parameters: {'n_estimators': 49, 'max_depth': 4, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,330] Trial 91 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 33, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,471] Trial 92 finished with value: 0.8653359298928919 and parameters: {'n_estimators': 30, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,641] Trial 93 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 40, 'max_depth': 3, 'min_samples_split': 4}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,750] Trial 94 finished with value: 0.8628042843232716 and parameters: {'n_estimators': 21, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:05,924] Trial 95 finished with value: 0.8551768906199285 and parameters: {'n_estimators': 27, 'max_depth': 4, 'min_samples_split': 6}. Best is trial 72 with value: 0.8678675754625121.
[I 2026-06-23 17:42:06,096] Trial 96 finished with value: 0.8602726387536513 and parameters: {'n_estimators': 38, 'max_depth': 3, 'min_samples_split': 5}. Best is trial 72 with value: 0.8678675754625121.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
72,72,0.867868,2026-06-23 17:42:02.330374,2026-06-23 17:42:02.470593,0 days 00:00:00.140219,3,5,26,COMPLETE
83,83,0.867868,2026-06-23 17:42:03.786319,2026-06-23 17:42:03.910870,0 days 00:00:00.124551,3,5,26,COMPLETE
21,21,0.865336,2026-06-23 17:41:49.098421,2026-06-23 17:41:49.256988,0 days 00:00:00.158567,3,5,35,COMPLETE
53,53,0.865336,2026-06-23 17:41:58.542672,2026-06-23 17:41:58.684352,0 days 00:00:00.141680,3,3,29,COMPLETE
78,78,0.865336,2026-06-23 17:42:03.112271,2026-06-23 17:42:03.252197,0 days 00:00:00.139926,3,5,31,COMPLETE

In [ ]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_recall_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_recall_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_recall_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for Recall')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       985
           1       0.90      0.89      0.89        98

    accuracy                           0.98      1083
   macro avg       0.94      0.94      0.94      1083
weighted avg       0.98      0.98      0.98      1083

### Parameter Tuning Random Forest (Optimized for F1)

In [ ]:
# Parameter tuning
def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 10, 200)
    max_depth = trial.suggest_int("max_depth", 2, 32, log=True)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    
    model = RandomForestClassifier(
        class_weight='balanced',
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    return scores.mean()


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

top_5_f1_df = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_f1_df)

[I 2026-06-23 17:42:06,586] A new study created in memory with name: no-name-6ba02d91-df2b-47a8-a2d1-b2640eeea4cd
[I 2026-06-23 17:42:06,694] Trial 0 finished with value: 0.8807512071696536 and parameters: {'n_estimators': 26, 'max_depth': 2, 'min_samples_split': 7}. Best is trial 0 with value: 0.8807512071696536.
[I 2026-06-23 17:42:07,197] Trial 1 finished with value: 0.9044703945363148 and parameters: {'n_estimators': 130, 'max_depth': 3, 'min_samples_split': 7}. Best is trial 1 with value: 0.9044703945363148.
[I 2026-06-23 17:42:07,338] Trial 2 finished with value: 0.8826923363743286 and parameters: {'n_estimators': 45, 'max_depth': 2, 'min_samples_split': 8}. Best is trial 1 with value: 0.9044703945363148.
[I 2026-06-23 17:42:08,404] Trial 3 finished with value: 0.9091131422187079 and parameters: {'n_estimators': 168, 'max_depth': 6, 'min_samples_split': 4}. Best is trial 3 with value: 0.9091131422187079.
[I 2026-06-23 17:42:09,551] Trial 4 finished with value: 0.9069214437697131 and parameters: {'n_estimators': 150, 'max_depth': 8, 'min_samples_split': 8}. Best is trial 3 with value: 0.9091131422187079.
[I 2026-06-23 17:42:11,167] Trial 5 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 186, 'max_depth': 24, 'min_samples_split': 3}. Best is trial 5 with value: 0.9093597612199407.
[I 2026-06-23 17:42:11,539] Trial 6 finished with value: 0.9074562633945487 and parameters: {'n_estimators': 41, 'max_depth': 32, 'min_samples_split': 9}. Best is trial 5 with value: 0.9093597612199407.
[I 2026-06-23 17:42:11,836] Trial 7 finished with value: 0.9080407782170934 and parameters: {'n_estimators': 32, 'max_depth': 11, 'min_samples_split': 5}. Best is trial 5 with value: 0.9093597612199407.
[I 2026-06-23 17:42:12,384] Trial 8 finished with value: 0.8995063197303192 and parameters: {'n_estimators': 115, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 5 with value: 0.9093597612199407.
[I 2026-06-23 17:42:13,399] Trial 9 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 119, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:14,121] Trial 10 finished with value: 0.9036870062732131 and parameters: {'n_estimators': 81, 'max_depth': 16, 'min_samples_split': 2}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:15,816] Trial 11 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 195, 'max_depth': 32, 'min_samples_split': 2}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:16,553] Trial 12 finished with value: 0.911022923273274 and parameters: {'n_estimators': 86, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:17,232] Trial 13 finished with value: 0.9097208947093322 and parameters: {'n_estimators': 81, 'max_depth': 14, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:17,926] Trial 14 finished with value: 0.9095805438321392 and parameters: {'n_estimators': 85, 'max_depth': 19, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:18,740] Trial 15 finished with value: 0.9096959319659905 and parameters: {'n_estimators': 107, 'max_depth': 8, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:19,290] Trial 16 finished with value: 0.901235827664399 and parameters: {'n_estimators': 61, 'max_depth': 12, 'min_samples_split': 6}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:20,489] Trial 17 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 138, 'max_depth': 21, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:21,287] Trial 18 finished with value: 0.9108445069670784 and parameters: {'n_estimators': 137, 'max_depth': 5, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:22,711] Trial 19 finished with value: 0.9087166448300469 and parameters: {'n_estimators': 161, 'max_depth': 25, 'min_samples_split': 10}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:23,776] Trial 20 finished with value: 0.9068221925128264 and parameters: {'n_estimators': 127, 'max_depth': 11, 'min_samples_split': 6}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:24,546] Trial 21 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 92, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:25,346] Trial 22 finished with value: 0.9096858776584804 and parameters: {'n_estimators': 97, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:26,522] Trial 23 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 145, 'max_depth': 25, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:27,510] Trial 24 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 118, 'max_depth': 13, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:28,007] Trial 25 finished with value: 0.9054490739998874 and parameters: {'n_estimators': 62, 'max_depth': 9, 'min_samples_split': 6}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:28,820] Trial 26 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 98, 'max_depth': 22, 'min_samples_split': 2}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:30,293] Trial 27 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 175, 'max_depth': 15, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:31,517] Trial 28 finished with value: 0.9082720074123956 and parameters: {'n_estimators': 148, 'max_depth': 27, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:32,081] Trial 29 finished with value: 0.9036883771160378 and parameters: {'n_estimators': 64, 'max_depth': 19, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:32,997] Trial 30 finished with value: 0.9084519114126041 and parameters: {'n_estimators': 112, 'max_depth': 10, 'min_samples_split': 7}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:33,124] Trial 31 finished with value: 0.9065312074173273 and parameters: {'n_estimators': 13, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:33,894] Trial 32 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 91, 'max_depth': 22, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:34,930] Trial 33 finished with value: 0.9097443771822211 and parameters: {'n_estimators': 126, 'max_depth': 29, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:35,282] Trial 34 finished with value: 0.9055750871970781 and parameters: {'n_estimators': 96, 'max_depth': 3, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:35,658] Trial 35 finished with value: 0.8993688225058053 and parameters: {'n_estimators': 135, 'max_depth': 2, 'min_samples_split': 6}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:36,258] Trial 36 finished with value: 0.9069214437697131 and parameters: {'n_estimators': 71, 'max_depth': 22, 'min_samples_split': 7}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:37,246] Trial 37 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 119, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:38,222] Trial 38 finished with value: 0.9079416731587173 and parameters: {'n_estimators': 160, 'max_depth': 6, 'min_samples_split': 8}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:38,634] Trial 39 finished with value: 0.9080238857357024 and parameters: {'n_estimators': 48, 'max_depth': 23, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:39,495] Trial 40 finished with value: 0.9049398026937947 and parameters: {'n_estimators': 104, 'max_depth': 28, 'min_samples_split': 2}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:40,471] Trial 41 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 118, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:41,514] Trial 42 finished with value: 0.9078080370820096 and parameters: {'n_estimators': 126, 'max_depth': 14, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:42,641] Trial 43 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 137, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:43,545] Trial 44 finished with value: 0.9097443771822211 and parameters: {'n_estimators': 109, 'max_depth': 21, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:44,321] Trial 45 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 93, 'max_depth': 32, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:44,945] Trial 46 finished with value: 0.9109756873199977 and parameters: {'n_estimators': 75, 'max_depth': 18, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:45,921] Trial 47 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 120, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:46,655] Trial 48 finished with value: 0.9036870062732131 and parameters: {'n_estimators': 89, 'max_depth': 25, 'min_samples_split': 2}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:47,497] Trial 49 finished with value: 0.9109487283865724 and parameters: {'n_estimators': 103, 'max_depth': 15, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:48,795] Trial 50 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 158, 'max_depth': 21, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:49,770] Trial 51 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 119, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:50,898] Trial 52 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 133, 'max_depth': 13, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:51,850] Trial 53 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 113, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:52,711] Trial 54 finished with value: 0.9109487283865724 and parameters: {'n_estimators': 103, 'max_depth': 20, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:53,862] Trial 55 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 139, 'max_depth': 27, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:54,475] Trial 56 finished with value: 0.9085500169854892 and parameters: {'n_estimators': 79, 'max_depth': 9, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:55,493] Trial 57 finished with value: 0.9080930260656288 and parameters: {'n_estimators': 123, 'max_depth': 24, 'min_samples_split': 6}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:56,457] Trial 58 finished with value: 0.9075451757700563 and parameters: {'n_estimators': 145, 'max_depth': 7, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:57,172] Trial 59 finished with value: 0.9093796581087222 and parameters: {'n_estimators': 88, 'max_depth': 14, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:58,208] Trial 60 finished with value: 0.9063555642009653 and parameters: {'n_estimators': 130, 'max_depth': 11, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:42:59,185] Trial 61 finished with value: 0.9109487283865724 and parameters: {'n_estimators': 120, 'max_depth': 15, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:00,149] Trial 62 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 113, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:01,386] Trial 63 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 152, 'max_depth': 17, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:02,295] Trial 64 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 108, 'max_depth': 18, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:03,647] Trial 65 finished with value: 0.9087166448300469 and parameters: {'n_estimators': 170, 'max_depth': 20, 'min_samples_split': 10}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:04,623] Trial 66 finished with value: 0.9066132197669077 and parameters: {'n_estimators': 117, 'max_depth': 29, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:05,435] Trial 67 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 98, 'max_depth': 23, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:06,599] Trial 68 finished with value: 0.9108902288628317 and parameters: {'n_estimators': 142, 'max_depth': 16, 'min_samples_split': 4}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:07,678] Trial 69 finished with value: 0.9093597612199407 and parameters: {'n_estimators': 131, 'max_depth': 12, 'min_samples_split': 3}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:08,909] Trial 70 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 153, 'max_depth': 13, 'min_samples_split': 5}. Best is trial 9 with value: 0.9123625986326573.
[I 2026-06-23 17:43:09,606] Trial 71 finished with value: 0.9125533909161649 and parameters: {'n_estimators': 82, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:10,152] Trial 72 finished with value: 0.9081554100155895 and parameters: {'n_estimators': 66, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:10,606] Trial 73 finished with value: 0.9079458909738557 and parameters: {'n_estimators': 54, 'max_depth': 26, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:11,370] Trial 74 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 93, 'max_depth': 21, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:12,073] Trial 75 finished with value: 0.9037479433538547 and parameters: {'n_estimators': 82, 'max_depth': 23, 'min_samples_split': 3}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:12,661] Trial 76 finished with value: 0.9081294282870637 and parameters: {'n_estimators': 70, 'max_depth': 18, 'min_samples_split': 5}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:13,110] Trial 77 finished with value: 0.9021307312154049 and parameters: {'n_estimators': 99, 'max_depth': 4, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:14,001] Trial 78 finished with value: 0.9097443771822211 and parameters: {'n_estimators': 109, 'max_depth': 30, 'min_samples_split': 5}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:14,983] Trial 79 finished with value: 0.9094182607436814 and parameters: {'n_estimators': 123, 'max_depth': 10, 'min_samples_split': 3}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:15,620] Trial 80 finished with value: 0.905200416234899 and parameters: {'n_estimators': 76, 'max_depth': 15, 'min_samples_split': 2}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:16,359] Trial 81 finished with value: 0.9109487283865724 and parameters: {'n_estimators': 87, 'max_depth': 20, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:17,050] Trial 82 finished with value: 0.9125533909161649 and parameters: {'n_estimators': 82, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:17,808] Trial 83 finished with value: 0.9099705079647047 and parameters: {'n_estimators': 92, 'max_depth': 22, 'min_samples_split': 9}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:18,493] Trial 84 finished with value: 0.9125533909161649 and parameters: {'n_estimators': 82, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:19,190] Trial 85 finished with value: 0.9125533909161649 and parameters: {'n_estimators': 83, 'max_depth': 25, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:19,663] Trial 86 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 56, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:20,378] Trial 87 finished with value: 0.9037479433538547 and parameters: {'n_estimators': 84, 'max_depth': 30, 'min_samples_split': 3}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:20,997] Trial 88 finished with value: 0.9095805438321392 and parameters: {'n_estimators': 74, 'max_depth': 25, 'min_samples_split': 5}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:21,573] Trial 89 finished with value: 0.9067029371345452 and parameters: {'n_estimators': 68, 'max_depth': 26, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:22,233] Trial 90 finished with value: 0.9095805438321392 and parameters: {'n_estimators': 81, 'max_depth': 32, 'min_samples_split': 5}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:23,088] Trial 91 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 103, 'max_depth': 22, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:23,870] Trial 92 finished with value: 0.9094763586167467 and parameters: {'n_estimators': 93, 'max_depth': 27, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:24,707] Trial 93 finished with value: 0.9081554100155895 and parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:25,349] Trial 94 finished with value: 0.9051607468858635 and parameters: {'n_estimators': 76, 'max_depth': 21, 'min_samples_split': 3}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:26,059] Trial 95 finished with value: 0.911022923273274 and parameters: {'n_estimators': 86, 'max_depth': 18, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.
[I 2026-06-23 17:43:26,822] Trial 96 finished with value: 0.9123625986326573 and parameters: {'n_estimators': 91, 'max_depth': 24, 'min_samples_split': 4}. Best is trial 71 with value: 0.9125533909161649.

,number,value,datetime_start,datetime_complete,duration,params_max_depth,params_min_samples_split,params_n_estimators,state
71,71,0.912553,2026-06-23 17:43:08.909295,2026-06-23 17:43:09.606481,0 days 00:00:00.697186,19,4,82,COMPLETE
82,82,0.912553,2026-06-23 17:43:16.359662,2026-06-23 17:43:17.050746,0 days 00:00:00.691084,24,4,82,COMPLETE
85,85,0.912553,2026-06-23 17:43:18.493525,2026-06-23 17:43:19.190370,0 days 00:00:00.696845,25,4,83,COMPLETE
84,84,0.912553,2026-06-23 17:43:17.808516,2026-06-23 17:43:18.493525,0 days 00:00:00.685009,24,4,82,COMPLETE
96,96,0.912363,2026-06-23 17:43:26.059093,2026-06-23 17:43:26.822892,0 days 00:00:00.763799,24,4,91,COMPLETE

In [ ]:
# Train using optimal parameters
model = RandomForestClassifier(
    class_weight='balanced',
    n_estimators=top_5_f1_df.head(1)['params_n_estimators'].item(),
    max_depth=top_5_f1_df.head(1)['params_max_depth'].item(),
    min_samples_split=top_5_f1_df.head(1)['params_min_samples_split'].item(),
    random_state=random_state
)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Random Forest Classifier with Parameter Tuning Optimized for F1')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.99      0.86      0.92        98

    accuracy                           0.99      1083
   macro avg       0.99      0.93      0.96      1083
weighted avg       0.99      0.99      0.99      1083

### Conclusions

In [ ]:
pd.concat(classification_reports, keys=classification_report_keys)

                                                                 precision  \
Baseline Decision Tree Classifier                  0              0.987730
                                                   1              0.819048
                                                   accuracy       0.971376
                                                   macro avg      0.903389
                                                   weighted avg   0.972466
Decision Tree Classifier with Standard Scaling     0              0.987730
                                                   1              0.819048
                                                   accuracy       0.971376
                                                   macro avg      0.903389
                                                   weighted avg   0.972466
Baseline Random Forest Classifier                  0              0.986961
                                                   1              0.988372
                                                   accuracy       0.987073
                                                   macro avg      0.987666
                                                   weighted avg   0.987089
Random Forest Classifier with Standard Scaling     0              0.986961
                                                   1              0.988372
                                                   accuracy       0.987073
                                                   macro avg      0.987666
                                                   weighted avg   0.987089
Random Forest Classifier with Parameter Tuning ... 0              0.988844
                                                   1              0.896907
                                                   accuracy       0.980609
                                                   macro avg      0.942876
                                                   weighted avg   0.980525
Random Forest Classifier with Parameter Tuning ... 0              0.985972
                                                   1              0.988235
                                                   accuracy       0.986150
                                                   macro avg      0.987104
                                                   weighted avg   0.986177

                                                                   recall  \
Baseline Decision Tree Classifier                  0             0.980711
                                                   1             0.877551
                                                   accuracy      0.971376
                                                   macro avg     0.929131
                                                   weighted avg  0.971376
Decision Tree Classifier with Standard Scaling     0             0.980711
                                                   1             0.877551
                                                   accuracy      0.971376
                                                   macro avg     0.929131
                                                   weighted avg  0.971376
Baseline Random Forest Classifier                  0             0.998985
                                                   1             0.867347
                                                   accuracy      0.987073
                                                   macro avg     0.933166
                                                   weighted avg  0.987073
Random Forest Classifier with Standard Scaling     0             0.998985
                                                   1             0.867347
                                                   accuracy      0.987073
                                                   macro avg     0.933166
                                                   weighted avg  0.987073
Random Forest Classifier with Parameter Tuning ... 0             0.989848
                                                   1             0.887755
                                                   accuracy      0.980609
                                                   macro avg     0.938801
                                                   weighted avg  0.980609
Random Forest Classifier with Parameter Tuning ... 0             0.998985
                                                   1             0.857143
                                                   accuracy      0.986150
                                                   macro avg     0.928064
                                                   weighted avg  0.986150

                                                                 f1-score  \
Baseline Decision Tree Classifier                  0             0.984208
                                                   1             0.847291
                                                   accuracy      0.971376
                                                   macro avg     0.915749
                                                   weighted avg  0.971818
Decision Tree Classifier with Standard Scaling     0             0.984208
                                                   1             0.847291
                                                   accuracy      0.971376
                                                   macro avg     0.915749
                                                   weighted avg  0.971818
Baseline Random Forest Classifier                  0             0.992936
                                                   1             0.923913
                                                   accuracy      0.987073
                                                   macro avg     0.958425
                                                   weighted avg  0.986691
Random Forest Classifier with Standard Scaling     0             0.992936
                                                   1             0.923913
                                                   accuracy      0.987073
                                                   macro avg     0.958425
                                                   weighted avg  0.986691
Random Forest Classifier with Parameter Tuning ... 0             0.989346
                                                   1             0.892308
                                                   accuracy      0.980609
                                                   macro avg     0.940827
                                                   weighted avg  0.980565
Random Forest Classifier with Parameter Tuning ... 0             0.992436
                                                   1             0.918033
                                                   accuracy      0.986150
                                                   macro avg     0.955234
                                                   weighted avg  0.985703

                                                                     support
Baseline Decision Tree Classifier                  0              985.000000
                                                   1               98.000000
                                                   accuracy         0.971376
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Decision Tree Classifier with Standard Scaling     0              985.000000
                                                   1               98.000000
                                                   accuracy         0.971376
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Baseline Random Forest Classifier                  0              985.000000
                                                   1               98.000000
                                                   accuracy         0.987073
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Standard Scaling     0              985.000000
                                                   1               98.000000
                                                   accuracy         0.987073
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Parameter Tuning ... 0              985.000000
                                                   1               98.000000
                                                   accuracy         0.980609
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000
Random Forest Classifier with Parameter Tuning ... 0              985.000000
                                                   1               98.000000
                                                   accuracy         0.986150
                                                   macro avg     1083.000000
                                                   weighted avg  1083.000000