In [109]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm 
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
import seaborn as sns
from sklearn.metrics import mean_absolute_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
import optuna
from sklearn.model_selection import cross_val_score

Note: LinearRegression/Lasso/Elastic Net/Ridge did not make sense for the fraud use case (binary classification). So I instead use Logistic Reg with different penalty

In [110]:
random_state=42

In [111]:
classification_reports = []
classification_report_keys = []

## Data

In [112]:
# Import IBM dataset
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/ibm_hi_small_trans_cleaned.csv')
df

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Amount Paid,Is Laundering,Amount_Received_USD,Amount_Paid_USD,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,3697.340000,0,3697.340000,3697.340000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,0.010000,0,0.010000,0.010000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,14675.570000,0,14675.570000,14675.570000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,2806.970000,0,2806.970000,2806.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,36682.970000,0,36682.970000,36682.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,0.154978,0,3107.386389,3107.386389,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,0.108128,0,2168.020464,2168.020464,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,0.004988,0,100.011894,100.011894,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,0.038417,0,770.280058,770.280058,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,0.281983,0,5653.900141,5653.900141,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0

In [113]:
df.drop(columns=['Timestamp', 'From Bank', 'To Bank', 'Account', 'Account.1'], inplace=True)

## Undersampling

In [114]:
from collections import Counter


X = df.drop(columns='Is Laundering')
y = df['Is Laundering']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 5073168, 1: 5177})
Resampled dataset shape: Counter({0: 5177, 1: 5177})

## Split Data

In [115]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

## Baseline Models
#### (No parameter optimization, feature scaling, or cross validation)

### Linear Regression

In [116]:
model = LogisticRegression()

In [117]:
model.fit(X_train, y_train)

LogisticRegression()

In [118]:
y_pred = model.predict(X_test)

In [119]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline Logistic Regression')

              precision    recall  f1-score   support

           0       1.00      0.01      0.02      1036
           1       0.50      1.00      0.67      1035

    accuracy                           0.50      2071
   macro avg       0.75      0.50      0.34      2071
weighted avg       0.75      0.50      0.34      2071

### Ridge

In [120]:
from sklearn.linear_model import RidgeClassifier


ridge_model = RidgeClassifier(random_state=random_state)

In [121]:
ridge_model.fit(X_train, y_train)

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_ridge.py:213: LinAlgWarning: Ill-conditioned matrix (rcond=2.80134e-23): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

RidgeClassifier(random_state=42)

In [122]:
y_pred = ridge_model.predict(X_test)

In [123]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline Ridge Classifier')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

### Lasso

In [124]:
lasso_model = LogisticRegression(penalty='l1', solver='liblinear')

In [125]:
lasso_model.fit(X_train, y_train)

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

LogisticRegression(penalty='l1', solver='liblinear')

In [126]:
y_pred = lasso_model.predict(X_test)

In [127]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline L1 (Lasso) Logistic Regression')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

## Parameter Tuning

### Logistic Regression

In [128]:
# We can only tune the C (float) and Class_weight to tryout balanced.

In [129]:
# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
from sklearn.model_selection import StratifiedKFold


cv = StratifiedKFold(n_splits=5)

In [130]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        class_weight=class_weight,
        C=c,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

log_reg_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_log_reg_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_log_reg_unscaled_recall_optuna_results)

[I 2026-05-27 19:18:30,545] A new study created in memory with name: no-name-012426de-af03-4fb9-9015-e2cd1939941b
[I 2026-05-27 19:18:30,699] Trial 0 finished with value: 0.8038647342995169 and parameters: {'C': 0.5123388053070168, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:30,853] Trial 1 finished with value: 0.8038647342995169 and parameters: {'C': 0.32652364507662274, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:31,001] Trial 2 finished with value: 0.8038647342995169 and parameters: {'C': 0.7982390744089412, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:31,155] Trial 3 finished with value: 0.8038647342995169 and parameters: {'C': 0.6334500702856152, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:31,306] Trial 4 finished with value: 0.8038647342995169 and parameters: {'C': 0.6580667355328703, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:31,468] Trial 5 finished with value: 0.8038647342995169 and parameters: {'C': 0.38862276608945534, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:31,623] Trial 6 finished with value: 0.8038647342995169 and parameters: {'C': 0.1199371755898885, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:31,786] Trial 7 finished with value: 0.8038647342995169 and parameters: {'C': 0.7005100306765158, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:31,956] Trial 8 finished with value: 0.8038647342995169 and parameters: {'C': 0.651245723411023, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:32,115] Trial 9 finished with value: 0.8038647342995169 and parameters: {'C': 0.738198649849667, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:32,284] Trial 10 finished with value: 0.8038647342995169 and parameters: {'C': 0.9372468285277904, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:32,469] Trial 11 finished with value: 0.8038647342995169 and parameters: {'C': 0.3074272220752294, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:32,637] Trial 12 finished with value: 0.8038647342995169 and parameters: {'C': 0.20754932455764746, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:32,820] Trial 13 finished with value: 0.8038647342995169 and parameters: {'C': 0.46210110638835783, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:32,986] Trial 14 finished with value: 0.8038647342995169 and parameters: {'C': 0.526806063497721, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:33,141] Trial 15 finished with value: 0.8038647342995169 and parameters: {'C': 0.002702634748605104, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:33,314] Trial 16 finished with value: 0.8038647342995169 and parameters: {'C': 0.32318306371631683, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:33,474] Trial 17 finished with value: 0.8038647342995169 and parameters: {'C': 0.5268908952762573, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:33,670] Trial 18 finished with value: 0.8038647342995169 and parameters: {'C': 0.2312481955788021, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:33,862] Trial 19 finished with value: 0.8038647342995169 and parameters: {'C': 0.4323173716293549, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:34,026] Trial 20 finished with value: 0.8038647342995169 and parameters: {'C': 0.9254444144519995, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:34,187] Trial 21 finished with value: 0.8038647342995169 and parameters: {'C': 0.8945143306415944, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:34,341] Trial 22 finished with value: 0.8038647342995169 and parameters: {'C': 0.818457884017065, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:34,500] Trial 23 finished with value: 0.8038647342995169 and parameters: {'C': 0.5592388268434016, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:34,654] Trial 24 finished with value: 0.8038647342995169 and parameters: {'C': 0.8014529912062986, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:34,814] Trial 25 finished with value: 0.8038647342995169 and parameters: {'C': 0.36911431287632074, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:35,002] Trial 26 finished with value: 0.8038647342995169 and parameters: {'C': 0.253375686157714, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:35,157] Trial 27 finished with value: 0.8038647342995169 and parameters: {'C': 0.13940245289473485, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:35,327] Trial 28 finished with value: 0.8038647342995169 and parameters: {'C': 0.8401484539893115, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:35,511] Trial 29 finished with value: 0.8038647342995169 and parameters: {'C': 0.5866190308247329, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:35,685] Trial 30 finished with value: 0.8038647342995169 and parameters: {'C': 0.995832693342625, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:35,844] Trial 31 finished with value: 0.8038647342995169 and parameters: {'C': 0.6307456655494227, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:36,014] Trial 32 finished with value: 0.8038647342995169 and parameters: {'C': 0.7325036202347179, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:36,210] Trial 33 finished with value: 0.8038647342995169 and parameters: {'C': 0.4613096467371884, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:36,401] Trial 34 finished with value: 0.8038647342995169 and parameters: {'C': 0.3974616532108937, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:36,613] Trial 35 finished with value: 0.8038647342995169 and parameters: {'C': 0.6370846486562047, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:36,829] Trial 36 finished with value: 0.8038647342995169 and parameters: {'C': 0.7601114845562691, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:36,986] Trial 37 finished with value: 0.8038647342995169 and parameters: {'C': 0.6087464997722121, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:37,180] Trial 38 finished with value: 0.8038647342995169 and parameters: {'C': 0.6694607983540426, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:37,364] Trial 39 finished with value: 0.8038647342995169 and parameters: {'C': 0.709574612728616, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:37,590] Trial 40 finished with value: 0.8038647342995169 and parameters: {'C': 0.5068249112320529, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:37,768] Trial 41 finished with value: 0.8038647342995169 and parameters: {'C': 0.6838831178771817, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:37,949] Trial 42 finished with value: 0.8038647342995169 and parameters: {'C': 0.7722559964007403, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:38,127] Trial 43 finished with value: 0.8038647342995169 and parameters: {'C': 0.5766925549339788, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:38,298] Trial 44 finished with value: 0.8038647342995169 and parameters: {'C': 0.8584830562227808, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:38,469] Trial 45 finished with value: 0.8038647342995169 and parameters: {'C': 0.32898617453763795, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:38,630] Trial 46 finished with value: 0.8038647342995169 and parameters: {'C': 0.539406120159097, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:38,796] Trial 47 finished with value: 0.8038647342995169 and parameters: {'C': 0.4705782075984624, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:38,981] Trial 48 finished with value: 0.8038647342995169 and parameters: {'C': 0.0757861983281522, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:39,159] Trial 49 finished with value: 0.8038647342995169 and parameters: {'C': 0.28328650497831154, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:39,365] Trial 50 finished with value: 0.8038647342995169 and parameters: {'C': 0.4066338114479478, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:39,518] Trial 51 finished with value: 0.8038647342995169 and parameters: {'C': 0.36829904599926255, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:39,693] Trial 52 finished with value: 0.8038647342995169 and parameters: {'C': 0.18251171425159102, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:39,855] Trial 53 finished with value: 0.8038647342995169 and parameters: {'C': 0.4814712504072708, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:40,031] Trial 54 finished with value: 0.8038647342995169 and parameters: {'C': 0.44429364865189264, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:40,213] Trial 55 finished with value: 0.8038647342995169 and parameters: {'C': 0.35856258123526014, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:40,405] Trial 56 finished with value: 0.8038647342995169 and parameters: {'C': 0.283722256297403, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:40,589] Trial 57 finished with value: 0.803623188405797 and parameters: {'C': 0.5185849639705213, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:40,758] Trial 58 finished with value: 0.8038647342995169 and parameters: {'C': 0.7151103094708805, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:40,918] Trial 59 finished with value: 0.8038647342995169 and parameters: {'C': 0.6138688923936513, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:41,077] Trial 60 finished with value: 0.8038647342995169 and parameters: {'C': 0.41543010871746355, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:41,246] Trial 61 finished with value: 0.8038647342995169 and parameters: {'C': 0.028430598894656545, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:41,395] Trial 62 finished with value: 0.8038647342995169 and parameters: {'C': 0.16853316604452376, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:41,564] Trial 63 finished with value: 0.8038647342995169 and parameters: {'C': 0.087932671254337, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:41,734] Trial 64 finished with value: 0.8038647342995169 and parameters: {'C': 0.24559313135872726, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:41,904] Trial 65 finished with value: 0.8038647342995169 and parameters: {'C': 0.6531461531836629, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:42,061] Trial 66 finished with value: 0.8038647342995169 and parameters: {'C': 0.5625322782976385, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:42,231] Trial 67 finished with value: 0.8038647342995169 and parameters: {'C': 0.7956132568012575, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:42,387] Trial 68 finished with value: 0.8038647342995169 and parameters: {'C': 0.21078325502716916, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:42,549] Trial 69 finished with value: 0.8038647342995169 and parameters: {'C': 0.8828727159238862, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:42,712] Trial 70 finished with value: 0.8038647342995169 and parameters: {'C': 0.6025365381134086, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:42,864] Trial 71 finished with value: 0.8038647342995169 and parameters: {'C': 0.6782113641542175, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:43,031] Trial 72 finished with value: 0.8038647342995169 and parameters: {'C': 0.702463312735479, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:43,200] Trial 73 finished with value: 0.8038647342995169 and parameters: {'C': 0.7542695889776635, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:43,354] Trial 74 finished with value: 0.8038647342995169 and parameters: {'C': 0.8194563922146728, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:43,508] Trial 75 finished with value: 0.8038647342995169 and parameters: {'C': 0.5451713307998313, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:43,662] Trial 76 finished with value: 0.8038647342995169 and parameters: {'C': 0.7328138654081024, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:43,832] Trial 77 finished with value: 0.8038647342995169 and parameters: {'C': 0.7921833867274597, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:43,995] Trial 78 finished with value: 0.8038647342995169 and parameters: {'C': 0.6440621390065766, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:44,149] Trial 79 finished with value: 0.8038647342995169 and parameters: {'C': 0.4967875171932618, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:44,305] Trial 80 finished with value: 0.8038647342995169 and parameters: {'C': 0.9210921388345853, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:44,447] Trial 81 finished with value: 0.8038647342995169 and parameters: {'C': 0.5877761440115407, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:44,616] Trial 82 finished with value: 0.8038647342995169 and parameters: {'C': 0.666109557799963, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:44,780] Trial 83 finished with value: 0.8038647342995169 and parameters: {'C': 0.33475091577454963, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:44,969] Trial 84 finished with value: 0.8038647342995169 and parameters: {'C': 0.4395469228122368, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:45,160] Trial 85 finished with value: 0.8038647342995169 and parameters: {'C': 0.628106082210789, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:45,353] Trial 86 finished with value: 0.8038647342995169 and parameters: {'C': 0.6945499319335918, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:45,535] Trial 87 finished with value: 0.8038647342995169 and parameters: {'C': 0.38906734699578427, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:45,692] Trial 88 finished with value: 0.8038647342995169 and parameters: {'C': 0.29609774509544695, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:45,854] Trial 89 finished with value: 0.8038647342995169 and parameters: {'C': 0.7709634300004098, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:46,014] Trial 90 finished with value: 0.8038647342995169 and parameters: {'C': 0.11394222681949745, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:46,171] Trial 91 finished with value: 0.8038647342995169 and parameters: {'C': 0.7331170066545766, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:46,352] Trial 92 finished with value: 0.8038647342995169 and parameters: {'C': 0.8347313194662153, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:46,511] Trial 93 finished with value: 0.8038647342995169 and parameters: {'C': 0.7402654871208685, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:46,672] Trial 94 finished with value: 0.8038647342995169 and parameters: {'C': 0.6620492254185587, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:46,833] Trial 95 finished with value: 0.8038647342995169 and parameters: {'C': 0.7132027810103634, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:46,986] Trial 96 finished with value: 0.8038647342995169 and parameters: {'C': 0.5845916228376512, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:47,160] Trial 97 finished with value: 0.8038647342995169 and parameters: {'C': 0.6297217289085272, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:47,302] Trial 98 finished with value: 0.8038647342995169 and parameters: {'C': 0.682539715161432, 'Class_weight': None}. Best is trial 0 with value: 0.8038647342995169.
[I 2026-05-27 19:18:47,476] Trial 99 finished with value: 0.8038647342995169 and parameters: {'C': 0.5327527406542396, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8038647342995169.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
0,0,0.803865,2026-05-27 19:18:30.546431,2026-05-27 19:18:30.699985,0 days 00:00:00.153554,0.512339,None,COMPLETE
1,1,0.803865,2026-05-27 19:18:30.699985,2026-05-27 19:18:30.853027,0 days 00:00:00.153042,0.326524,None,COMPLETE
2,2,0.803865,2026-05-27 19:18:30.853027,2026-05-27 19:18:31.001247,0 days 00:00:00.148220,0.798239,balanced,COMPLETE
3,3,0.803865,2026-05-27 19:18:31.001247,2026-05-27 19:18:31.155919,0 days 00:00:00.154672,0.633450,balanced,COMPLETE
4,4,0.803865,2026-05-27 19:18:31.156488,2026-05-27 19:18:31.306927,0 days 00:00:00.150439,0.658067,None,COMPLETE

In [131]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        class_weight=class_weight,
        C=c,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

log_reg_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_log_reg_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_log_reg_unscaled_f1_optuna_results)

[I 2026-05-27 19:18:47,508] A new study created in memory with name: no-name-96110a97-bfa9-4bb2-b0da-d13b6f351a38
[I 2026-05-27 19:18:47,673] Trial 0 finished with value: 0.5420800717047658 and parameters: {'C': 0.2444207789555405, 'Class_weight': None}. Best is trial 0 with value: 0.5420800717047658.
[I 2026-05-27 19:18:47,832] Trial 1 finished with value: 0.5421129799729683 and parameters: {'C': 0.6852082049021077, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:48,032] Trial 2 finished with value: 0.5421129799729683 and parameters: {'C': 0.4576910743595539, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:48,196] Trial 3 finished with value: 0.5421129799729683 and parameters: {'C': 0.6338126414247635, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:48,354] Trial 4 finished with value: 0.5420800717047658 and parameters: {'C': 0.5946458636296627, 'Class_weight': None}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:48,522] Trial 5 finished with value: 0.5420800717047658 and parameters: {'C': 0.7033380782674038, 'Class_weight': None}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:48,692] Trial 6 finished with value: 0.5421129799729683 and parameters: {'C': 0.08819092463552271, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:48,853] Trial 7 finished with value: 0.5420800717047658 and parameters: {'C': 0.8900179268090904, 'Class_weight': None}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:49,071] Trial 8 finished with value: 0.5421129799729683 and parameters: {'C': 0.7899325866274236, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:49,255] Trial 9 finished with value: 0.5421129799729683 and parameters: {'C': 0.206360868544376, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:49,450] Trial 10 finished with value: 0.5421129799729683 and parameters: {'C': 0.43758775570732433, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:49,654] Trial 11 finished with value: 0.5421129799729683 and parameters: {'C': 0.4090693743635469, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:49,852] Trial 12 finished with value: 0.5421129799729683 and parameters: {'C': 0.9777926241907289, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:50,034] Trial 13 finished with value: 0.5421129799729683 and parameters: {'C': 0.500378230574303, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:50,234] Trial 14 finished with value: 0.5421129799729683 and parameters: {'C': 0.35252049224121496, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:50,411] Trial 15 finished with value: 0.5421129799729683 and parameters: {'C': 0.7552102556746368, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:50,578] Trial 16 finished with value: 0.5421129799729683 and parameters: {'C': 0.5813337824147993, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:50,737] Trial 17 finished with value: 0.5421129799729683 and parameters: {'C': 0.336937745798857, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:50,906] Trial 18 finished with value: 0.5420800717047658 and parameters: {'C': 0.03840181129701292, 'Class_weight': None}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:51,061] Trial 19 finished with value: 0.5421129799729683 and parameters: {'C': 0.8373026360921372, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:51,201] Trial 20 finished with value: 0.5421129799729683 and parameters: {'C': 0.6704977415864518, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:51,368] Trial 21 finished with value: 0.5421129799729683 and parameters: {'C': 0.5962571540326937, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:51,536] Trial 22 finished with value: 0.5421129799729683 and parameters: {'C': 0.527732505590697, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:51,737] Trial 23 finished with value: 0.5421129799729683 and parameters: {'C': 0.664680450227377, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:51,930] Trial 24 finished with value: 0.5421129799729683 and parameters: {'C': 0.48628350088645006, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:52,096] Trial 25 finished with value: 0.5421129799729683 and parameters: {'C': 0.7205351356609142, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:52,247] Trial 26 finished with value: 0.5420800717047658 and parameters: {'C': 0.8791367472444596, 'Class_weight': None}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:52,404] Trial 27 finished with value: 0.5421129799729683 and parameters: {'C': 0.6342032055242668, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:52,552] Trial 28 finished with value: 0.5421129799729683 and parameters: {'C': 0.30789365688218207, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:52,709] Trial 29 finished with value: 0.5420800717047658 and parameters: {'C': 0.536141524396598, 'Class_weight': None}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:52,869] Trial 30 finished with value: 0.5421129799729683 and parameters: {'C': 0.23613866889296653, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:53,025] Trial 31 finished with value: 0.5421129799729683 and parameters: {'C': 0.045224969173613516, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:53,179] Trial 32 finished with value: 0.5421129799729683 and parameters: {'C': 0.1851931179772381, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:53,353] Trial 33 finished with value: 0.5421129799729683 and parameters: {'C': 0.16211954952342505, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:53,511] Trial 34 finished with value: 0.5420800717047658 and parameters: {'C': 0.12566313556234032, 'Class_weight': None}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:53,677] Trial 35 finished with value: 0.5421129799729683 and parameters: {'C': 0.7981785514589805, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:53,871] Trial 36 finished with value: 0.5420800717047658 and parameters: {'C': 0.09851258424529051, 'Class_weight': None}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:54,040] Trial 37 finished with value: 0.5421129799729683 and parameters: {'C': 0.9592451803256969, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:54,201] Trial 38 finished with value: 0.5421129799729683 and parameters: {'C': 0.4062428389354582, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:54,367] Trial 39 finished with value: 0.5421129799729683 and parameters: {'C': 0.27520167828336517, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:54,545] Trial 40 finished with value: 0.5420800717047658 and parameters: {'C': 0.7086482096483192, 'Class_weight': None}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:54,708] Trial 41 finished with value: 0.5421129799729683 and parameters: {'C': 0.751332446595357, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:54,855] Trial 42 finished with value: 0.5421129799729683 and parameters: {'C': 0.797048633222639, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:54,998] Trial 43 finished with value: 0.5421129799729683 and parameters: {'C': 0.5843673858906981, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:55,151] Trial 44 finished with value: 0.5421129799729683 and parameters: {'C': 0.912059938405194, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:55,324] Trial 45 finished with value: 0.5421129799729683 and parameters: {'C': 0.45669332227363746, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:55,477] Trial 46 finished with value: 0.5421129799729683 and parameters: {'C': 0.6378085281528189, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:55,640] Trial 47 finished with value: 0.5421129799729683 and parameters: {'C': 0.8140670183470413, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:55,804] Trial 48 finished with value: 0.5421129799729683 and parameters: {'C': 0.7532052031143935, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:56,003] Trial 49 finished with value: 0.5421129799729683 and parameters: {'C': 0.4012678216132797, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:56,181] Trial 50 finished with value: 0.5421129799729683 and parameters: {'C': 0.006747522071679571, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:56,373] Trial 51 finished with value: 0.5421129799729683 and parameters: {'C': 0.08727765181680794, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:56,547] Trial 52 finished with value: 0.5421129799729683 and parameters: {'C': 0.8574402929071328, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:56,708] Trial 53 finished with value: 0.5421129799729683 and parameters: {'C': 0.17877967603643452, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:56,912] Trial 54 finished with value: 0.5421129799729683 and parameters: {'C': 0.21604393714774484, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:57,095] Trial 55 finished with value: 0.5421129799729683 and parameters: {'C': 0.660069922064619, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:57,308] Trial 56 finished with value: 0.5421129799729683 and parameters: {'C': 0.5986365582678729, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:57,476] Trial 57 finished with value: 0.5420800717047658 and parameters: {'C': 0.5382410751214487, 'Class_weight': None}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:57,635] Trial 58 finished with value: 0.5421129799729683 and parameters: {'C': 0.699633830770911, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:57,813] Trial 59 finished with value: 0.5421129799729683 and parameters: {'C': 0.2739373491104913, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:57,964] Trial 60 finished with value: 0.5421129799729683 and parameters: {'C': 0.3334544317177944, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:58,128] Trial 61 finished with value: 0.5421129799729683 and parameters: {'C': 0.4395252963837281, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:58,309] Trial 62 finished with value: 0.5421129799729683 and parameters: {'C': 0.3649744075790859, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:58,476] Trial 63 finished with value: 0.5421129799729683 and parameters: {'C': 0.49149136311747854, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:58,629] Trial 64 finished with value: 0.5421129799729683 and parameters: {'C': 0.5406090515570089, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:58,803] Trial 65 finished with value: 0.5421129799729683 and parameters: {'C': 0.376373559289675, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:58,997] Trial 66 finished with value: 0.5421129799729683 and parameters: {'C': 0.4505677585316698, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.5421129799729683.
[I 2026-05-27 19:18:59,179] Trial 67 finished with value: 0.5435548496501321 and parameters: {'C': 0.6242956129565066, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:18:59,337] Trial 68 finished with value: 0.5421212538378974 and parameters: {'C': 0.6772117795949696, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:18:59,499] Trial 69 finished with value: 0.5420800717047658 and parameters: {'C': 0.6253615735518807, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:18:59,677] Trial 70 finished with value: 0.5420800717047658 and parameters: {'C': 0.7301358588622776, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:18:59,853] Trial 71 finished with value: 0.5420800717047658 and parameters: {'C': 0.7744015504733032, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:00,029] Trial 72 finished with value: 0.5420800717047658 and parameters: {'C': 0.6834274055285243, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:00,230] Trial 73 finished with value: 0.5420800717047658 and parameters: {'C': 0.6187229465426952, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:00,397] Trial 74 finished with value: 0.5420800717047658 and parameters: {'C': 0.5673305934320184, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:00,566] Trial 75 finished with value: 0.5420800717047658 and parameters: {'C': 0.6563615173529713, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:00,772] Trial 76 finished with value: 0.5421295465498993 and parameters: {'C': 0.06909358647256567, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:00,952] Trial 77 finished with value: 0.5420800717047658 and parameters: {'C': 0.06177951477727756, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:01,115] Trial 78 finished with value: 0.5420800717047658 and parameters: {'C': 0.8263685664918948, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:01,285] Trial 79 finished with value: 0.5420800717047658 and parameters: {'C': 0.7335830218367145, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:01,454] Trial 80 finished with value: 0.5420800717047658 and parameters: {'C': 0.9271777006335347, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:01,617] Trial 81 finished with value: 0.5420555852819773 and parameters: {'C': 0.12307682530181588, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:01,768] Trial 82 finished with value: 0.5420800717047658 and parameters: {'C': 0.1270196834799889, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:01,917] Trial 83 finished with value: 0.5420800717047658 and parameters: {'C': 0.015676746380137517, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:02,069] Trial 84 finished with value: 0.5420800717047658 and parameters: {'C': 0.09697490672411214, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:02,254] Trial 85 finished with value: 0.5421129799729683 and parameters: {'C': 0.0694757951022279, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:02,404] Trial 86 finished with value: 0.5421129799729683 and parameters: {'C': 0.15439197449948913, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:02,556] Trial 87 finished with value: 0.5420800717047658 and parameters: {'C': 0.7788712206978001, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:02,714] Trial 88 finished with value: 0.5421129799729683 and parameters: {'C': 0.6832591162149985, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:02,870] Trial 89 finished with value: 0.5421129799729683 and parameters: {'C': 0.563901698079632, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:03,029] Trial 90 finished with value: 0.5421129799729683 and parameters: {'C': 0.03563063818104346, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:03,183] Trial 91 finished with value: 0.5421129799729683 and parameters: {'C': 0.42814339622494263, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:03,358] Trial 92 finished with value: 0.5421129799729683 and parameters: {'C': 0.5104023412835977, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:03,517] Trial 93 finished with value: 0.5421129799729683 and parameters: {'C': 0.6129389728553764, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:03,685] Trial 94 finished with value: 0.5421129799729683 and parameters: {'C': 0.20729073244093643, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:03,839] Trial 95 finished with value: 0.5421129799729683 and parameters: {'C': 0.4773373640631351, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:04,039] Trial 96 finished with value: 0.5421129799729683 and parameters: {'C': 0.2711803737103273, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:04,210] Trial 97 finished with value: 0.5421129799729683 and parameters: {'C': 0.6513248123917148, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:04,384] Trial 98 finished with value: 0.5420800717047658 and parameters: {'C': 0.6993978233169718, 'Class_weight': None}. Best is trial 67 with value: 0.5435548496501321.
[I 2026-05-27 19:19:04,558] Trial 99 finished with value: 0.5421129799729683 and parameters: {'C': 0.8486542633249617, 'Class_weight': 'balanced'}. Best is trial 67 with value: 0.5435548496501321.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
67,67,0.543555,2026-05-27 19:18:58.997328,2026-05-27 19:18:59.179551,0 days 00:00:00.182223,0.624296,None,COMPLETE
76,76,0.542130,2026-05-27 19:19:00.566622,2026-05-27 19:19:00.772235,0 days 00:00:00.205613,0.069094,None,COMPLETE
68,68,0.542121,2026-05-27 19:18:59.180551,2026-05-27 19:18:59.337046,0 days 00:00:00.156495,0.677212,None,COMPLETE
1,1,0.542113,2026-05-27 19:18:47.674277,2026-05-27 19:18:47.832973,0 days 00:00:00.158696,0.685208,balanced,COMPLETE
35,35,0.542113,2026-05-27 19:18:53.511332,2026-05-27 19:18:53.677268,0 days 00:00:00.165936,0.798179,balanced,COMPLETE

#### Tryout best params

In [132]:
log_reg_recall_optimized_model = LogisticRegression(C=0.769946, class_weight='balanced', random_state=random_state)
log_reg_recall_optimized_model.fit(X_train, y_train)
y_pred = log_reg_recall_optimized_model.predict(X_test)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Logistic Regression (Recall Optimized)')

              precision    recall  f1-score   support

           0       1.00      0.01      0.02      1036
           1       0.50      1.00      0.67      1035

    accuracy                           0.50      2071
   macro avg       0.75      0.50      0.34      2071
weighted avg       0.75      0.50      0.34      2071

In [133]:
log_reg_f1_optimized_model = LogisticRegression(C=0.315005, class_weight='balanced', random_state=random_state)
log_reg_f1_optimized_model.fit(X_train, y_train)
y_pred = log_reg_f1_optimized_model.predict(X_test)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Logistic Regression (F1 Optimized)')

              precision    recall  f1-score   support

           0       1.00      0.01      0.02      1036
           1       0.50      1.00      0.67      1035

    accuracy                           0.50      2071
   macro avg       0.75      0.50      0.34      2071
weighted avg       0.75      0.50      0.34      2071

### Ridge

In [134]:
# We can tune alpha and class weight

#### Recall optimized

In [135]:
def objective(trial):
    alpha = trial.suggest_float("alpha", 0.001, 1.0)
    class_weight = trial.suggest_categorical("class_weight", ['balanced', None])
    
    model = RidgeClassifier(
        class_weight=class_weight,
        alpha=alpha,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

ridge_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_ridge_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_ridge_unscaled_recall_optuna_results)

[I 2026-05-27 19:19:04,830] A new study created in memory with name: no-name-4e527e6a-e1fc-44a8-a2af-22e2ec656a87
[I 2026-05-27 19:19:04,967] Trial 0 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9160121799545452, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:05,087] Trial 1 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5774180563193767, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:05,209] Trial 2 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.05390141718460329, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:05,316] Trial 3 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.25242539586269463, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:05,426] Trial 4 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.2158633609076622, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:05,552] Trial 5 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.239000548902838, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:05,672] Trial 6 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6692382532262048, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:05,783] Trial 7 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5491593974127598, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:05,912] Trial 8 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.03943304573219897, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:06,063] Trial 9 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.012253880639970124, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:06,199] Trial 10 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9903734610448494, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:06,328] Trial 11 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8862111078890914, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:06,440] Trial 12 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7450602277415767, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:06,552] Trial 13 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4639903888532614, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:06,688] Trial 14 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7781704107987919, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:06,806] Trial 15 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5013411645415017, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:06,937] Trial 16 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6445738278155699, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:07,087] Trial 17 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.3800299215043625, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:07,227] Trial 18 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9815378097587442, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:07,376] Trial 19 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.36578056052385266, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:07,502] Trial 20 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8597285602678477, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:07,629] Trial 21 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6081822850508629, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:07,753] Trial 22 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.16661307094287758, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:07,871] Trial 23 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.36321723989402654, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:08,000] Trial 24 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.11659624149255499, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:08,128] Trial 25 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7513613114975836, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:08,282] Trial 26 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8628022506673352, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:08,401] Trial 27 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.3045145189911053, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:08,529] Trial 28 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.45659250817549923, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:08,672] Trial 29 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5775132248708567, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:08,828] Trial 30 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9059929707013812, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:08,938] Trial 31 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.10883394548218209, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:09,056] Trial 32 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.23933252580460243, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:09,177] Trial 33 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.2693239963510423, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:09,360] Trial 34 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.18718337294454673, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:09,479] Trial 35 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.0821846186221068, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:09,585] Trial 36 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.1550465081414797, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:09,709] Trial 37 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.0038229751299018178, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:09,828] Trial 38 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.2979259088269295, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:09,947] Trial 39 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6728818016291656, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:10,080] Trial 40 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4205115791693681, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:10,211] Trial 41 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.05800814485279979, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:10,344] Trial 42 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.1978174562281578, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:10,479] Trial 43 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.2275439191292929, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:10,596] Trial 44 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.518796748533716, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:10,714] Trial 45 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6979610895653158, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:10,834] Trial 46 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.33546200790013, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:10,957] Trial 47 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.12915279458725604, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:11,072] Trial 48 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.06479102564613154, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:11,191] Trial 49 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9356439122279465, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:11,304] Trial 50 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4109201882967215, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:11,417] Trial 51 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.813222608311204, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:11,550] Trial 52 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.23390712586071838, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:11,657] Trial 53 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.2827199422917227, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:11,776] Trial 54 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.029319476492558644, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:11,888] Trial 55 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.32929583974689086, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:12,011] Trial 56 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5480493128765175, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:12,135] Trial 57 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.14350397667057702, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:12,256] Trial 58 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4633200587649124, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:12,375] Trial 59 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6106520691745733, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:12,516] Trial 60 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.0879406980704838, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:12,632] Trial 61 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6371125268892565, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:12,744] Trial 62 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8122275452439566, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:12,857] Trial 63 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6945524403393017, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:12,975] Trial 64 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9983468213222968, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:13,088] Trial 65 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5011363820442232, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:13,207] Trial 66 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5599543254996968, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:13,330] Trial 67 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.19510920718793845, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:13,457] Trial 68 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.41944584522176664, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:13,575] Trial 69 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9497930603528736, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:13,688] Trial 70 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7636161744041376, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:13,806] Trial 71 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6142831952516496, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:13,931] Trial 72 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5363196788391766, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:14,058] Trial 73 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.25214594739586416, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:14,177] Trial 74 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5815511616457603, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:14,304] Trial 75 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4836737893229075, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:14,433] Trial 76 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.72169950358317, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:14,547] Trial 77 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6539021053854484, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:14,715] Trial 78 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.38742491983237903, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:14,833] Trial 79 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.33416230063947616, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:14,947] Trial 80 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.21010167199016244, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:15,065] Trial 81 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.03119149190040392, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:15,176] Trial 82 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.1750039387205624, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:15,281] Trial 83 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.0999930575084009, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:15,392] Trial 84 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.0445716568369191, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:15,509] Trial 85 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.13522935255810237, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:15,633] Trial 86 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4429544466882328, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:15,768] Trial 87 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.006235814988101017, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:15,880] Trial 88 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5808660187814015, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:15,991] Trial 89 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8821078521157277, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:16,153] Trial 90 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.2757548575708418, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:16,303] Trial 91 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.07410105207906698, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:16,418] Trial 92 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.0015912986835433657, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:16,555] Trial 93 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.11552569335806494, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:16,682] Trial 94 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.048241037981414936, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:16,801] Trial 95 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.15678989678732264, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:16,930] Trial 96 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5191904924716437, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:17,044] Trial 97 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.804389767407639, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:17,195] Trial 98 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.025117157318824496, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-05-27 19:19:17,331] Trial 99 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.09320612650806723, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.

,number,value,datetime_start,datetime_complete,duration,params_alpha,params_class_weight,state
0,0,0.859732,2026-05-27 19:19:04.831748,2026-05-27 19:19:04.967681,0 days 00:00:00.135933,0.916012,balanced,COMPLETE
1,1,0.859732,2026-05-27 19:19:04.967681,2026-05-27 19:19:05.087496,0 days 00:00:00.119815,0.577418,balanced,COMPLETE
2,2,0.859732,2026-05-27 19:19:05.087496,2026-05-27 19:19:05.209322,0 days 00:00:00.121826,0.053901,balanced,COMPLETE
3,3,0.859732,2026-05-27 19:19:05.209322,2026-05-27 19:19:05.316473,0 days 00:00:00.107151,0.252425,balanced,COMPLETE
4,4,0.859732,2026-05-27 19:19:05.316473,2026-05-27 19:19:05.426937,0 days 00:00:00.110464,0.215863,None,COMPLETE

#### Tryout best params

In [136]:
ridge_recall_optimized_model = RidgeClassifier(alpha=0.039558, class_weight='balanced', random_state=random_state)
ridge_recall_optimized_model.fit(X_train, y_train)
y_pred = ridge_recall_optimized_model.predict(X_test)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Ridge Classifier (Recall Optimized)')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_ridge.py:213: LinAlgWarning: Ill-conditioned matrix (rcond=1.53123e-24): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

#### F1 optimized

In [137]:
def objective(trial):
    alpha = trial.suggest_float("alpha", 0.001, 1.0)
    class_weight = trial.suggest_categorical("class_weight", ['balanced', None])
    
    model = RidgeClassifier(
        class_weight=class_weight,
        alpha=alpha,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

ridge_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_ridge_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_ridge_unscaled_f1_optuna_results)

[I 2026-05-27 19:19:17,382] A new study created in memory with name: no-name-a33ed796-ff6d-4668-b1ab-eceffc6e658f
[I 2026-05-27 19:19:17,507] Trial 0 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9025321723490667, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:17,628] Trial 1 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7712048527664856, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:17,749] Trial 2 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3289018708241408, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:17,901] Trial 3 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4290513421772031, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:18,019] Trial 4 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5176451369780092, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:18,132] Trial 5 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9546584982109073, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:18,252] Trial 6 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.16567768922290224, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:18,386] Trial 7 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6219330695443213, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:18,531] Trial 8 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7682979356943886, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:18,653] Trial 9 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7692599894368198, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:18,771] Trial 10 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.006615960818397104, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:18,887] Trial 11 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.986242546272506, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:19,004] Trial 12 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8134610106283324, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:19,130] Trial 13 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6683515296761522, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:19,249] Trial 14 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8798331776223273, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:19,395] Trial 15 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6410433355234106, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:19,511] Trial 16 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8754298443854148, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:19,645] Trial 17 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5266186600732979, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:19,763] Trial 18 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7204623040050058, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:19,890] Trial 19 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.894640292684262, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:20,035] Trial 20 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.30749089674469376, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:20,156] Trial 21 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3612989409898692, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:20,283] Trial 22 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.1881131601493495, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:20,413] Trial 23 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.17988145733650795, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:20,556] Trial 24 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3077310068812028, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:20,682] Trial 25 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5661178140788697, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:20,806] Trial 26 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4400343849089032, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:20,933] Trial 27 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.07671656003732302, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:21,067] Trial 28 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8250118077370789, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:21,196] Trial 29 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.42448587846549013, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:21,323] Trial 30 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7165667835876377, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:21,450] Trial 31 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4562036337879245, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:21,590] Trial 32 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3568689437354515, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:21,708] Trial 33 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5327694546487324, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:21,820] Trial 34 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.2501445031162992, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:21,933] Trial 35 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9463100165447598, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:22,059] Trial 36 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6042950199071528, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:22,176] Trial 37 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4745068465885926, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:22,297] Trial 38 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.23733841354935142, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:22,410] Trial 39 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3992195075867948, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:22,532] Trial 40 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9826928176639306, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:22,651] Trial 41 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7907217254276324, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:22,776] Trial 42 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4974231172304813, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:22,898] Trial 43 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9299913701030555, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:23,020] Trial 44 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7082826727892052, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:23,145] Trial 45 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5789274586331514, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:23,267] Trial 46 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8328900759241482, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:23,377] Trial 47 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6693647348432143, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:23,497] Trial 48 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.31570884091889306, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:23,620] Trial 49 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.38418292359688483, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:23,730] Trial 50 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7541764514014396, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:23,851] Trial 51 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.863143919557001, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:23,973] Trial 52 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9276490832213852, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:24,096] Trial 53 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9888997582079878, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:24,216] Trial 54 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9080868621304736, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:24,339] Trial 55 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8523257430011467, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:24,463] Trial 56 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.252011055665723, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:24,573] Trial 57 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.08899348903294657, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:24,683] Trial 58 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9566641801150685, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:24,792] Trial 59 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7665410257764195, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:24,903] Trial 60 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5294185247768229, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:25,018] Trial 61 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.12798898260768102, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:25,145] Trial 62 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.276927533979839, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:25,271] Trial 63 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.20000417304777113, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:25,406] Trial 64 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.024441192472809847, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:25,524] Trial 65 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.32972028399831765, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:25,649] Trial 66 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.40809893418689763, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:25,771] Trial 67 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.1532953111077517, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:25,895] Trial 68 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.36324015385037056, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:26,017] Trial 69 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8999620228853178, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:26,139] Trial 70 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6650047460993365, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:26,265] Trial 71 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4414183818080071, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:26,406] Trial 72 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5033697375957716, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:26,534] Trial 73 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6250623820129528, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:26,655] Trial 74 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5767212223545786, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:26,784] Trial 75 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.48617946923830535, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:26,933] Trial 76 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.806336978743928, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:27,112] Trial 77 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7402652965431067, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:27,268] Trial 78 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.560876311294543, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:27,423] Trial 79 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7890896747234186, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:27,564] Trial 80 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6925860611564224, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:27,689] Trial 81 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6129851657166311, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:27,800] Trial 82 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8798785760323611, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:27,918] Trial 83 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9635545828497385, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:28,051] Trial 84 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5448276075341068, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:28,167] Trial 85 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8366123825635797, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:28,272] Trial 86 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4602973717257758, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:28,391] Trial 87 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7352044523440446, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:28,518] Trial 88 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5118661224398935, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:28,640] Trial 89 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4286610889934255, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:28,761] Trial 90 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5931567948712282, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:28,870] Trial 91 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6567374975953533, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:28,997] Trial 92 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.788036790479092, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:29,118] Trial 93 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9269027150200013, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:29,241] Trial 94 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7084769862456225, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:29,353] Trial 95 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6892004831340434, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:29,480] Trial 96 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7705189275603483, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:29,607] Trial 97 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.20629980452696633, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:29,751] Trial 98 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8165841165446052, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-05-27 19:19:29,913] Trial 99 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.2922783435210202, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.

,number,value,datetime_start,datetime_complete,duration,params_alpha,params_class_weight,state
0,0,0.876967,2026-05-27 19:19:17.382329,2026-05-27 19:19:17.507709,0 days 00:00:00.125380,0.902532,None,COMPLETE
1,1,0.876967,2026-05-27 19:19:17.507709,2026-05-27 19:19:17.628886,0 days 00:00:00.121177,0.771205,None,COMPLETE
2,2,0.876967,2026-05-27 19:19:17.628886,2026-05-27 19:19:17.749825,0 days 00:00:00.120939,0.328902,balanced,COMPLETE
3,3,0.876967,2026-05-27 19:19:17.749825,2026-05-27 19:19:17.901084,0 days 00:00:00.151259,0.429051,None,COMPLETE
4,4,0.876967,2026-05-27 19:19:17.901084,2026-05-27 19:19:18.019480,0 days 00:00:00.118396,0.517645,balanced,COMPLETE

#### Tryout best params

In [138]:
ridge_f1_optimized_model = RidgeClassifier(alpha=0.364826, class_weight='balanced', random_state=random_state)
ridge_f1_optimized_model.fit(X_train, y_train)
y_pred = ridge_f1_optimized_model.predict(X_test)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Ridge Classifier (F1 Optimized)')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_ridge.py:213: LinAlgWarning: Ill-conditioned matrix (rcond=1.20156e-23): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

### Lasso Logistic Regression

In [ ]:
# We can only tune the C (float) and Class_weight to tryout balanced.

In [ ]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        penalty='l1', # Lasso
        class_weight=class_weight,
        C=c,
        solver='liblinear',
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=15, n_jobs=-1)

lasso_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_lasso_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_lasso_unscaled_recall_optuna_results)

[I 2026-05-27 19:29:30,572] A new study created in memory with name: no-name-7bb9c622-251d-46b7-b9ce-0c9386097b97

In [ ]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        penalty='l1', # Lasso
        class_weight=class_weight,
        C=c,
        solver='liblinear',
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=15)

lasso_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_lasso_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_lasso_unscaled_f1_optuna_results)

[I 2026-05-27 19:24:07,766] A new study created in memory with name: no-name-557a3f05-bb26-47bc-9871-68116dfe3509
[I 2026-05-27 19:24:08,373] Trial 0 finished with value: 0.04726049275011109 and parameters: {'C': 0.4960233912574134, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:08,969] Trial 1 finished with value: 0.04301554501010194 and parameters: {'C': 0.5885935362159502, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:09,562] Trial 2 finished with value: 0.04301554501010194 and parameters: {'C': 0.7014105884765477, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:10,148] Trial 3 finished with value: 0.04726049275011109 and parameters: {'C': 0.1249700890598025, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:10,740] Trial 4 finished with value: 0.04726049275011109 and parameters: {'C': 0.4199293721996046, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:11,286] Trial 5 finished with value: 0.04726049275011109 and parameters: {'C': 0.027059879613962695, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:11,935] Trial 6 finished with value: 0.04301554501010194 and parameters: {'C': 0.25429417861422554, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:12,536] Trial 7 finished with value: 0.04301554501010194 and parameters: {'C': 0.9696702873645049, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:13,120] Trial 8 finished with value: 0.04301554501010194 and parameters: {'C': 0.270733905333096, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:13,733] Trial 9 finished with value: 0.04301554501010194 and parameters: {'C': 0.37797161833776277, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:14,338] Trial 10 finished with value: 0.04726049275011109 and parameters: {'C': 0.7900672234886608, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:14,928] Trial 11 finished with value: 0.04726049275011109 and parameters: {'C': 0.08769356078750162, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:15,538] Trial 12 finished with value: 0.04726049275011109 and parameters: {'C': 0.21458313361461318, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:16,138] Trial 13 finished with value: 0.04726049275011109 and parameters: {'C': 0.5592977076685272, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:16,750] Trial 14 finished with value: 0.04726049275011109 and parameters: {'C': 0.161459837964953, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:17,336] Trial 15 finished with value: 0.04726049275011109 and parameters: {'C': 0.40438817907156843, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:17,961] Trial 16 finished with value: 0.04726049275011109 and parameters: {'C': 0.9986000365494319, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:18,594] Trial 17 finished with value: 0.04726049275011109 and parameters: {'C': 0.7347548702528648, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:19,208] Trial 18 finished with value: 0.04726049275011109 and parameters: {'C': 0.5128269633876756, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:19,816] Trial 19 finished with value: 0.04726049275011109 and parameters: {'C': 0.8296537753147553, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:20,403] Trial 20 finished with value: 0.04726049275011109 and parameters: {'C': 0.31428158421759433, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:20,995] Trial 21 finished with value: 0.04726049275011109 and parameters: {'C': 0.4191765067549782, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:21,608] Trial 22 finished with value: 0.04726049275011109 and parameters: {'C': 0.6324238342796349, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:22,232] Trial 23 finished with value: 0.04726049275011109 and parameters: {'C': 0.4594877589497888, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:22,810] Trial 24 finished with value: 0.04726049275011109 and parameters: {'C': 0.3400797102187203, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:23,407] Trial 25 finished with value: 0.04726049275011109 and parameters: {'C': 0.15578180417323662, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:24,037] Trial 26 finished with value: 0.04726049275011109 and parameters: {'C': 0.49960417888707315, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:24,613] Trial 27 finished with value: 0.04726049275011109 and parameters: {'C': 0.021069998804254864, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:25,218] Trial 28 finished with value: 0.04726049275011109 and parameters: {'C': 0.6512923065343641, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:25,819] Trial 29 finished with value: 0.04301554501010194 and parameters: {'C': 0.5752281542780064, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:26,453] Trial 30 finished with value: 0.04726049275011109 and parameters: {'C': 0.12792837301677384, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:27,005] Trial 31 finished with value: 0.04726049275011109 and parameters: {'C': 0.0034193889349111994, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:27,602] Trial 32 finished with value: 0.04726049275011109 and parameters: {'C': 0.0711549340498702, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:28,197] Trial 33 finished with value: 0.04726049275011109 and parameters: {'C': 0.2083181764479001, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:28,804] Trial 34 finished with value: 0.04301554501010194 and parameters: {'C': 0.07105316977911452, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:29,400] Trial 35 finished with value: 0.04301554501010194 and parameters: {'C': 0.27955796242840947, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:30,014] Trial 36 finished with value: 0.04726049275011109 and parameters: {'C': 0.19954137594199672, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:30,626] Trial 37 finished with value: 0.04301554501010194 and parameters: {'C': 0.34406881350600127, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:31,224] Trial 38 finished with value: 0.04726049275011109 and parameters: {'C': 0.4511867439388787, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:31,851] Trial 39 finished with value: 0.04726049275011109 and parameters: {'C': 0.8865277335934514, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:32,459] Trial 40 finished with value: 0.04301554501010194 and parameters: {'C': 0.27938344199094856, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:33,133] Trial 41 finished with value: 0.04726049275011109 and parameters: {'C': 0.7846018345266007, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:33,769] Trial 42 finished with value: 0.04726049275011109 and parameters: {'C': 0.9263919847732606, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:34,375] Trial 43 finished with value: 0.04726049275011109 and parameters: {'C': 0.6849671912782578, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:34,969] Trial 44 finished with value: 0.04726049275011109 and parameters: {'C': 0.5437679050130393, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:35,552] Trial 45 finished with value: 0.04726049275011109 and parameters: {'C': 0.1129538468573561, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:36,178] Trial 46 finished with value: 0.04726049275011109 and parameters: {'C': 0.7143615423850507, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:36,801] Trial 47 finished with value: 0.04726049275011109 and parameters: {'C': 0.615944385947538, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:37,409] Trial 48 finished with value: 0.04726049275011109 and parameters: {'C': 0.2419788953174406, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:37,999] Trial 49 finished with value: 0.04726049275011109 and parameters: {'C': 0.7616905142419819, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:38,584] Trial 50 finished with value: 0.04726049275011109 and parameters: {'C': 0.038180744433683356, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:39,168] Trial 51 finished with value: 0.04726049275011109 and parameters: {'C': 0.07999929327131017, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:39,784] Trial 52 finished with value: 0.04726049275011109 and parameters: {'C': 0.39066041669148, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:40,387] Trial 53 finished with value: 0.04726049275011109 and parameters: {'C': 0.15384395676340024, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:40,999] Trial 54 finished with value: 0.04726049275011109 and parameters: {'C': 0.11390605892469002, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:41,587] Trial 55 finished with value: 0.04726049275011109 and parameters: {'C': 0.48859864257508256, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:42,154] Trial 56 finished with value: 0.04726049275011109 and parameters: {'C': 0.04385288935391074, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:42,736] Trial 57 finished with value: 0.04726049275011109 and parameters: {'C': 0.1922579963496241, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:43,361] Trial 58 finished with value: 0.04301554501010194 and parameters: {'C': 0.4298054243855753, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:43,954] Trial 59 finished with value: 0.04726049275011109 and parameters: {'C': 0.5982650205710214, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:44,547] Trial 60 finished with value: 0.04726049275011109 and parameters: {'C': 0.5480596115259494, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:45,128] Trial 61 finished with value: 0.04726049275011109 and parameters: {'C': 0.24611340270480672, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:45,749] Trial 62 finished with value: 0.04726049275011109 and parameters: {'C': 0.09206811527392378, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:46,364] Trial 63 finished with value: 0.04726049275011109 and parameters: {'C': 0.17158974313027173, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:46,940] Trial 64 finished with value: 0.04726049275011109 and parameters: {'C': 0.00471507475177721, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:47,547] Trial 65 finished with value: 0.04726049275011109 and parameters: {'C': 0.32176508411024046, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:48,176] Trial 66 finished with value: 0.04726049275011109 and parameters: {'C': 0.2303015683822265, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:48,767] Trial 67 finished with value: 0.04726049275011109 and parameters: {'C': 0.3717437967312046, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:49,404] Trial 68 finished with value: 0.04301554501010194 and parameters: {'C': 0.1425005757743465, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:49,969] Trial 69 finished with value: 0.04726049275011109 and parameters: {'C': 0.04114459231268611, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:50,562] Trial 70 finished with value: 0.04726049275011109 and parameters: {'C': 0.4785048547200499, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:51,133] Trial 71 finished with value: 0.04726049275011109 and parameters: {'C': 0.651624490756485, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:51,739] Trial 72 finished with value: 0.04726049275011109 and parameters: {'C': 0.8151459590355992, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:52,332] Trial 73 finished with value: 0.04726049275011109 and parameters: {'C': 0.536634455141304, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:52,948] Trial 74 finished with value: 0.04726049275011109 and parameters: {'C': 0.09106294398086867, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:53,582] Trial 75 finished with value: 0.04726049275011109 and parameters: {'C': 0.9119817468058596, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:54,196] Trial 76 finished with value: 0.04726049275011109 and parameters: {'C': 0.5749652988698991, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:54,783] Trial 77 finished with value: 0.04726049275011109 and parameters: {'C': 0.4390792007427301, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:55,379] Trial 78 finished with value: 0.04301554501010194 and parameters: {'C': 0.2940510007401558, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:56,010] Trial 79 finished with value: 0.04726049275011109 and parameters: {'C': 0.3491069383298866, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:56,597] Trial 80 finished with value: 0.04726049275011109 and parameters: {'C': 0.17866810830739277, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:57,185] Trial 81 finished with value: 0.04726049275011109 and parameters: {'C': 0.11172186495195655, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:57,799] Trial 82 finished with value: 0.04726049275011109 and parameters: {'C': 0.2159956145902115, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:58,399] Trial 83 finished with value: 0.04726049275011109 and parameters: {'C': 0.9744538514864606, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:58,994] Trial 84 finished with value: 0.04726049275011109 and parameters: {'C': 0.05768807471204582, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:24:59,610] Trial 85 finished with value: 0.04726049275011109 and parameters: {'C': 0.13335310946287512, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:00,205] Trial 86 finished with value: 0.04726049275011109 and parameters: {'C': 0.40555115892023974, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:00,789] Trial 87 finished with value: 0.04726049275011109 and parameters: {'C': 0.5243000210109071, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:01,388] Trial 88 finished with value: 0.04726049275011109 and parameters: {'C': 0.4659050737861531, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:01,981] Trial 89 finished with value: 0.04301554501010194 and parameters: {'C': 0.16330399564414022, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:02,553] Trial 90 finished with value: 0.04726049275011109 and parameters: {'C': 0.02935032677808222, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:03,149] Trial 91 finished with value: 0.04726049275011109 and parameters: {'C': 0.5104012084588871, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:03,747] Trial 92 finished with value: 0.04726049275011109 and parameters: {'C': 0.4175116797791415, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:04,349] Trial 93 finished with value: 0.04726049275011109 and parameters: {'C': 0.8527225738535149, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:04,922] Trial 94 finished with value: 0.04726049275011109 and parameters: {'C': 0.36930330591589317, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:05,501] Trial 95 finished with value: 0.04726049275011109 and parameters: {'C': 0.6733874237691072, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:06,072] Trial 96 finished with value: 0.04726049275011109 and parameters: {'C': 0.062093746958771234, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:06,667] Trial 97 finished with value: 0.04726049275011109 and parameters: {'C': 0.7283500880060659, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:07,254] Trial 98 finished with value: 0.04726049275011109 and parameters: {'C': 0.1155927627301119, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.
[I 2026-05-27 19:25:07,855] Trial 99 finished with value: 0.04726049275011109 and parameters: {'C': 0.572469344347963, 'Class_weight': None}. Best is trial 0 with value: 0.04726049275011109.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
0,0,0.04726,2026-05-27 19:24:07.768325,2026-05-27 19:24:08.373268,0 days 00:00:00.604943,0.496023,None,COMPLETE
3,3,0.04726,2026-05-27 19:24:09.562922,2026-05-27 19:24:10.148980,0 days 00:00:00.586058,0.124970,None,COMPLETE
5,5,0.04726,2026-05-27 19:24:10.740207,2026-05-27 19:24:11.286398,0 days 00:00:00.546191,0.027060,None,COMPLETE
4,4,0.04726,2026-05-27 19:24:10.148980,2026-05-27 19:24:10.740207,0 days 00:00:00.591227,0.419929,None,COMPLETE
28,28,0.04726,2026-05-27 19:24:24.614084,2026-05-27 19:24:25.218892,0 days 00:00:00.604808,0.651292,None,COMPLETE

#### Tryout best params

In [148]:
lasso_recall_optimized_model = LogisticRegression(
    penalty='l1', # Lasso
    C=0.248927, 
    class_weight=None,
    solver='saga',
    random_state=random_state
)
lasso_recall_optimized_model.fit(X_train, y_train)
y_pred = lasso_recall_optimized_model.predict(X_test)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Lasso Classifier (Recall Optimized)')

              precision    recall  f1-score   support

           0       0.50      0.94      0.65      1036
           1       0.47      0.06      0.10      1035

    accuracy                           0.50      2071
   macro avg       0.48      0.50      0.38      2071
weighted avg       0.48      0.50      0.38      2071

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [146]:
lasso_f1_optimized_model = LogisticRegression(
    penalty='l1', # Lasso
    C=0.496023, 
    class_weight=None,
    solver='saga',
    random_state=random_state
)
lasso_f1_optimized_model.fit(X_train, y_train)
y_pred = lasso_f1_optimized_model.predict(X_test)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Lasso Classifier (F1 Optimized)')

              precision    recall  f1-score   support

           0       0.50      0.94      0.65      1036
           1       0.47      0.06      0.10      1035

    accuracy                           0.50      2071
   macro avg       0.48      0.50      0.38      2071
weighted avg       0.48      0.50      0.38      2071

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

## Conclusions

In [149]:
pd.concat(classification_reports, keys=classification_report_keys)

                                                      precision    recall  \
Baseline Logistic Regression            0              1.000000  0.007722
                                        1              0.501697  1.000000
                                        accuracy       0.503621  0.503621
                                        macro avg      0.750848  0.503861
                                        weighted avg   0.750969  0.503621
Baseline Ridge Classifier               0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563
Baseline L1 (Lasso) Logistic Regression 0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563
Logistic Regression (Recall Optimized)  0              1.000000  0.007722
                                        1              0.501697  1.000000
                                        accuracy       0.503621  0.503621
                                        macro avg      0.750848  0.503861
                                        weighted avg   0.750969  0.503621
Logistic Regression (F1 Optimized)      0              1.000000  0.007722
                                        1              0.501697  1.000000
                                        accuracy       0.503621  0.503621
                                        macro avg      0.750848  0.503861
                                        weighted avg   0.750969  0.503621
Ridge Classifier (Recall Optimized)     0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563
Ridge Classifier (F1 Optimized)         0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563
Lasso Classifier (F1 Optimized)         0              0.498202  0.936293
                                        1              0.467742  0.056039
                                        accuracy       0.496379  0.496379
                                        macro avg      0.482972  0.496166
                                        weighted avg   0.482980  0.496379
Lasso Classifier (Recall Optimized)     0              0.498202  0.936293
                                        1              0.467742  0.056039
                                        accuracy       0.496379  0.496379
                                        macro avg      0.482972  0.496166
                                        weighted avg   0.482980  0.496379

                                                      f1-score      support
Baseline Logistic Regression            0             0.015326  1036.000000
                                        1             0.668173  1035.000000
                                        accuracy      0.503621     0.503621
                                        macro avg     0.341749  2071.000000
                                        weighted avg  0.341592  2071.000000
Baseline Ridge Classifier               0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000
Baseline L1 (Lasso) Logistic Regression 0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000
Logistic Regression (Recall Optimized)  0             0.015326  1036.000000
                                        1             0.668173  1035.000000
                                        accuracy      0.503621     0.503621
                                        macro avg     0.341749  2071.000000
                                        weighted avg  0.341592  2071.000000
Logistic Regression (F1 Optimized)      0             0.015326  1036.000000
                                        1             0.668173  1035.000000
                                        accuracy      0.503621     0.503621
                                        macro avg     0.341749  2071.000000
                                        weighted avg  0.341592  2071.000000
Ridge Classifier (Recall Optimized)     0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000
Ridge Classifier (F1 Optimized)         0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000
Lasso Classifier (F1 Optimized)         0             0.650352  1036.000000
                                        1             0.100086  1035.000000
                                        accuracy      0.496379     0.496379
                                        macro avg     0.375219  2071.000000
                                        weighted avg  0.375352  2071.000000
Lasso Classifier (Recall Optimized)     0             0.650352  1036.000000
                                        1             0.100086  1035.000000
                                        accuracy      0.496379     0.496379
                                        macro avg     0.375219  2071.000000
                                        weighted avg  0.375352  2071.000000

The lasso and ridge both overcome poor initial performance of the logistic regression model

The logistic reg performance could have been poor due to severe multicollinearity or imbalanced feature scaling