In [1]:
import pandas as pd
from imblearn.under_sampling import RandomUnderSampler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from collections import Counter

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## PPP

In [2]:
random_state = 42

In [3]:
classification_reports = []
classification_report_keys = []

### Data

In [4]:
# Import credit card datasaet
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/ppp_cleaned.csv')
df

,ProcessingMethod,BorrowerState,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,ServicingLenderState,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,...,MORTGAGE_INTEREST_PROCEED_pct,RENT_PROCEED_pct,REFINANCE_EIDL_PROCEED_pct,HEALTH_CARE_PROCEED_pct,DEBT_INTEREST_PROCEED_pct,PROCEED_Per_Job,Fraud,DateApproved_int,ForgivenessDate_int,LoanStatusDate_int
0,0.0,48.0,2.0,24,769358.78,769358.78,11.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,12409.01,0,1588291200,1605830400,1608249600
1,0.0,48.0,2.0,24,736927.79,736927.79,11.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,10094.90,0,1588291200,1628726400,1632787200
2,0.0,48.0,2.0,24,691355.00,691355.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9218.07,0,1588291200,1612915200,1615939200
3,0.0,48.0,2.0,24,499871.00,499871.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,23803.38,0,1588291200,1631232000,1634342400
4,0.0,48.0,2.0,24,367437.00,367437.00,37.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,14697.48,0,1588291200,1617840000,1629158400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968527,0.0,56.0,2.0,24,150000.00,150000.00,54.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10000.00,0,1585872000,1607472000,1610496000
968528,0.0,56.0,2.0,24,150000.00,150000.00,31.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3452.38,0,1586822400,1604361600,1607385600
968529,1.0,56.0,2.0,60,150000.00,150000.00,54.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,29999.40,0,1613088000,1629158400,1631664000
968530,0.0,56.0,2.0,60,150000.00,150000.00,18.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,21428.57,0,1586908800,1645574400,1646697600
968531,0.0,56.0,2.0,24,150000.00,150000.00,54.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,13636.36,0,1586390400,1632268800,1634860800

### Undersampling

In [5]:
X = df.drop(columns='Fraud')
y = df['Fraud']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(sampling_strategy=0.1, random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 968437, 1: 95})
Resampled dataset shape: Counter({0: 950, 1: 95})

### Split Data

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Models
#### (No parameter optimization, feature scaling, or cross validation)

#### Linear Regression

In [7]:
model = LogisticRegression()

In [8]:
model.fit(X_train, y_train)

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [9]:
y_pred = model.predict(X_test)

In [10]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline Logistic Regression')

              precision    recall  f1-score   support

           0       0.99      0.89      0.94       190
           1       0.45      0.89      0.60        19

    accuracy                           0.89       209
   macro avg       0.72      0.89      0.77       209
weighted avg       0.94      0.89      0.91       209

#### Ridge

In [11]:
from sklearn.linear_model import RidgeClassifier


ridge_model = RidgeClassifier(random_state=random_state)

In [12]:
ridge_model.fit(X_train, y_train)

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_ridge.py:213: LinAlgWarning: Ill-conditioned matrix (rcond=3.15646e-22): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

RidgeClassifier(random_state=42)

In [13]:
y_pred = ridge_model.predict(X_test)

In [14]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline Ridge Classifier')

              precision    recall  f1-score   support

           0       0.98      0.95      0.97       190
           1       0.62      0.79      0.70        19

    accuracy                           0.94       209
   macro avg       0.80      0.87      0.83       209
weighted avg       0.95      0.94      0.94       209

#### Lasso

In [15]:
lasso_model = LogisticRegression(penalty='l1', solver='liblinear')

In [16]:
lasso_model.fit(X_train, y_train)

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

LogisticRegression(penalty='l1', solver='liblinear')

In [17]:
y_pred = lasso_model.predict(X_test)

In [18]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline L1 (Lasso) Logistic Regression')

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       190
           1       0.70      0.74      0.72        19

    accuracy                           0.95       209
   macro avg       0.84      0.85      0.84       209
weighted avg       0.95      0.95      0.95       209

### Scaling Data

In [19]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Parameter Tuning

#### Logistic Regression

In [20]:
# We can only tune the C (float) and Class_weight to tryout balanced.

In [21]:
# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
from sklearn.model_selection import StratifiedKFold


cv = StratifiedKFold(n_splits=5)

In [22]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        class_weight=class_weight,
        C=c,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

log_reg_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_log_reg_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_log_reg_unscaled_recall_optuna_results)

[I 2026-06-24 19:23:16,086] A new study created in memory with name: no-name-f2d90437-e943-4eb1-8177-11a61af9fed8
[I 2026-06-24 19:23:17,475] Trial 0 finished with value: 0.79 and parameters: {'C': 0.8618697353185664, 'Class_weight': None}. Best is trial 0 with value: 0.79.
[I 2026-06-24 19:23:18,648] Trial 1 finished with value: 0.9225000000000001 and parameters: {'C': 0.8297147054295477, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:19,663] Trial 2 finished with value: 0.79 and parameters: {'C': 0.599220617113706, 'Class_weight': None}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,717] Trial 3 finished with value: 0.7766666666666667 and parameters: {'C': 0.937685201065128, 'Class_weight': None}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,733] Trial 4 finished with value: 0.9225000000000001 and parameters: {'C': 0.10625805127345389, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,748] Trial 5 finished with value: 0.79 and parameters: {'C': 0.3531892326591997, 'Class_weight': None}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,764] Trial 6 finished with value: 0.9225000000000001 and parameters: {'C': 0.07477102392280875, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,779] Trial 7 finished with value: 0.9225000000000001 and parameters: {'C': 0.6794566753454945, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,795] Trial 8 finished with value: 0.79 and parameters: {'C': 0.5641350458349975, 'Class_weight': None}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,811] Trial 9 finished with value: 0.9225000000000001 and parameters: {'C': 0.03810838134613309, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,826] Trial 10 finished with value: 0.9225000000000001 and parameters: {'C': 0.7910553105104898, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,841] Trial 11 finished with value: 0.9225000000000001 and parameters: {'C': 0.30722693769379006, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,857] Trial 12 finished with value: 0.9225000000000001 and parameters: {'C': 0.33038949808916396, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,872] Trial 13 finished with value: 0.9225000000000001 and parameters: {'C': 0.2060936357774359, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,888] Trial 14 finished with value: 0.9091666666666667 and parameters: {'C': 0.9981912770810087, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,904] Trial 15 finished with value: 0.9225000000000001 and parameters: {'C': 0.45813356489695284, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,919] Trial 16 finished with value: 0.9225000000000001 and parameters: {'C': 0.7622769249226148, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,941] Trial 17 finished with value: 0.9225000000000001 and parameters: {'C': 0.1711313207072404, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,956] Trial 18 finished with value: 0.9225000000000001 and parameters: {'C': 0.437853768361483, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,972] Trial 19 finished with value: 0.9225000000000001 and parameters: {'C': 0.6530046073103304, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:20,988] Trial 20 finished with value: 0.9225000000000001 and parameters: {'C': 0.20814508006380633, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,003] Trial 21 finished with value: 0.9225000000000001 and parameters: {'C': 0.08040181628609239, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,019] Trial 22 finished with value: 0.9225000000000001 and parameters: {'C': 0.1274134734842128, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,034] Trial 23 finished with value: 0.9216666666666666 and parameters: {'C': 0.0016204577537149434, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,049] Trial 24 finished with value: 0.9225000000000001 and parameters: {'C': 0.250032340872749, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,064] Trial 25 finished with value: 0.9225000000000001 and parameters: {'C': 0.0991001270396803, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,079] Trial 26 finished with value: 0.79 and parameters: {'C': 0.5161310358981637, 'Class_weight': None}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,095] Trial 27 finished with value: 0.9225000000000001 and parameters: {'C': 0.3965971715777654, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,111] Trial 28 finished with value: 0.9225000000000001 and parameters: {'C': 0.28076423966191716, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,126] Trial 29 finished with value: 0.79 and parameters: {'C': 0.8305137588149207, 'Class_weight': None}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,141] Trial 30 finished with value: 0.9225000000000001 and parameters: {'C': 0.15560095894468115, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,189] Trial 31 finished with value: 0.9225000000000001 and parameters: {'C': 0.7053937200492625, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,205] Trial 32 finished with value: 0.9225000000000001 and parameters: {'C': 0.911484299775287, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,220] Trial 33 finished with value: 0.9225000000000001 and parameters: {'C': 0.6894533340743569, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,235] Trial 34 finished with value: 0.79 and parameters: {'C': 0.6340839047837441, 'Class_weight': None}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,252] Trial 35 finished with value: 0.79 and parameters: {'C': 0.8817617235076012, 'Class_weight': None}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,267] Trial 36 finished with value: 0.9225000000000001 and parameters: {'C': 0.5704418862434946, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,282] Trial 37 finished with value: 0.9225000000000001 and parameters: {'C': 0.7327569784454446, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,298] Trial 38 finished with value: 0.79 and parameters: {'C': 0.8172105972559064, 'Class_weight': None}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,313] Trial 39 finished with value: 0.9091666666666667 and parameters: {'C': 0.9657304468931818, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,340] Trial 40 finished with value: 0.9225000000000001 and parameters: {'C': 0.04338066900836505, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9225000000000001.
[I 2026-06-24 19:23:21,356] Trial 41 finished with value: 0.9350000000000002 and parameters: {'C': 0.01753822469353218, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,372] Trial 42 finished with value: 0.9225000000000001 and parameters: {'C': 0.05654653430115601, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,387] Trial 43 finished with value: 0.9350000000000002 and parameters: {'C': 0.02070843560456752, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,403] Trial 44 finished with value: 0.9350000000000002 and parameters: {'C': 0.028419845375322904, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,419] Trial 45 finished with value: 0.9350000000000002 and parameters: {'C': 0.01795420968928474, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,435] Trial 46 finished with value: 0.9350000000000002 and parameters: {'C': 0.0045141874434274105, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,451] Trial 47 finished with value: 0.9350000000000002 and parameters: {'C': 0.013323540074099624, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,467] Trial 48 finished with value: 0.9225000000000001 and parameters: {'C': 0.1175781675088095, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,482] Trial 49 finished with value: 0.9350000000000002 and parameters: {'C': 0.0025768844902963224, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,498] Trial 50 finished with value: 0.9225000000000001 and parameters: {'C': 0.15649115860267648, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,516] Trial 51 finished with value: 0.9350000000000002 and parameters: {'C': 0.027829469392583447, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,532] Trial 52 finished with value: 0.9225000000000001 and parameters: {'C': 0.09060816061325884, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,547] Trial 53 finished with value: 0.9225000000000001 and parameters: {'C': 0.0512660489768692, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,563] Trial 54 finished with value: 0.9225000000000001 and parameters: {'C': 0.20695350896951134, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,578] Trial 55 finished with value: 0.9350000000000002 and parameters: {'C': 0.007599854294477818, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,594] Trial 56 finished with value: 0.9225000000000001 and parameters: {'C': 0.07663864556101416, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,610] Trial 57 finished with value: 0.9225000000000001 and parameters: {'C': 0.12346982577076998, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,626] Trial 58 finished with value: 0.9350000000000002 and parameters: {'C': 0.031198560043387925, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,642] Trial 59 finished with value: 0.8033333333333333 and parameters: {'C': 0.18185657294544988, 'Class_weight': None}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,657] Trial 60 finished with value: 0.9225000000000001 and parameters: {'C': 0.2508337221697535, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,673] Trial 61 finished with value: 0.9350000000000002 and parameters: {'C': 0.004067356535432543, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,688] Trial 62 finished with value: 0.9225000000000001 and parameters: {'C': 0.05489569076172408, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,704] Trial 63 finished with value: 0.9225000000000001 and parameters: {'C': 0.0861346699951991, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,720] Trial 64 finished with value: 0.9216666666666666 and parameters: {'C': 0.001143535976283411, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,736] Trial 65 finished with value: 0.9225000000000001 and parameters: {'C': 0.14297817589981687, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,751] Trial 66 finished with value: 0.9225000000000001 and parameters: {'C': 0.1113297546167568, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,767] Trial 67 finished with value: 0.9225000000000001 and parameters: {'C': 0.0649898932095932, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,782] Trial 68 finished with value: 0.9350000000000002 and parameters: {'C': 0.03158021534817267, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,798] Trial 69 finished with value: 0.9225000000000001 and parameters: {'C': 0.1786080988503002, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,813] Trial 70 finished with value: 0.9350000000000002 and parameters: {'C': 0.02764075030811818, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,829] Trial 71 finished with value: 0.9350000000000002 and parameters: {'C': 0.031843810584020166, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,845] Trial 72 finished with value: 0.9225000000000001 and parameters: {'C': 0.07011913285885467, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,860] Trial 73 finished with value: 0.9225000000000001 and parameters: {'C': 0.10284526791341755, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,876] Trial 74 finished with value: 0.9216666666666666 and parameters: {'C': 0.001611235768489633, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,891] Trial 75 finished with value: 0.9225000000000001 and parameters: {'C': 0.13682176215055586, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,907] Trial 76 finished with value: 0.75 and parameters: {'C': 0.02755581932617957, 'Class_weight': None}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,922] Trial 77 finished with value: 0.9225000000000001 and parameters: {'C': 0.08516590383699747, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,938] Trial 78 finished with value: 0.9225000000000001 and parameters: {'C': 0.044638288305864235, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,952] Trial 79 finished with value: 0.9350000000000002 and parameters: {'C': 0.02216454347126326, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,967] Trial 80 finished with value: 0.9225000000000001 and parameters: {'C': 0.3646373861210625, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:21,985] Trial 81 finished with value: 0.9350000000000002 and parameters: {'C': 0.009989433634649368, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,000] Trial 82 finished with value: 0.9225000000000001 and parameters: {'C': 0.05294300991939854, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,016] Trial 83 finished with value: 0.9225000000000001 and parameters: {'C': 0.1026433065109542, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,031] Trial 84 finished with value: 0.9225000000000001 and parameters: {'C': 0.06385391188119258, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,047] Trial 85 finished with value: 0.9350000000000002 and parameters: {'C': 0.018979053006754006, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,063] Trial 86 finished with value: 0.9225000000000001 and parameters: {'C': 0.08773433703636993, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,078] Trial 87 finished with value: 0.8033333333333333 and parameters: {'C': 0.12497114126693913, 'Class_weight': None}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,094] Trial 88 finished with value: 0.9216666666666666 and parameters: {'C': 0.0015107093308854604, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,110] Trial 89 finished with value: 0.9225000000000001 and parameters: {'C': 0.052219537011626446, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,125] Trial 90 finished with value: 0.9225000000000001 and parameters: {'C': 0.16227037982932696, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,141] Trial 91 finished with value: 0.9350000000000002 and parameters: {'C': 0.03400731582588205, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,156] Trial 92 finished with value: 0.9225000000000001 and parameters: {'C': 0.06736842390467776, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,171] Trial 93 finished with value: 0.9350000000000002 and parameters: {'C': 0.029880345000039145, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,187] Trial 94 finished with value: 0.9225000000000001 and parameters: {'C': 0.10150499408832214, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,203] Trial 95 finished with value: 0.9225000000000001 and parameters: {'C': 0.041798139275655934, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,219] Trial 96 finished with value: 0.9225000000000001 and parameters: {'C': 0.07274076166204284, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,244] Trial 97 finished with value: 0.9350000000000002 and parameters: {'C': 0.018062419301839563, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,260] Trial 98 finished with value: 0.9225000000000001 and parameters: {'C': 0.14353529899552994, 'Class_weight': 'balanced'}. Best is trial 41 with value: 0.9350000000000002.
[I 2026-06-24 19:23:22,275] Trial 99 finished with value: 0.79 and parameters: {'C': 0.043749187700314274, 'Class_weight': None}. Best is trial 41 with value: 0.9350000000000002.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
49,49,0.935,2026-06-24 19:23:21.467203,2026-06-24 19:23:21.482290,0 days 00:00:00.015087,0.002577,balanced,COMPLETE
51,51,0.935,2026-06-24 19:23:21.499414,2026-06-24 19:23:21.516371,0 days 00:00:00.016957,0.027829,balanced,COMPLETE
41,41,0.935,2026-06-24 19:23:21.340383,2026-06-24 19:23:21.356481,0 days 00:00:00.016098,0.017538,balanced,COMPLETE
43,43,0.935,2026-06-24 19:23:21.372469,2026-06-24 19:23:21.387751,0 days 00:00:00.015282,0.020708,balanced,COMPLETE
68,68,0.935,2026-06-24 19:23:21.767927,2026-06-24 19:23:21.782949,0 days 00:00:00.015022,0.031580,balanced,COMPLETE

In [23]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        class_weight=class_weight,
        C=c,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

log_reg_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_log_reg_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_log_reg_unscaled_f1_optuna_results)

[I 2026-06-24 19:23:22,294] A new study created in memory with name: no-name-0bab2b58-3f0f-41e4-b560-d8e548ad01dd
[I 2026-06-24 19:23:22,322] Trial 0 finished with value: 0.7231606147150822 and parameters: {'C': 0.7429561565982611, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.7231606147150822.
[I 2026-06-24 19:23:22,337] Trial 1 finished with value: 0.7637535014005602 and parameters: {'C': 0.4935644037518289, 'Class_weight': None}. Best is trial 1 with value: 0.7637535014005602.
[I 2026-06-24 19:23:22,353] Trial 2 finished with value: 0.7637535014005602 and parameters: {'C': 0.8941397917695677, 'Class_weight': None}. Best is trial 1 with value: 0.7637535014005602.
[I 2026-06-24 19:23:22,368] Trial 3 finished with value: 0.7266693866449068 and parameters: {'C': 0.41925089425399004, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.7637535014005602.
[I 2026-06-24 19:23:22,383] Trial 4 finished with value: 0.8063636363636363 and parameters: {'C': 0.11906713406829948, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,399] Trial 5 finished with value: 0.7637535014005602 and parameters: {'C': 0.6317729387788286, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,415] Trial 6 finished with value: 0.7885505299298402 and parameters: {'C': 0.22425770863291794, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,430] Trial 7 finished with value: 0.8063636363636363 and parameters: {'C': 0.1357964424607972, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,446] Trial 8 finished with value: 0.719498746867168 and parameters: {'C': 0.8973606234164712, 'Class_weight': 'balanced'}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,461] Trial 9 finished with value: 0.7228907091820188 and parameters: {'C': 0.3885496160759773, 'Class_weight': 'balanced'}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,477] Trial 10 finished with value: 0.7964285714285715 and parameters: {'C': 0.036401056949214416, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,492] Trial 11 finished with value: 0.7698455367810206 and parameters: {'C': 0.02300962917737756, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,508] Trial 12 finished with value: 0.7885505299298402 and parameters: {'C': 0.2302528897227924, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,524] Trial 13 finished with value: 0.7944618599791013 and parameters: {'C': 0.19982197184613149, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,555] Trial 14 finished with value: 0.8063636363636363 and parameters: {'C': 0.1335723978624425, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,586] Trial 15 finished with value: 0.7780422012065014 and parameters: {'C': 0.3340500828777518, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,605] Trial 16 finished with value: 0.8063636363636363 and parameters: {'C': 0.12046672669225425, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,635] Trial 17 finished with value: 0.7637535014005602 and parameters: {'C': 0.6674932138179492, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,667] Trial 18 finished with value: 0.7228907091820188 and parameters: {'C': 0.3128665281291717, 'Class_weight': 'balanced'}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,683] Trial 19 finished with value: 0.3313492063492064 and parameters: {'C': 0.0065363047564324095, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,697] Trial 20 finished with value: 0.7637535014005602 and parameters: {'C': 0.5730207016340947, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,714] Trial 21 finished with value: 0.8063636363636363 and parameters: {'C': 0.1385607194038568, 'Class_weight': None}. Best is trial 4 with value: 0.8063636363636363.
[I 2026-06-24 19:23:22,729] Trial 22 finished with value: 0.8116666666666668 and parameters: {'C': 0.10200267902790681, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,745] Trial 23 finished with value: 0.7835594425858117 and parameters: {'C': 0.2899091195723095, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,761] Trial 24 finished with value: 0.8116666666666668 and parameters: {'C': 0.11361093387332395, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,777] Trial 25 finished with value: 0.8116666666666668 and parameters: {'C': 0.08057408594797688, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,792] Trial 26 finished with value: 0.7193819372521942 and parameters: {'C': 0.0923453412870999, 'Class_weight': 'balanced'}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,814] Trial 27 finished with value: 0.7885505299298402 and parameters: {'C': 0.2055423274481701, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,830] Trial 28 finished with value: 0.7559374094465372 and parameters: {'C': 0.9992091197903162, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,846] Trial 29 finished with value: 0.7266693866449068 and parameters: {'C': 0.45335476256481494, 'Class_weight': 'balanced'}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,862] Trial 30 finished with value: 0.7835594425858117 and parameters: {'C': 0.27568756064007843, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,877] Trial 31 finished with value: 0.8116666666666668 and parameters: {'C': 0.07862628877800217, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,892] Trial 32 finished with value: 0.8116666666666668 and parameters: {'C': 0.059692786878202606, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,907] Trial 33 finished with value: 0.8018181818181818 and parameters: {'C': 0.1881634840150913, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,923] Trial 34 finished with value: 0.8116666666666668 and parameters: {'C': 0.06975632266298303, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,954] Trial 35 finished with value: 0.7737641263401913 and parameters: {'C': 0.3581132986291438, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:22,970] Trial 36 finished with value: 0.11168730650154798 and parameters: {'C': 0.005926149068984629, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,001] Trial 37 finished with value: 0.7637535014005602 and parameters: {'C': 0.5136152935743736, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,017] Trial 38 finished with value: 0.7160486039188609 and parameters: {'C': 0.1655826470364296, 'Class_weight': 'balanced'}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,033] Trial 39 finished with value: 0.7885505299298402 and parameters: {'C': 0.24753280369263692, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,048] Trial 40 finished with value: 0.8116666666666668 and parameters: {'C': 0.08277077922084515, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,063] Trial 41 finished with value: 0.8116666666666668 and parameters: {'C': 0.06391684215099457, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,079] Trial 42 finished with value: 0.8116666666666668 and parameters: {'C': 0.06511010848239322, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,095] Trial 43 finished with value: 0.8063636363636363 and parameters: {'C': 0.15823438731202838, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,110] Trial 44 finished with value: 0.7637535014005602 and parameters: {'C': 0.8010039356643446, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,126] Trial 45 finished with value: 0.8116666666666668 and parameters: {'C': 0.10134014460700279, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,142] Trial 46 finished with value: 0.6974716009259402 and parameters: {'C': 0.05349350291962132, 'Class_weight': 'balanced'}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,157] Trial 47 finished with value: 0.8018181818181818 and parameters: {'C': 0.17242245812369772, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,173] Trial 48 finished with value: 0.7835594425858117 and parameters: {'C': 0.26293638407809083, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,189] Trial 49 finished with value: 0.8116666666666668 and parameters: {'C': 0.11166197092159147, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,205] Trial 50 finished with value: 0.7863756613756614 and parameters: {'C': 0.03409266954484952, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,221] Trial 51 finished with value: 0.8116666666666668 and parameters: {'C': 0.05853719590249465, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,236] Trial 52 finished with value: 0.07205882352941176 and parameters: {'C': 0.004614262748613429, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,252] Trial 53 finished with value: 0.7885505299298402 and parameters: {'C': 0.21161296413024522, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,267] Trial 54 finished with value: 0.8063636363636363 and parameters: {'C': 0.13158184354940622, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,285] Trial 55 finished with value: 0.8116666666666668 and parameters: {'C': 0.08530540922100761, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,300] Trial 56 finished with value: 0.8063636363636363 and parameters: {'C': 0.15195084009980644, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,316] Trial 57 finished with value: 0.6870653907496013 and parameters: {'C': 0.03867458298870205, 'Class_weight': 'balanced'}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,331] Trial 58 finished with value: 0.7885505299298402 and parameters: {'C': 0.23086580156110437, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,347] Trial 59 finished with value: 0.8063636363636363 and parameters: {'C': 0.11949957945077427, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,363] Trial 60 finished with value: 0.7637535014005602 and parameters: {'C': 0.6920378664165546, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,393] Trial 61 finished with value: 0.8116666666666668 and parameters: {'C': 0.09702092943481826, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,408] Trial 62 finished with value: 0.8116666666666668 and parameters: {'C': 0.08778922509172273, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,424] Trial 63 finished with value: 0.8043103448275861 and parameters: {'C': 0.0445079557501562, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,440] Trial 64 finished with value: 0.8018181818181818 and parameters: {'C': 0.1749106106086764, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,455] Trial 65 finished with value: 0.0 and parameters: {'C': 0.0016428742936305113, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,471] Trial 66 finished with value: 0.8116666666666668 and parameters: {'C': 0.07686538506297715, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,486] Trial 67 finished with value: 0.8063636363636363 and parameters: {'C': 0.12959218548775944, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,502] Trial 68 finished with value: 0.7160486039188609 and parameters: {'C': 0.189064214866767, 'Class_weight': 'balanced'}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,519] Trial 69 finished with value: 0.7863756613756614 and parameters: {'C': 0.030648889378259478, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,534] Trial 70 finished with value: 0.7737641263401913 and parameters: {'C': 0.39051351160482195, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,549] Trial 71 finished with value: 0.8116666666666668 and parameters: {'C': 0.06791039455284259, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,565] Trial 72 finished with value: 0.8116666666666668 and parameters: {'C': 0.10881889718001933, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,581] Trial 73 finished with value: 0.8116666666666668 and parameters: {'C': 0.07216411539920839, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,597] Trial 74 finished with value: 0.8063636363636363 and parameters: {'C': 0.15194988094955733, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,613] Trial 75 finished with value: 0.7863756613756614 and parameters: {'C': 0.03119102520789902, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,628] Trial 76 finished with value: 0.8116666666666668 and parameters: {'C': 0.057617205970450926, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,644] Trial 77 finished with value: 0.8063636363636363 and parameters: {'C': 0.14529218760720075, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,659] Trial 78 finished with value: 0.7193819372521942 and parameters: {'C': 0.09382426032809241, 'Class_weight': 'balanced'}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,675] Trial 79 finished with value: 0.7637535014005602 and parameters: {'C': 0.5591382455817691, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,691] Trial 80 finished with value: 0.7885505299298402 and parameters: {'C': 0.2302027019188136, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,706] Trial 81 finished with value: 0.8116666666666668 and parameters: {'C': 0.06526721280188717, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,721] Trial 82 finished with value: 0.7564327070778684 and parameters: {'C': 0.01671119809641522, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,737] Trial 83 finished with value: 0.8116666666666668 and parameters: {'C': 0.1116652266824797, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,753] Trial 84 finished with value: 0.8043103448275861 and parameters: {'C': 0.04191577500396502, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,768] Trial 85 finished with value: 0.8018181818181818 and parameters: {'C': 0.19376234271342896, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,795] Trial 86 finished with value: 0.7780422012065014 and parameters: {'C': 0.30113827610921523, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,823] Trial 87 finished with value: 0.8063636363636363 and parameters: {'C': 0.12512652898332177, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,838] Trial 88 finished with value: 0.8116666666666668 and parameters: {'C': 0.08823861150006805, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,869] Trial 89 finished with value: 0.7637535014005602 and parameters: {'C': 0.8127021458481349, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,897] Trial 90 finished with value: 0.7160486039188609 and parameters: {'C': 0.16159278552439438, 'Class_weight': 'balanced'}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,929] Trial 91 finished with value: 0.8116666666666668 and parameters: {'C': 0.06519539893729488, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,943] Trial 92 finished with value: 0.8116666666666668 and parameters: {'C': 0.10422865233173546, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,958] Trial 93 finished with value: 0.7779100529100529 and parameters: {'C': 0.027480443104246466, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:23,989] Trial 94 finished with value: 0.8063636363636363 and parameters: {'C': 0.13493745124358622, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:24,005] Trial 95 finished with value: 0.8116666666666668 and parameters: {'C': 0.05288158802156961, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:24,021] Trial 96 finished with value: 0.8116666666666668 and parameters: {'C': 0.07863241328646034, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:24,037] Trial 97 finished with value: 0.8018181818181818 and parameters: {'C': 0.17636595524406307, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:24,052] Trial 98 finished with value: 0.7607287276642116 and parameters: {'C': 0.019494913811069728, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.
[I 2026-06-24 19:23:24,068] Trial 99 finished with value: 0.0 and parameters: {'C': 0.001137195028804952, 'Class_weight': None}. Best is trial 22 with value: 0.8116666666666668.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
32,32,0.811667,2026-06-24 19:23:22.877184,2026-06-24 19:23:22.892282,0 days 00:00:00.015098,0.059693,None,COMPLETE
34,34,0.811667,2026-06-24 19:23:22.907750,2026-06-24 19:23:22.923709,0 days 00:00:00.015959,0.069756,None,COMPLETE
25,25,0.811667,2026-06-24 19:23:22.761329,2026-06-24 19:23:22.777192,0 days 00:00:00.015863,0.080574,None,COMPLETE
31,31,0.811667,2026-06-24 19:23:22.862041,2026-06-24 19:23:22.877184,0 days 00:00:00.015143,0.078626,None,COMPLETE
24,24,0.811667,2026-06-24 19:23:22.746410,2026-06-24 19:23:22.761329,0 days 00:00:00.014919,0.113611,None,COMPLETE

##### Tryout best params

In [24]:
log_reg_recall_optimized_model = LogisticRegression(C=0.769946, class_weight='balanced', random_state=random_state)
log_reg_recall_optimized_model.fit(X_train_scaled, y_train)
y_pred = log_reg_recall_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Logistic Regression (Recall Optimized)')

              precision    recall  f1-score   support

           0       0.98      0.92      0.95       190
           1       0.52      0.84      0.64        19

    accuracy                           0.91       209
   macro avg       0.75      0.88      0.80       209
weighted avg       0.94      0.91      0.92       209

In [25]:
log_reg_f1_optimized_model = LogisticRegression(C=0.315005, class_weight='balanced', random_state=random_state)
log_reg_f1_optimized_model.fit(X_train_scaled, y_train)
y_pred = log_reg_f1_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Logistic Regression (F1 Optimized)')

              precision    recall  f1-score   support

           0       0.98      0.92      0.95       190
           1       0.52      0.84      0.64        19

    accuracy                           0.91       209
   macro avg       0.75      0.88      0.80       209
weighted avg       0.94      0.91      0.92       209

#### Ridge

In [26]:
# We can tune alpha and class weight

##### Recall optimized

In [27]:
def objective(trial):
    alpha = trial.suggest_float("alpha", 0.001, 1.0)
    class_weight = trial.suggest_categorical("class_weight", ['balanced', None])
    
    model = RidgeClassifier(
        class_weight=class_weight,
        alpha=alpha,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

ridge_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_ridge_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_ridge_unscaled_recall_optuna_results)

[I 2026-06-24 19:23:24,169] A new study created in memory with name: no-name-f5599b59-5e48-4a69-ae09-f86d8cfea12f
[I 2026-06-24 19:23:24,190] Trial 0 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.07830805371391322, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,206] Trial 1 finished with value: 0.7899999999999999 and parameters: {'alpha': 0.43514992988920276, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,222] Trial 2 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.8585361598234713, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,237] Trial 3 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.7703638839486203, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,253] Trial 4 finished with value: 0.7899999999999999 and parameters: {'alpha': 0.33204202972568997, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,268] Trial 5 finished with value: 0.7766666666666666 and parameters: {'alpha': 0.8774257500677478, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,283] Trial 6 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.7268714958994424, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,299] Trial 7 finished with value: 0.7899999999999999 and parameters: {'alpha': 0.4004299216727824, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,315] Trial 8 finished with value: 0.7766666666666666 and parameters: {'alpha': 0.8526014152520068, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,331] Trial 9 finished with value: 0.7766666666666666 and parameters: {'alpha': 0.8197572557173534, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,346] Trial 10 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.042202984016711256, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,362] Trial 11 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.01114293016625112, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,377] Trial 12 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.5713512421353422, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,393] Trial 13 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.21818174214263725, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,408] Trial 14 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.5845253190076536, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,424] Trial 15 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.9557292692667619, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,440] Trial 16 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.18860549168878848, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,455] Trial 17 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.609043965070467, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,471] Trial 18 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.29774688211691425, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,487] Trial 19 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.9847295628415391, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,503] Trial 20 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.11949556142499554, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,519] Trial 21 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.7323011572100864, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,544] Trial 22 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.7225898649063774, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,560] Trial 23 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.6675629232626223, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,575] Trial 24 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.5015043536455129, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,590] Trial 25 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.8295002895589941, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,606] Trial 26 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.8890909218875824, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,622] Trial 27 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.7802248883605033, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,637] Trial 28 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.9342115720883977, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,652] Trial 29 finished with value: 0.7899999999999999 and parameters: {'alpha': 0.47449768468613485, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,668] Trial 30 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.6595626391068522, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,684] Trial 31 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.7142273153478872, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,702] Trial 32 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.7961777866617626, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,717] Trial 33 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.8953309466716383, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,732] Trial 34 finished with value: 0.7899999999999999 and parameters: {'alpha': 0.5207662301839897, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,748] Trial 35 finished with value: 0.7899999999999999 and parameters: {'alpha': 0.38860484448922017, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,763] Trial 36 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.7693555216297285, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,780] Trial 37 finished with value: 0.7899999999999999 and parameters: {'alpha': 0.6561660945911192, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,795] Trial 38 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.3273068478808704, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,810] Trial 39 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.8611690853018332, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,825] Trial 40 finished with value: 0.7899999999999999 and parameters: {'alpha': 0.42639234131550335, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,839] Trial 41 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.003998375516611391, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,855] Trial 42 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.07278694920809493, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,870] Trial 43 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.06896363204320176, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,886] Trial 44 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.1612131265413716, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,901] Trial 45 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.24959642091509054, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,917] Trial 46 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.06779263184848824, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,933] Trial 47 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.11410670008767695, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,949] Trial 48 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.9175083824069068, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,964] Trial 49 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.9812370838264968, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,980] Trial 50 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.5554398207461241, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:24,995] Trial 51 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.030003303035464668, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,011] Trial 52 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.14107054380098027, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,027] Trial 53 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.2331610570681088, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,042] Trial 54 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.004036015530134226, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,058] Trial 55 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.09976921237050182, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,073] Trial 56 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.19741336827790806, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,089] Trial 57 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.04415933158665035, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,105] Trial 58 finished with value: 0.7766666666666666 and parameters: {'alpha': 0.8356719384567832, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,121] Trial 59 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.6138652091475729, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,142] Trial 60 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.750742962822639, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,158] Trial 61 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.7066150020040638, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,173] Trial 62 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.6778771438446242, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,189] Trial 63 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.6220979920467928, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,204] Trial 64 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.5708278619600817, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,220] Trial 65 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.28683712917353155, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,236] Trial 66 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.8108176412199077, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,252] Trial 67 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.4756138297003744, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,268] Trial 68 finished with value: 0.7766666666666666 and parameters: {'alpha': 0.7542791736700436, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,283] Trial 69 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.8706054685939161, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,305] Trial 70 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.3803231946835811, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,320] Trial 71 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.034339568844321454, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,336] Trial 72 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.17391434382136195, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,352] Trial 73 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.09518543384551853, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,367] Trial 74 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.13816946317849552, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,383] Trial 75 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.7952523566456886, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,399] Trial 76 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.051514441664424565, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,415] Trial 77 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.004948475400414987, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,431] Trial 78 finished with value: 0.7899999999999999 and parameters: {'alpha': 0.6844354402847658, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,447] Trial 79 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.3531894850576852, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,462] Trial 80 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.5275024081829016, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,477] Trial 81 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.6455020153315217, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,493] Trial 82 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.5568221418933873, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,508] Trial 83 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.5873147851159113, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,524] Trial 84 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.45168030989431257, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,540] Trial 85 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.20326730461532366, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,556] Trial 86 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.9422665695028714, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,571] Trial 87 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.8953348326620446, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,587] Trial 88 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.6337128970672625, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,602] Trial 89 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.8479647617779353, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,617] Trial 90 finished with value: 0.7899999999999999 and parameters: {'alpha': 0.09232204948181677, 'class_weight': None}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,635] Trial 91 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.736670078116108, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,650] Trial 92 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.6991479653947777, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,666] Trial 93 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.5900166655414798, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,682] Trial 94 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.9681371806508303, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,697] Trial 95 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.9272937573966562, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,713] Trial 96 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.9547846556226768, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,728] Trial 97 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.5299027604675717, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.
[I 2026-06-24 19:23:25,744] Trial 98 finished with value: 0.9350000000000002 and parameters: {'alpha': 0.8191768526787457, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.9350000000000002.

,number,value,datetime_start,datetime_complete,duration,params_alpha,params_class_weight,state
0,0,0.935,2026-06-24 19:23:24.170528,2026-06-24 19:23:24.190455,0 days 00:00:00.019927,0.078308,balanced,COMPLETE
2,2,0.935,2026-06-24 19:23:24.207075,2026-06-24 19:23:24.222367,0 days 00:00:00.015292,0.858536,balanced,COMPLETE
3,3,0.935,2026-06-24 19:23:24.222367,2026-06-24 19:23:24.237571,0 days 00:00:00.015204,0.770364,balanced,COMPLETE
6,6,0.935,2026-06-24 19:23:24.268651,2026-06-24 19:23:24.283779,0 days 00:00:00.015128,0.726871,balanced,COMPLETE
28,28,0.935,2026-06-24 19:23:24.622241,2026-06-24 19:23:24.637383,0 days 00:00:00.015142,0.934212,balanced,COMPLETE

##### Tryout best params

In [28]:
ridge_recall_optimized_model = RidgeClassifier(alpha=0.039558, class_weight='balanced', random_state=random_state)
ridge_recall_optimized_model.fit(X_train_scaled, y_train)
y_pred = ridge_recall_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Ridge Classifier (Recall Optimized)')

              precision    recall  f1-score   support

           0       0.98      0.88      0.93       190
           1       0.42      0.84      0.56        19

    accuracy                           0.88       209
   macro avg       0.70      0.86      0.75       209
weighted avg       0.93      0.88      0.90       209

##### F1 optimized

In [29]:
def objective(trial):
    alpha = trial.suggest_float("alpha", 0.001, 1.0)
    class_weight = trial.suggest_categorical("class_weight", ['balanced', None])
    
    model = RidgeClassifier(
        class_weight=class_weight,
        alpha=alpha,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

ridge_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_ridge_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_ridge_unscaled_f1_optuna_results)

[I 2026-06-24 19:23:25,795] A new study created in memory with name: no-name-8bd87806-44f5-46bf-af8c-02c0baeabfea
[I 2026-06-24 19:23:25,823] Trial 0 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.8233293275412075, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.6647694334650855.
[I 2026-06-24 19:23:25,845] Trial 1 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5555056826845673, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:25,860] Trial 2 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.26924662542734534, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:25,876] Trial 3 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.0033975815539298133, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:25,894] Trial 4 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.47950081217394874, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:25,908] Trial 5 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.5613556364554781, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:25,924] Trial 6 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.6272263577298794, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:25,940] Trial 7 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.3374667488124516, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:25,955] Trial 8 finished with value: 0.7570211532889017 and parameters: {'alpha': 0.9586822677727359, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:25,970] Trial 9 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.12228866992662227, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:25,986] Trial 10 finished with value: 0.7570211532889017 and parameters: {'alpha': 0.7266156796092242, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,002] Trial 11 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.3165459258670807, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,017] Trial 12 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.33084129634499293, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,032] Trial 13 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.18199548983494188, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,047] Trial 14 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.38895995850592097, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,062] Trial 15 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.48676536211074367, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,078] Trial 16 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.20653475850805814, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,093] Trial 17 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.6689595860274037, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,108] Trial 18 finished with value: 0.7570211532889017 and parameters: {'alpha': 0.8204353006367715, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,125] Trial 19 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.4415746292758741, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,142] Trial 20 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.25542726508658303, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,157] Trial 21 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5965060587035356, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,173] Trial 22 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5953110528310027, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,188] Trial 23 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.7089407138402819, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,204] Trial 24 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5440962237670702, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,219] Trial 25 finished with value: 0.7570211532889017 and parameters: {'alpha': 0.8163920233853675, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,235] Trial 26 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.6599164922091154, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,250] Trial 27 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.4238849910265403, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,266] Trial 28 finished with value: 0.7570211532889017 and parameters: {'alpha': 0.9635651527985865, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,285] Trial 29 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.10156996120804399, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,301] Trial 30 finished with value: 0.7570211532889017 and parameters: {'alpha': 0.8772936901165873, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,316] Trial 31 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.3306611143748191, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,335] Trial 32 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.2539799089706108, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,350] Trial 33 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.019088162924102203, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,365] Trial 34 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.517050876652436, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,381] Trial 35 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.3728359216056888, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,396] Trial 36 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.264605967008482, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,412] Trial 37 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.467978865733494, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,427] Trial 38 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.6138296077399371, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,443] Trial 39 finished with value: 0.7570211532889017 and parameters: {'alpha': 0.7662377362241282, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,459] Trial 40 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.10388610338710674, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,475] Trial 41 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.3353399621998249, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,489] Trial 42 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.2962609444395605, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,504] Trial 43 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.19562205140558578, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,519] Trial 44 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.3937093439026636, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,535] Trial 45 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.14943550102868117, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,550] Trial 46 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.48989729759719924, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,566] Trial 47 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5271845724104377, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,581] Trial 48 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.4405463751028584, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,597] Trial 49 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5745025135275662, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,613] Trial 50 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.6393912020551976, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,628] Trial 51 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.19757872646893881, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,643] Trial 52 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.2972985853820527, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,659] Trial 53 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.15409893914877032, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,674] Trial 54 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.24241686603891177, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,690] Trial 55 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.04935676767717323, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,705] Trial 56 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.3606034981572823, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,721] Trial 57 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.4085259325931085, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,737] Trial 58 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.6927511884777959, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,752] Trial 59 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.21759864063573459, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,768] Trial 60 finished with value: 0.7570211532889017 and parameters: {'alpha': 0.7644616559182207, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,784] Trial 61 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.2761211321098823, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,800] Trial 62 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.3822880005467892, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,815] Trial 63 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.31436816609358614, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,831] Trial 64 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.4654212721512941, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,847] Trial 65 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.35058804462482135, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,870] Trial 66 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5651537105333023, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,885] Trial 67 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.17641401328926887, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,905] Trial 68 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.24287608082419282, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,921] Trial 69 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.4291325322845164, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,936] Trial 70 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.29513709552391776, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,952] Trial 71 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5184749832723972, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,967] Trial 72 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.4645583174324489, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,983] Trial 73 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.6507312417619413, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:26,998] Trial 74 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.6075745740541906, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,029] Trial 75 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5004253317606613, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,045] Trial 76 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.40524990417942386, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,061] Trial 77 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5496527321791275, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,077] Trial 78 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.3140949230624852, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,092] Trial 79 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.3592821818119678, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,108] Trial 80 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5841098137794056, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,123] Trial 81 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.2319404430587392, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,138] Trial 82 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.12668585096946552, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,154] Trial 83 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.21643810404518388, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,169] Trial 84 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.27542169278723394, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,185] Trial 85 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.18241489925955953, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,200] Trial 86 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.06873523156904704, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,216] Trial 87 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.33614999268445833, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,231] Trial 88 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.14021314626853548, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,247] Trial 89 finished with value: 0.6647694334650855 and parameters: {'alpha': 0.627872367980879, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,262] Trial 90 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.6833582160543422, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,278] Trial 91 finished with value: 0.7570211532889017 and parameters: {'alpha': 0.7237322746393073, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,293] Trial 92 finished with value: 0.7570211532889017 and parameters: {'alpha': 0.9041785858183065, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,309] Trial 93 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.2670819045194387, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,324] Trial 94 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.6655431431423076, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,340] Trial 95 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.376059465019307, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,356] Trial 96 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.5334072482248583, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,372] Trial 97 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.31932903317564937, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,387] Trial 98 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.16713227421397053, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.
[I 2026-06-24 19:23:27,419] Trial 99 finished with value: 0.7599343185550083 and parameters: {'alpha': 0.2204018391995264, 'class_weight': None}. Best is trial 1 with value: 0.7599343185550083.

,number,value,datetime_start,datetime_complete,duration,params_alpha,params_class_weight,state
1,1,0.759934,2026-06-24 19:23:25.823427,2026-06-24 19:23:25.845475,0 days 00:00:00.022048,0.555506,None,COMPLETE
2,2,0.759934,2026-06-24 19:23:25.845475,2026-06-24 19:23:25.860983,0 days 00:00:00.015508,0.269247,None,COMPLETE
11,11,0.759934,2026-06-24 19:23:25.986723,2026-06-24 19:23:26.002082,0 days 00:00:00.015359,0.316546,None,COMPLETE
6,6,0.759934,2026-06-24 19:23:25.909788,2026-06-24 19:23:25.924701,0 days 00:00:00.014913,0.627226,None,COMPLETE
33,33,0.759934,2026-06-24 19:23:26.335403,2026-06-24 19:23:26.350559,0 days 00:00:00.015156,0.019088,None,COMPLETE

##### Tryout best params

In [30]:
ridge_f1_optimized_model = RidgeClassifier(alpha=0.364826, class_weight='balanced', random_state=random_state)
ridge_f1_optimized_model.fit(X_train_scaled, y_train)
y_pred = ridge_f1_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Ridge Classifier (F1 Optimized)')

              precision    recall  f1-score   support

           0       0.98      0.88      0.93       190
           1       0.41      0.84      0.55        19

    accuracy                           0.88       209
   macro avg       0.70      0.86      0.74       209
weighted avg       0.93      0.88      0.89       209

#### Lasso Logistic Regression

In [31]:
# We can only tune the C (float) and Class_weight to tryout balanced.

In [32]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        penalty='l1', # Lasso
        class_weight=class_weight,
        C=c,
        solver='liblinear',
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=15, n_jobs=-1)

lasso_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_lasso_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_lasso_unscaled_recall_optuna_results)

[I 2026-06-24 19:23:27,489] A new study created in memory with name: no-name-fcac938c-0e98-4c66-8312-de74bfb833b4
[I 2026-06-24 19:23:27,591] Trial 0 finished with value: 0.9225000000000001 and parameters: {'C': 0.41346256526724884, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9225000000000001.
[I 2026-06-24 19:23:27,606] Trial 5 finished with value: 0.9225000000000001 and parameters: {'C': 0.6387371254822808, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9225000000000001.
[I 2026-06-24 19:23:27,609] Trial 1 finished with value: 0.8300000000000001 and parameters: {'C': 0.16434847869122923, 'Class_weight': None}. Best is trial 0 with value: 0.9225000000000001.
[I 2026-06-24 19:23:27,623] Trial 3 finished with value: 0.8166666666666668 and parameters: {'C': 0.629062958954625, 'Class_weight': None}. Best is trial 0 with value: 0.9225000000000001.
[I 2026-06-24 19:23:27,646] Trial 7 finished with value: 0.9350000000000002 and parameters: {'C': 0.1044316485223579, 'Class_weight': 'balanced'}. Best is trial 7 with value: 0.9350000000000002.
[I 2026-06-24 19:23:27,647] Trial 12 finished with value: 0.9350000000000002 and parameters: {'C': 0.2640633625420201, 'Class_weight': 'balanced'}. Best is trial 7 with value: 0.9350000000000002.
[I 2026-06-24 19:23:27,647] Trial 8 finished with value: 0.8166666666666668 and parameters: {'C': 0.9275837363270223, 'Class_weight': None}. Best is trial 7 with value: 0.9350000000000002.
[I 2026-06-24 19:23:27,647] Trial 4 finished with value: 0.9225000000000001 and parameters: {'C': 0.8949245804267929, 'Class_weight': 'balanced'}. Best is trial 7 with value: 0.9350000000000002.
[I 2026-06-24 19:23:27,648] Trial 2 finished with value: 0.8166666666666668 and parameters: {'C': 0.8465295273762603, 'Class_weight': None}. Best is trial 7 with value: 0.9350000000000002.
[I 2026-06-24 19:23:27,648] Trial 13 finished with value: 0.9225000000000001 and parameters: {'C': 0.525592056145594, 'Class_weight': 'balanced'}. Best is trial 7 with value: 0.9350000000000002.
[I 2026-06-24 19:23:27,648] Trial 9 finished with value: 0.9350000000000002 and parameters: {'C': 0.24297778994542601, 'Class_weight': 'balanced'}. Best is trial 7 with value: 0.9350000000000002.
[I 2026-06-24 19:23:27,648] Trial 10 finished with value: 0.8166666666666668 and parameters: {'C': 0.8608593053637797, 'Class_weight': None}. Best is trial 7 with value: 0.9350000000000002.
[I 2026-06-24 19:23:27,648] Trial 14 finished with value: 0.9350000000000002 and parameters: {'C': 0.2590264827832332, 'Class_weight': 'balanced'}. Best is trial 7 with value: 0.9350000000000002.
[I 2026-06-24 19:23:27,648] Trial 6 finished with value: 0.8166666666666668 and parameters: {'C': 0.9525481780090888, 'Class_weight': None}. Best is trial 7 with value: 0.9350000000000002.
[I 2026-06-24 19:23:27,648] Trial 11 finished with value: 0.8166666666666668 and parameters: {'C': 0.5724135714557395, 'Class_weight': None}. Best is trial 7 with value: 0.9350000000000002.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
14,14,0.9350,2026-06-24 19:23:27.528184,2026-06-24 19:23:27.648618,0 days 00:00:00.120434,0.259026,balanced,COMPLETE
9,9,0.9350,2026-06-24 19:23:27.514594,2026-06-24 19:23:27.648618,0 days 00:00:00.134024,0.242978,balanced,COMPLETE
7,7,0.9350,2026-06-24 19:23:27.508594,2026-06-24 19:23:27.646496,0 days 00:00:00.137902,0.104432,balanced,COMPLETE
12,12,0.9350,2026-06-24 19:23:27.522606,2026-06-24 19:23:27.647617,0 days 00:00:00.125011,0.264063,balanced,COMPLETE
0,0,0.9225,2026-06-24 19:23:27.491893,2026-06-24 19:23:27.591659,0 days 00:00:00.099766,0.413463,balanced,COMPLETE

In [33]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        penalty='l1', # Lasso
        class_weight=class_weight,
        C=c,
        solver='liblinear',
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=15)

lasso_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_lasso_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_lasso_unscaled_f1_optuna_results)

[I 2026-06-24 19:23:27,683] A new study created in memory with name: no-name-d78a5173-e6f7-443d-8a37-2bb7a45f31d3
[I 2026-06-24 19:23:27,708] Trial 0 finished with value: 0.7222786696470908 and parameters: {'C': 0.8226769121681857, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.7222786696470908.
[I 2026-06-24 19:23:27,748] Trial 1 finished with value: 0.7998768472906403 and parameters: {'C': 0.3645916710328363, 'Class_weight': None}. Best is trial 1 with value: 0.7998768472906403.
[I 2026-06-24 19:23:27,779] Trial 2 finished with value: 0.7153717627401839 and parameters: {'C': 0.9362627395766104, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.7998768472906403.
[I 2026-06-24 19:23:27,795] Trial 3 finished with value: 0.6642818428184282 and parameters: {'C': 0.01650026900993542, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.7998768472906403.
[I 2026-06-24 19:23:27,811] Trial 4 finished with value: 0.7191144527986633 and parameters: {'C': 0.2446138819499793, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.7998768472906403.
[I 2026-06-24 19:23:27,826] Trial 5 finished with value: 0.805522008580963 and parameters: {'C': 0.2023936931917072, 'Class_weight': None}. Best is trial 5 with value: 0.805522008580963.
[I 2026-06-24 19:23:27,841] Trial 6 finished with value: 0.0 and parameters: {'C': 0.007336792476630736, 'Class_weight': None}. Best is trial 5 with value: 0.805522008580963.
[I 2026-06-24 19:23:27,873] Trial 7 finished with value: 0.7818216318785579 and parameters: {'C': 0.9278592327409565, 'Class_weight': None}. Best is trial 5 with value: 0.805522008580963.
[I 2026-06-24 19:23:27,888] Trial 8 finished with value: 0.7223664853189885 and parameters: {'C': 0.29607227145743154, 'Class_weight': 'balanced'}. Best is trial 5 with value: 0.805522008580963.
[I 2026-06-24 19:23:27,903] Trial 9 finished with value: 0.7262129683182315 and parameters: {'C': 0.5057407910065881, 'Class_weight': 'balanced'}. Best is trial 5 with value: 0.805522008580963.
[I 2026-06-24 19:23:27,932] Trial 10 finished with value: 0.7916169481241784 and parameters: {'C': 0.6007776628647216, 'Class_weight': None}. Best is trial 5 with value: 0.805522008580963.
[I 2026-06-24 19:23:27,951] Trial 11 finished with value: 0.7998768472906403 and parameters: {'C': 0.27960401532763796, 'Class_weight': None}. Best is trial 5 with value: 0.805522008580963.
[I 2026-06-24 19:23:27,977] Trial 12 finished with value: 0.805522008580963 and parameters: {'C': 0.1840362704609785, 'Class_weight': None}. Best is trial 5 with value: 0.805522008580963.
[I 2026-06-24 19:23:28,000] Trial 13 finished with value: 0.805522008580963 and parameters: {'C': 0.15390839220885097, 'Class_weight': None}. Best is trial 5 with value: 0.805522008580963.
[I 2026-06-24 19:23:28,015] Trial 14 finished with value: 0.805522008580963 and parameters: {'C': 0.11631882773425906, 'Class_weight': None}. Best is trial 5 with value: 0.805522008580963.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
5,5,0.805522,2026-06-24 19:23:27.812364,2026-06-24 19:23:27.826430,0 days 00:00:00.014066,0.202394,None,COMPLETE
14,14,0.805522,2026-06-24 19:23:28.001689,2026-06-24 19:23:28.015744,0 days 00:00:00.014055,0.116319,None,COMPLETE
13,13,0.805522,2026-06-24 19:23:27.977931,2026-06-24 19:23:28.000615,0 days 00:00:00.022684,0.153908,None,COMPLETE
12,12,0.805522,2026-06-24 19:23:27.951404,2026-06-24 19:23:27.977931,0 days 00:00:00.026527,0.184036,None,COMPLETE
11,11,0.799877,2026-06-24 19:23:27.932575,2026-06-24 19:23:27.951404,0 days 00:00:00.018829,0.279604,None,COMPLETE

##### Tryout best params

In [34]:
lasso_recall_optimized_model = LogisticRegression(
    penalty='l1', # Lasso
    C=0.248927, 
    class_weight=None,
    solver='saga',
    random_state=random_state
)
lasso_recall_optimized_model.fit(X_train_scaled, y_train)
y_pred = lasso_recall_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Lasso Classifier (Recall Optimized)')

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

              precision    recall  f1-score   support

           0       0.98      0.97      0.97       190
           1       0.71      0.79      0.75        19

    accuracy                           0.95       209
   macro avg       0.85      0.88      0.86       209
weighted avg       0.95      0.95      0.95       209

In [35]:
lasso_f1_optimized_model = LogisticRegression(
    penalty='l1', # Lasso
    C=0.496023, 
    class_weight=None,
    solver='saga',
    random_state=random_state
)
lasso_f1_optimized_model.fit(X_train_scaled, y_train)
y_pred = lasso_f1_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Lasso Classifier (F1 Optimized)')

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       190
           1       0.68      0.79      0.73        19

    accuracy                           0.95       209
   macro avg       0.83      0.88      0.85       209
weighted avg       0.95      0.95      0.95       209

### Conclusions

In [36]:
reports_df = pd.concat(classification_reports, keys=classification_report_keys)
reports_df

                                                      precision    recall  \
Baseline Logistic Regression            0              0.988304  0.889474
                                        1              0.447368  0.894737
                                        accuracy       0.889952  0.889952
                                        macro avg      0.717836  0.892105
                                        weighted avg   0.939128  0.889952
Baseline Ridge Classifier               0              0.978378  0.952632
                                        1              0.625000  0.789474
                                        accuracy       0.937799  0.937799
                                        macro avg      0.801689  0.871053
                                        weighted avg   0.946253  0.937799
Baseline L1 (Lasso) Logistic Regression 0              0.973545  0.968421
                                        1              0.700000  0.736842
                                        accuracy       0.947368  0.947368
                                        macro avg      0.836772  0.852632
                                        weighted avg   0.948677  0.947368
Logistic Regression (Recall Optimized)  0              0.983146  0.921053
                                        1              0.516129  0.842105
                                        accuracy       0.913876  0.913876
                                        macro avg      0.749638  0.881579
                                        weighted avg   0.940690  0.913876
Logistic Regression (F1 Optimized)      0              0.983146  0.921053
                                        1              0.516129  0.842105
                                        accuracy       0.913876  0.913876
                                        macro avg      0.749638  0.881579
                                        weighted avg   0.940690  0.913876
Ridge Classifier (Recall Optimized)     0              0.982456  0.884211
                                        1              0.421053  0.842105
                                        accuracy       0.880383  0.880383
                                        macro avg      0.701754  0.863158
                                        weighted avg   0.931419  0.880383
Ridge Classifier (F1 Optimized)         0              0.982353  0.878947
                                        1              0.410256  0.842105
                                        accuracy       0.875598  0.875598
                                        macro avg      0.696305  0.860526
                                        weighted avg   0.930344  0.875598
Lasso Classifier (Recall Optimized)     0              0.978723  0.968421
                                        1              0.714286  0.789474
                                        accuracy       0.952153  0.952153
                                        macro avg      0.846505  0.878947
                                        weighted avg   0.954684  0.952153
Lasso Classifier (F1 Optimized)         0              0.978610  0.963158
                                        1              0.681818  0.789474
                                        accuracy       0.947368  0.947368
                                        macro avg      0.830214  0.876316
                                        weighted avg   0.951629  0.947368

                                                      f1-score     support
Baseline Logistic Regression            0             0.936288  190.000000
                                        1             0.596491   19.000000
                                        accuracy      0.889952    0.889952
                                        macro avg     0.766390  209.000000
                                        weighted avg  0.905397  209.000000
Baseline Ridge Classifier               0             0.965333  190.000000
                                        1             0.697674   19.000000
                                        accuracy      0.937799    0.937799
                                        macro avg     0.831504  209.000000
                                        weighted avg  0.941001  209.000000
Baseline L1 (Lasso) Logistic Regression 0             0.970976  190.000000
                                        1             0.717949   19.000000
                                        accuracy      0.947368    0.947368
                                        macro avg     0.844462  209.000000
                                        weighted avg  0.947974  209.000000
Logistic Regression (Recall Optimized)  0             0.951087  190.000000
                                        1             0.640000   19.000000
                                        accuracy      0.913876    0.913876
                                        macro avg     0.795543  209.000000
                                        weighted avg  0.922806  209.000000
Logistic Regression (F1 Optimized)      0             0.951087  190.000000
                                        1             0.640000   19.000000
                                        accuracy      0.913876    0.913876
                                        macro avg     0.795543  209.000000
                                        weighted avg  0.922806  209.000000
Ridge Classifier (Recall Optimized)     0             0.930748  190.000000
                                        1             0.561404   19.000000
                                        accuracy      0.880383    0.880383
                                        macro avg     0.746076  209.000000
                                        weighted avg  0.897171  209.000000
Ridge Classifier (F1 Optimized)         0             0.927778  190.000000
                                        1             0.551724   19.000000
                                        accuracy      0.875598    0.875598
                                        macro avg     0.739751  209.000000
                                        weighted avg  0.893591  209.000000
Lasso Classifier (Recall Optimized)     0             0.973545  190.000000
                                        1             0.750000   19.000000
                                        accuracy      0.952153    0.952153
                                        macro avg     0.861772  209.000000
                                        weighted avg  0.953223  209.000000
Lasso Classifier (F1 Optimized)         0             0.970822  190.000000
                                        1             0.731707   19.000000
                                        accuracy      0.947368    0.947368
                                        macro avg     0.851265  209.000000
                                        weighted avg  0.949085  209.000000

Since this is a fraud dataset, the Lasso Recall optimized model could be the best, with F1 of 0.75 for positive class.  The lasso drives the unhelpful weights to zero. 

The log reg consistently has low precision for the positive class, likely due to the multicolinearity. There could be inconsistency due to this causing large swings in the model. 

Ridge might not performed as well since coefs can be completely shrunk to 0

In [41]:
import numpy as np

pd.set_option('display.max_rows', None)

coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Ridge_Coef': ridge_f1_optimized_model.coef_,
})

# Sort features by the absolute size of their coefficients
coef_df['Abs_Coefficient'] = np.abs(coef_df['Ridge_Coef'])
coef_df = coef_df.sort_values(by='Abs_Coefficient', ascending=False)
coef_df

                          Feature  Ridge_Coef  Abs_Coefficient
39            ForgivenessDate_int   -0.636292         0.636292
38               DateApproved_int    0.336484         0.336484
0                ProcessingMethod   -0.318839         0.318839
21         OriginatingLenderState   -0.189621         0.189621
6            ServicingLenderState    0.178688         0.178688
27             ForgivenPercentage    0.155812         0.155812
29                   PROCEED_Diff   -0.148566         0.148566
2                      LoanStatus   -0.128188         0.128188
31            PAYROLL_PROCEED_pct    0.114106         0.114106
16                   RENT_PROCEED    0.097229         0.097229
3                            Term   -0.071091         0.071091
30          UTILITIES_PROCEED_pct    0.060526         0.060526
7             RuralUrbanIndicator    0.047982         0.047982
10         BusinessAgeDescription    0.038604         0.038604
9                    LMIIndicator   -0.033847         0.033847
1                   BorrowerState    0.031293         0.031293
11                   ProjectState    0.031293         0.031293
13              UTILITIES_PROCEED   -0.029296         0.029296
33               RENT_PROCEED_pct    0.027941         0.027941
8                HubzoneIndicator   -0.025413         0.025413
32  MORTGAGE_INTEREST_PROCEED_pct    0.021649         0.021649
20                   BusinessType   -0.020370         0.020370
40             LoanStatusDate_int    0.019878         0.019878
26              NotForgivenAmount   -0.018404         0.018404
37                PROCEED_Per_Job    0.014354         0.014354
35        HEALTH_CARE_PROCEED_pct    0.013315         0.013315
12                   JobsReported   -0.012459         0.012459
19          DEBT_INTEREST_PROCEED   -0.009028         0.009028
24              ForgivenessAmount    0.008972         0.008972
17         REFINANCE_EIDL_PROCEED   -0.006570         0.006570
14                PAYROLL_PROCEED   -0.005792         0.005792
15      MORTGAGE_INTEREST_PROCEED   -0.004938         0.004938
25                   ApprovalDiff   -0.003343         0.003343
23                      NonProfit   -0.002415         0.002415
36      DEBT_INTEREST_PROCEED_pct   -0.002188         0.002188
18            HEALTH_CARE_PROCEED   -0.002104         0.002104
5           CurrentApprovalAmount   -0.002083         0.002083
28                  TOTAL_PROCEED   -0.002083         0.002083
22                        Veteran    0.001830         0.001830
4           InitialApprovalAmount   -0.001464         0.001464
34     REFINANCE_EIDL_PROCEED_pct    0.000000         0.000000

In [ ]:
len(coef_df[coef_df['Abs_Coefficient'] == 0])

1

We can see 1 features coefs get shrunk to 0 by the Ridge model. This shows these features did not add additional information to the model and can be safely dropped

In [43]:
coefficients = lasso_f1_optimized_model.coef_[0]

# 3. Create a DataFrame to map features to their coefficients
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': coefficients
})

# 4. VIEW RETAINED FEATURES (Coefficient is NOT 0)
selected_features = coef_df[coef_df['Coefficient'] != 0]
print("Features Selected by Lasso:")
print(selected_features)

# 5. VIEW REJECTED FEATURES (Coefficient is exactly 0)
dropped_features = coef_df[coef_df['Coefficient'] == 0]
print("\nFeatures Ignored by Lasso:")
print(dropped_features['Feature'].tolist())

Features Selected by Lasso:
                   Feature  Coefficient
0         ProcessingMethod    -0.519262
1            BorrowerState     0.218712
2               LoanStatus    -0.251691
3                     Term    -0.043586
7      RuralUrbanIndicator     0.184038
9             LMIIndicator    -0.062952
10  BusinessAgeDescription     0.200309
11            ProjectState     0.218712
12            JobsReported    -0.081325
14         PAYROLL_PROCEED    -0.016060
16            RENT_PROCEED     0.152955
20            BusinessType    -0.012146
21  OriginatingLenderState    -0.199626
22                 Veteran     0.149011
23               NonProfit     0.045029
25            ApprovalDiff    -0.055810
26       NotForgivenAmount    -0.041735
27      ForgivenPercentage    -0.629629
29            PROCEED_Diff    -0.435194
37         PROCEED_Per_Job     0.166441
38        DateApproved_int    -0.052837
39     ForgivenessDate_int    -0.952909
40      LoanStatusDate_int    -0.203905

Features Ignored by Lasso:
['InitialApprovalAmount', 'CurrentApprovalAmount', 'ServicingLenderState', 'HubzoneIndicator', 'UTILITIES_PROCEED', 'MORTGAGE_INTEREST_PROCEED', 'REFINANCE_EIDL_PROCEED', 'HEALTH_CARE_PROCEED', 'DEBT_INTEREST_PROCEED', 'ForgivenessAmount', 'TOTAL_PROCEED', 'UTILITIES_PROCEED_pct', 'PAYROLL_PROCEED_pct', 'MORTGAGE_INTEREST_PROCEED_pct', 'RENT_PROCEED_pct', 'REFINANCE_EIDL_PROCEED_pct', 'HEALTH_CARE_PROCEED_pct', 'DEBT_INTEREST_PROCEED_pct']

In [44]:
len(dropped_features)

18

Lasso dropped 18 features