In [ ]:
import pandas as pd
from imblearn.under_sampling import RandomUnderSampler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from collections import Counter

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Note: LinearRegression/Lasso/Elastic Net/Ridge did not make sense for the fraud use case (binary classification). So I instead use Logistic Reg with different penalty

In [2]:
random_state=42

In [3]:
classification_reports = []
classification_report_keys = []

## IBM

### Data

In [4]:
# Import IBM dataset
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/ibm_hi_small_trans_cleaned.csv')
df

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Amount Paid,Is Laundering,Amount_Received_USD,Amount_Paid_USD,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,3697.340000,0,3697.340000,3697.340000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,0.010000,0,0.010000,0.010000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,14675.570000,0,14675.570000,14675.570000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,2806.970000,0,2806.970000,2806.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,36682.970000,0,36682.970000,36682.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,0.154978,0,3107.386389,3107.386389,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,0.108128,0,2168.020464,2168.020464,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,0.004988,0,100.011894,100.011894,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,0.038417,0,770.280058,770.280058,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,0.281983,0,5653.900141,5653.900141,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0

In [5]:
df.drop(columns=['Timestamp', 'From Bank', 'To Bank', 'Account', 'Account.1'], inplace=True)

### Undersampling

In [6]:
from collections import Counter


X = df.drop(columns='Is Laundering')
y = df['Is Laundering']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 5073168, 1: 5177})
Resampled dataset shape: Counter({0: 5177, 1: 5177})

### Split Data

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Models
#### (No parameter optimization, feature scaling, or cross validation)

#### Linear Regression

In [8]:
model = LogisticRegression()

In [9]:
model.fit(X_train, y_train)

LogisticRegression()

In [10]:
y_pred = model.predict(X_test)

In [11]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline Logistic Regression')

              precision    recall  f1-score   support

           0       1.00      0.01      0.02      1036
           1       0.50      1.00      0.67      1035

    accuracy                           0.50      2071
   macro avg       0.75      0.50      0.34      2071
weighted avg       0.75      0.50      0.34      2071

#### Ridge

In [12]:
from sklearn.linear_model import RidgeClassifier


ridge_model = RidgeClassifier(random_state=random_state)

In [13]:
ridge_model.fit(X_train, y_train)

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_ridge.py:213: LinAlgWarning: Ill-conditioned matrix (rcond=2.80134e-23): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

RidgeClassifier(random_state=42)

In [14]:
y_pred = ridge_model.predict(X_test)

In [15]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline Ridge Classifier')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

#### Lasso

In [16]:
lasso_model = LogisticRegression(penalty='l1', solver='liblinear')

In [17]:
lasso_model.fit(X_train, y_train)

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

LogisticRegression(penalty='l1', solver='liblinear')

In [18]:
y_pred = lasso_model.predict(X_test)

In [19]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline L1 (Lasso) Logistic Regression')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

### Scaling Data

In [20]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Parameter Tuning

#### Logistic Regression

In [21]:
# We can only tune the C (float) and Class_weight to tryout balanced.

In [22]:
# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
from sklearn.model_selection import StratifiedKFold


cv = StratifiedKFold(n_splits=5)

In [23]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        class_weight=class_weight,
        C=c,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

log_reg_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_log_reg_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_log_reg_unscaled_recall_optuna_results)

[I 2026-06-24 19:11:43,261] A new study created in memory with name: no-name-aa1fbdae-f775-4056-903f-2b608112b814
[I 2026-06-24 19:11:44,856] Trial 0 finished with value: 0.8597323473365851 and parameters: {'C': 0.7971471149212764, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:46,055] Trial 1 finished with value: 0.8597323473365851 and parameters: {'C': 0.062296252717312005, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:47,447] Trial 2 finished with value: 0.8597323473365851 and parameters: {'C': 0.32511085134283163, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:48,851] Trial 3 finished with value: 0.8597323473365851 and parameters: {'C': 0.6465034220326928, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:49,025] Trial 4 finished with value: 0.8597323473365851 and parameters: {'C': 0.6604048671082713, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:49,181] Trial 5 finished with value: 0.8597323473365851 and parameters: {'C': 0.48177728857022406, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:49,338] Trial 6 finished with value: 0.8597323473365851 and parameters: {'C': 0.8904046085323785, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:49,496] Trial 7 finished with value: 0.8597323473365851 and parameters: {'C': 0.26177963082639677, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:49,649] Trial 8 finished with value: 0.8597323473365851 and parameters: {'C': 0.07749817939447806, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:49,806] Trial 9 finished with value: 0.8597323473365851 and parameters: {'C': 0.5665536421962604, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:50,009] Trial 10 finished with value: 0.8597323473365851 and parameters: {'C': 0.9730791882235427, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:50,165] Trial 11 finished with value: 0.8597323473365851 and parameters: {'C': 0.016648091330012292, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:50,337] Trial 12 finished with value: 0.8597323473365851 and parameters: {'C': 0.8392007389882503, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:50,490] Trial 13 finished with value: 0.8597323473365851 and parameters: {'C': 0.7697269194965911, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:50,653] Trial 14 finished with value: 0.8597323473365851 and parameters: {'C': 0.379073239024799, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:50,806] Trial 15 finished with value: 0.8597323473365851 and parameters: {'C': 0.11585383899418242, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:50,963] Trial 16 finished with value: 0.8597323473365851 and parameters: {'C': 0.192997729118992, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:51,119] Trial 17 finished with value: 0.8597323473365851 and parameters: {'C': 0.44635610578044443, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:51,294] Trial 18 finished with value: 0.8597323473365851 and parameters: {'C': 0.761472538229128, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:51,447] Trial 19 finished with value: 0.8597323473365851 and parameters: {'C': 0.5649733324693795, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:51,618] Trial 20 finished with value: 0.8597323473365851 and parameters: {'C': 0.9966685844847273, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:51,775] Trial 21 finished with value: 0.8597323473365851 and parameters: {'C': 0.3155556817357555, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:51,930] Trial 22 finished with value: 0.8597323473365851 and parameters: {'C': 0.22175165134154395, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:52,082] Trial 23 finished with value: 0.8597323473365851 and parameters: {'C': 0.3646598328042703, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:52,240] Trial 24 finished with value: 0.8597323473365851 and parameters: {'C': 0.12864419673631003, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:52,390] Trial 25 finished with value: 0.8597323473365851 and parameters: {'C': 0.03132904297472372, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:52,554] Trial 26 finished with value: 0.8597323473365851 and parameters: {'C': 0.1801871519418807, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:52,711] Trial 27 finished with value: 0.8597323473365851 and parameters: {'C': 0.29390334999172935, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:52,867] Trial 28 finished with value: 0.8597323473365851 and parameters: {'C': 0.39849135174227035, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:53,023] Trial 29 finished with value: 0.8597323473365851 and parameters: {'C': 0.6924626930754001, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:53,178] Trial 30 finished with value: 0.8597323473365851 and parameters: {'C': 0.5506243063794098, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:53,334] Trial 31 finished with value: 0.8597323473365851 and parameters: {'C': 0.6624308374499087, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:53,491] Trial 32 finished with value: 0.8597323473365851 and parameters: {'C': 0.7376092040277431, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:53,667] Trial 33 finished with value: 0.8597323473365851 and parameters: {'C': 0.6202767643475688, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:53,841] Trial 34 finished with value: 0.8597323473365851 and parameters: {'C': 0.8535606385711731, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:54,013] Trial 35 finished with value: 0.8597323473365851 and parameters: {'C': 0.6328054763402241, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:54,168] Trial 36 finished with value: 0.8597323473365851 and parameters: {'C': 0.5225313008360102, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:54,326] Trial 37 finished with value: 0.8597323473365851 and parameters: {'C': 0.4461816013945325, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:54,480] Trial 38 finished with value: 0.8597323473365851 and parameters: {'C': 0.9062490099332906, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:54,634] Trial 39 finished with value: 0.8597323473365851 and parameters: {'C': 0.8059743171170526, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:54,804] Trial 40 finished with value: 0.8597323473365851 and parameters: {'C': 0.944314526705372, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:54,967] Trial 41 finished with value: 0.8597323473365851 and parameters: {'C': 0.6999670305704774, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:55,124] Trial 42 finished with value: 0.8597323473365851 and parameters: {'C': 0.6024264130228999, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:55,281] Trial 43 finished with value: 0.8597323473365851 and parameters: {'C': 0.7100769280651613, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:55,448] Trial 44 finished with value: 0.8597323473365851 and parameters: {'C': 0.8072569391430704, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:55,611] Trial 45 finished with value: 0.8597323473365851 and parameters: {'C': 0.48975339685265623, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:55,771] Trial 46 finished with value: 0.8597323473365851 and parameters: {'C': 0.06898463327170351, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:55,931] Trial 47 finished with value: 0.8597323473365851 and parameters: {'C': 0.654154701452708, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:56,104] Trial 48 finished with value: 0.8597323473365851 and parameters: {'C': 0.8711483009261475, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:56,267] Trial 49 finished with value: 0.8597323473365851 and parameters: {'C': 0.8117487845138097, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:56,439] Trial 50 finished with value: 0.8597323473365851 and parameters: {'C': 0.4434938494735774, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:56,592] Trial 51 finished with value: 0.8597323473365851 and parameters: {'C': 0.5857758110347273, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:56,748] Trial 52 finished with value: 0.8597323473365851 and parameters: {'C': 0.5082662314666523, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:56,916] Trial 53 finished with value: 0.8597323473365851 and parameters: {'C': 0.7622527524003139, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:57,072] Trial 54 finished with value: 0.8597323473365851 and parameters: {'C': 0.333729923123575, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:57,226] Trial 55 finished with value: 0.8597323473365851 and parameters: {'C': 0.26446247569312953, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:57,374] Trial 56 finished with value: 0.8597323473365851 and parameters: {'C': 0.3953794925832283, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:57,535] Trial 57 finished with value: 0.8597323473365851 and parameters: {'C': 0.1392550631571548, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:57,691] Trial 58 finished with value: 0.8597323473365851 and parameters: {'C': 0.4843403175915427, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:57,842] Trial 59 finished with value: 0.8597323473365851 and parameters: {'C': 0.21808379466236485, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:58,004] Trial 60 finished with value: 0.8597323473365851 and parameters: {'C': 0.5500465472976217, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:58,185] Trial 61 finished with value: 0.8597323473365851 and parameters: {'C': 0.9722870510642841, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:58,356] Trial 62 finished with value: 0.8597323473365851 and parameters: {'C': 0.8973862421199592, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:11:58,495] Trial 63 finished with value: 0.8614225858522288 and parameters: {'C': 0.002048251102744668, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:11:58,651] Trial 64 finished with value: 0.8597323473365851 and parameters: {'C': 0.01809982954062928, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:11:58,808] Trial 65 finished with value: 0.8597323473365851 and parameters: {'C': 0.11943669206045021, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:11:58,963] Trial 66 finished with value: 0.8597323473365851 and parameters: {'C': 0.06296177259626515, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:11:59,104] Trial 67 finished with value: 0.8597323473365851 and parameters: {'C': 0.007960011201700715, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:11:59,259] Trial 68 finished with value: 0.8597323473365851 and parameters: {'C': 0.16743157452647883, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:11:59,448] Trial 69 finished with value: 0.8597323473365851 and parameters: {'C': 0.0359924757761409, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:11:59,604] Trial 70 finished with value: 0.8597323473365851 and parameters: {'C': 0.0960599580899218, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:11:59,774] Trial 71 finished with value: 0.8597323473365851 and parameters: {'C': 0.7313028763182304, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:11:59,929] Trial 72 finished with value: 0.8597323473365851 and parameters: {'C': 0.6616179970556533, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:00,085] Trial 73 finished with value: 0.8597323473365851 and parameters: {'C': 0.35730958295738774, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:00,238] Trial 74 finished with value: 0.8597323473365851 and parameters: {'C': 0.786601819629323, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:00,410] Trial 75 finished with value: 0.8597323473365851 and parameters: {'C': 0.9048795277747863, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:00,571] Trial 76 finished with value: 0.8597323473365851 and parameters: {'C': 0.8366564931741354, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:00,741] Trial 77 finished with value: 0.8597323473365851 and parameters: {'C': 0.2909225764266995, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:00,888] Trial 78 finished with value: 0.8597323473365851 and parameters: {'C': 0.41394588848531244, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:01,067] Trial 79 finished with value: 0.8597323473365851 and parameters: {'C': 0.9308563978166899, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:01,248] Trial 80 finished with value: 0.8597323473365851 and parameters: {'C': 0.04513976037613961, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:01,422] Trial 81 finished with value: 0.8597323473365851 and parameters: {'C': 0.6361619507363256, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:01,587] Trial 82 finished with value: 0.8597323473365851 and parameters: {'C': 0.24944414831273273, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:01,757] Trial 83 finished with value: 0.8597323473365851 and parameters: {'C': 0.46416260886867317, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:01,916] Trial 84 finished with value: 0.8597323473365851 and parameters: {'C': 0.09477180025439491, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:02,068] Trial 85 finished with value: 0.8597323473365851 and parameters: {'C': 0.15290705705953128, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:02,226] Trial 86 finished with value: 0.8597323473365851 and parameters: {'C': 0.5306389343826712, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:02,396] Trial 87 finished with value: 0.8597323473365851 and parameters: {'C': 0.6878300847780934, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:02,572] Trial 88 finished with value: 0.8597323473365851 and parameters: {'C': 0.5805090575267078, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:02,729] Trial 89 finished with value: 0.8597323473365851 and parameters: {'C': 0.2229809240278113, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:02,884] Trial 90 finished with value: 0.8597323473365851 and parameters: {'C': 0.20106102120361233, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:03,037] Trial 91 finished with value: 0.8597323473365851 and parameters: {'C': 0.08225849915845738, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:03,195] Trial 92 finished with value: 0.8614225858522288 and parameters: {'C': 0.0034150579497921676, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:03,350] Trial 93 finished with value: 0.8597323473365851 and parameters: {'C': 0.01237406389895515, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:03,508] Trial 94 finished with value: 0.8597323473365851 and parameters: {'C': 0.045241492153821776, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:03,678] Trial 95 finished with value: 0.8597323473365851 and parameters: {'C': 0.8696489321892555, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:03,830] Trial 96 finished with value: 0.8597323473365851 and parameters: {'C': 0.4237893816904329, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:04,003] Trial 97 finished with value: 0.8597323473365851 and parameters: {'C': 0.7275203292585823, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:04,161] Trial 98 finished with value: 0.8597323473365851 and parameters: {'C': 0.3510785293968865, 'Class_weight': None}. Best is trial 63 with value: 0.8614225858522288.
[I 2026-06-24 19:12:04,318] Trial 99 finished with value: 0.8597323473365851 and parameters: {'C': 0.312701517510258, 'Class_weight': 'balanced'}. Best is trial 63 with value: 0.8614225858522288.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
92,92,0.861423,2026-06-24 19:12:03.037365,2026-06-24 19:12:03.195615,0 days 00:00:00.158250,0.003415,balanced,COMPLETE
63,63,0.861423,2026-06-24 19:11:58.356413,2026-06-24 19:11:58.495597,0 days 00:00:00.139184,0.002048,None,COMPLETE
0,0,0.859732,2026-06-24 19:11:43.262091,2026-06-24 19:11:44.856665,0 days 00:00:01.594574,0.797147,balanced,COMPLETE
1,1,0.859732,2026-06-24 19:11:44.858329,2026-06-24 19:11:46.055537,0 days 00:00:01.197208,0.062296,None,COMPLETE
4,4,0.859732,2026-06-24 19:11:48.852619,2026-06-24 19:11:49.025572,0 days 00:00:00.172953,0.660405,balanced,COMPLETE

In [24]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        class_weight=class_weight,
        C=c,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

log_reg_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_log_reg_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_log_reg_unscaled_f1_optuna_results)

[I 2026-06-24 19:12:04,339] A new study created in memory with name: no-name-bf364028-9e6b-4b58-9ddf-a161dbbb5e87
[I 2026-06-24 19:12:04,506] Trial 0 finished with value: 0.8771824847322993 and parameters: {'C': 0.6670177538704194, 'Class_weight': None}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:04,658] Trial 1 finished with value: 0.8771824847322993 and parameters: {'C': 0.014561258990156301, 'Class_weight': None}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:04,805] Trial 2 finished with value: 0.8771824847322993 and parameters: {'C': 0.4705405784046112, 'Class_weight': None}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:04,977] Trial 3 finished with value: 0.8771824847322993 and parameters: {'C': 0.3804685332403221, 'Class_weight': None}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:05,147] Trial 4 finished with value: 0.8771824847322993 and parameters: {'C': 0.5652260266098672, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:05,306] Trial 5 finished with value: 0.8771824847322993 and parameters: {'C': 0.3868953458458798, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:05,462] Trial 6 finished with value: 0.8771824847322993 and parameters: {'C': 0.733377201436405, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:05,616] Trial 7 finished with value: 0.8771824847322993 and parameters: {'C': 0.770116985549801, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:05,773] Trial 8 finished with value: 0.8769665578707571 and parameters: {'C': 0.9439540220391323, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:05,935] Trial 9 finished with value: 0.8771824847322993 and parameters: {'C': 0.5498365497699662, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:06,091] Trial 10 finished with value: 0.8771824847322993 and parameters: {'C': 0.14832647534695237, 'Class_weight': None}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:06,225] Trial 11 finished with value: 0.878147688462198 and parameters: {'C': 0.0018383032694636089, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:06,383] Trial 12 finished with value: 0.8771824847322993 and parameters: {'C': 0.19443786239817798, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:06,549] Trial 13 finished with value: 0.8771824847322993 and parameters: {'C': 0.7195505393032888, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:06,708] Trial 14 finished with value: 0.8771824847322993 and parameters: {'C': 0.24117328865874998, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:06,872] Trial 15 finished with value: 0.8770744551069047 and parameters: {'C': 0.991691834060431, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:07,021] Trial 16 finished with value: 0.8771824847322993 and parameters: {'C': 0.020483481343964494, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:07,177] Trial 17 finished with value: 0.8771824847322993 and parameters: {'C': 0.6573728484209216, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:07,349] Trial 18 finished with value: 0.8770744551069047 and parameters: {'C': 0.8171888599923665, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:07,518] Trial 19 finished with value: 0.8771824847322993 and parameters: {'C': 0.35106402028726386, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:07,693] Trial 20 finished with value: 0.8770744551069047 and parameters: {'C': 0.8767551280576048, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:07,836] Trial 21 finished with value: 0.8771824847322993 and parameters: {'C': 0.014717916337117956, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:07,983] Trial 22 finished with value: 0.8771824847322993 and parameters: {'C': 0.09564707593377376, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:08,140] Trial 23 finished with value: 0.8771824847322993 and parameters: {'C': 0.29918208468267915, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:08,310] Trial 24 finished with value: 0.8771824847322993 and parameters: {'C': 0.118652471182706, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:08,478] Trial 25 finished with value: 0.8771824847322993 and parameters: {'C': 0.6442566726276314, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:08,634] Trial 26 finished with value: 0.8771824847322993 and parameters: {'C': 0.06297760025152148, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:08,788] Trial 27 finished with value: 0.8771824847322993 and parameters: {'C': 0.48214641985086093, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:08,944] Trial 28 finished with value: 0.8771824847322993 and parameters: {'C': 0.21863174744398245, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:09,100] Trial 29 finished with value: 0.8771824847322993 and parameters: {'C': 0.4378743189227182, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:09,256] Trial 30 finished with value: 0.8771824847322993 and parameters: {'C': 0.27527590280124326, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:09,413] Trial 31 finished with value: 0.8771824847322993 and parameters: {'C': 0.6298684131614893, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:09,568] Trial 32 finished with value: 0.8771824847322993 and parameters: {'C': 0.17300063054015183, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:09,725] Trial 33 finished with value: 0.8771824847322993 and parameters: {'C': 0.5485415610006845, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:09,873] Trial 34 finished with value: 0.8771824847322993 and parameters: {'C': 0.363034987662372, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:10,039] Trial 35 finished with value: 0.8771824847322993 and parameters: {'C': 0.4430948069611777, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:10,195] Trial 36 finished with value: 0.8771824847322993 and parameters: {'C': 0.03814071514908843, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:10,364] Trial 37 finished with value: 0.8770744551069047 and parameters: {'C': 0.8163665406178784, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:10,525] Trial 38 finished with value: 0.8771824847322993 and parameters: {'C': 0.09695940462175773, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:10,696] Trial 39 finished with value: 0.8771824847322993 and parameters: {'C': 0.5802218839793541, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:10,852] Trial 40 finished with value: 0.8771824847322993 and parameters: {'C': 0.3218429536543498, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:11,010] Trial 41 finished with value: 0.8771824847322993 and parameters: {'C': 0.40025412933094445, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:11,165] Trial 42 finished with value: 0.8771824847322993 and parameters: {'C': 0.7127778079037792, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:11,317] Trial 43 finished with value: 0.8771824847322993 and parameters: {'C': 0.5099529246055481, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:11,474] Trial 44 finished with value: 0.8771824847322993 and parameters: {'C': 0.15108579795773516, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:11,622] Trial 45 finished with value: 0.8771824847322993 and parameters: {'C': 0.5097739553395136, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:11,779] Trial 46 finished with value: 0.8771824847322993 and parameters: {'C': 0.5968560895929661, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:11,935] Trial 47 finished with value: 0.8771824847322993 and parameters: {'C': 0.24540501739935938, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:12,089] Trial 48 finished with value: 0.8771824847322993 and parameters: {'C': 0.6885943727643256, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:12,242] Trial 49 finished with value: 0.8771824847322993 and parameters: {'C': 0.7578236776429926, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:12,399] Trial 50 finished with value: 0.8771824847322993 and parameters: {'C': 0.06581582614522498, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:12,568] Trial 51 finished with value: 0.8771824847322993 and parameters: {'C': 0.585931189068419, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:12,739] Trial 52 finished with value: 0.8771824847322993 and parameters: {'C': 0.46647485406732203, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:12,896] Trial 53 finished with value: 0.8771824847322993 and parameters: {'C': 0.5389525555455897, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:13,053] Trial 54 finished with value: 0.8771824847322993 and parameters: {'C': 0.4030856318591266, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:13,192] Trial 55 finished with value: 0.8771824847322993 and parameters: {'C': 0.009082488140903684, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:13,369] Trial 56 finished with value: 0.8771824847322993 and parameters: {'C': 0.6945311047443038, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:13,540] Trial 57 finished with value: 0.8770744551069047 and parameters: {'C': 0.7996947539708712, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:13,714] Trial 58 finished with value: 0.8769665578707571 and parameters: {'C': 0.9221845375636408, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:13,867] Trial 59 finished with value: 0.8771824847322993 and parameters: {'C': 0.6397393371741739, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:14,034] Trial 60 finished with value: 0.8771824847322993 and parameters: {'C': 0.19458486438088, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:14,195] Trial 61 finished with value: 0.8771824847322993 and parameters: {'C': 0.38865747110904836, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:14,345] Trial 62 finished with value: 0.8771824847322993 and parameters: {'C': 0.31677033041603253, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:14,507] Trial 63 finished with value: 0.8771824847322993 and parameters: {'C': 0.45434276548954583, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:14,657] Trial 64 finished with value: 0.8771824847322993 and parameters: {'C': 0.3574549472776407, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:14,807] Trial 65 finished with value: 0.8771824847322993 and parameters: {'C': 0.4254830358682945, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:14,962] Trial 66 finished with value: 0.8771824847322993 and parameters: {'C': 0.6082100485559067, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:15,123] Trial 67 finished with value: 0.8771824847322993 and parameters: {'C': 0.48835926501399174, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:15,281] Trial 68 finished with value: 0.8771824847322993 and parameters: {'C': 0.5567477948341073, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:15,440] Trial 69 finished with value: 0.8771824847322993 and parameters: {'C': 0.12187560318315795, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:15,596] Trial 70 finished with value: 0.8771824847322993 and parameters: {'C': 0.040829994545842525, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:15,770] Trial 71 finished with value: 0.8771824847322993 and parameters: {'C': 0.7516541171131421, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:15,946] Trial 72 finished with value: 0.8771824847322993 and parameters: {'C': 0.6645113748226676, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:16,115] Trial 73 finished with value: 0.8770744551069047 and parameters: {'C': 0.8406189786612932, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:16,292] Trial 74 finished with value: 0.8771824847322993 and parameters: {'C': 0.5325723430796423, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:16,464] Trial 75 finished with value: 0.8770744551069047 and parameters: {'C': 0.7309314487287892, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:16,635] Trial 76 finished with value: 0.8771824847322993 and parameters: {'C': 0.6665743863073305, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:16,793] Trial 77 finished with value: 0.8771824847322993 and parameters: {'C': 0.08740980843450821, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:16,948] Trial 78 finished with value: 0.8771824847322993 and parameters: {'C': 0.2741059339047808, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:17,115] Trial 79 finished with value: 0.8770744551069047 and parameters: {'C': 0.7824618392576623, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:17,289] Trial 80 finished with value: 0.8771824847322993 and parameters: {'C': 0.6236987864277564, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:17,463] Trial 81 finished with value: 0.8770744551069047 and parameters: {'C': 0.8378543961890291, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:17,636] Trial 82 finished with value: 0.8771824847322993 and parameters: {'C': 0.7647635655499673, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:17,803] Trial 83 finished with value: 0.8770744551069047 and parameters: {'C': 0.7273145589767243, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:17,981] Trial 84 finished with value: 0.8770744551069047 and parameters: {'C': 0.8693370939241587, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:18,148] Trial 85 finished with value: 0.8771824847322993 and parameters: {'C': 0.691747831386635, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:18,303] Trial 86 finished with value: 0.8771824847322993 and parameters: {'C': 0.5612758892774825, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:18,463] Trial 87 finished with value: 0.8771824847322993 and parameters: {'C': 0.5162998616199554, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:18,617] Trial 88 finished with value: 0.8771824847322993 and parameters: {'C': 0.37307730905294656, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:18,774] Trial 89 finished with value: 0.8771824847322993 and parameters: {'C': 0.03512052872977376, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:18,943] Trial 90 finished with value: 0.8769665578707571 and parameters: {'C': 0.9979761619306285, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:19,101] Trial 91 finished with value: 0.8771824847322993 and parameters: {'C': 0.474463160994953, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:19,272] Trial 92 finished with value: 0.8771824847322993 and parameters: {'C': 0.4184510713368035, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:19,426] Trial 93 finished with value: 0.8771824847322993 and parameters: {'C': 0.3368630787801932, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:19,589] Trial 94 finished with value: 0.8771824847322993 and parameters: {'C': 0.49773264413401186, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:19,745] Trial 95 finished with value: 0.8771824847322993 and parameters: {'C': 0.5639309957136761, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:19,899] Trial 96 finished with value: 0.878147688462198 and parameters: {'C': 0.0024733955392037266, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:20,057] Trial 97 finished with value: 0.8771824847322993 and parameters: {'C': 0.06989614726662191, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:20,198] Trial 98 finished with value: 0.8771824847322993 and parameters: {'C': 0.006544091563051013, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.
[I 2026-06-24 19:12:20,355] Trial 99 finished with value: 0.8771824847322993 and parameters: {'C': 0.02498435056581444, 'Class_weight': None}. Best is trial 11 with value: 0.878147688462198.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
11,11,0.878148,2026-06-24 19:12:06.091475,2026-06-24 19:12:06.225341,0 days 00:00:00.133866,0.001838,None,COMPLETE
96,96,0.878148,2026-06-24 19:12:19.746743,2026-06-24 19:12:19.899790,0 days 00:00:00.153047,0.002473,None,COMPLETE
2,2,0.877182,2026-06-24 19:12:04.659755,2026-06-24 19:12:04.805449,0 days 00:00:00.145694,0.470541,None,COMPLETE
0,0,0.877182,2026-06-24 19:12:04.341658,2026-06-24 19:12:04.506496,0 days 00:00:00.164838,0.667018,None,COMPLETE
3,3,0.877182,2026-06-24 19:12:04.806452,2026-06-24 19:12:04.977283,0 days 00:00:00.170831,0.380469,None,COMPLETE

##### Tryout best params

In [25]:
log_reg_recall_optimized_model = LogisticRegression(C=0.769946, class_weight='balanced', random_state=random_state)
log_reg_recall_optimized_model.fit(X_train_scaled, y_train)
y_pred = log_reg_recall_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Logistic Regression (Recall Optimized)')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

In [26]:
log_reg_f1_optimized_model = LogisticRegression(C=0.315005, class_weight='balanced', random_state=random_state)
log_reg_f1_optimized_model.fit(X_train_scaled, y_train)
y_pred = log_reg_f1_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Logistic Regression (F1 Optimized)')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

#### Ridge

In [27]:
# We can tune alpha and class weight

##### Recall optimized

In [28]:
def objective(trial):
    alpha = trial.suggest_float("alpha", 0.001, 1.0)
    class_weight = trial.suggest_categorical("class_weight", ['balanced', None])
    
    model = RidgeClassifier(
        class_weight=class_weight,
        alpha=alpha,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

ridge_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_ridge_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_ridge_unscaled_recall_optuna_results)

[I 2026-06-24 19:12:20,495] A new study created in memory with name: no-name-668ab559-2e13-4b35-8736-844a4cb23b6a
[I 2026-06-24 19:12:20,650] Trial 0 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6730975660407932, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:20,805] Trial 1 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.097804436962455, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:20,959] Trial 2 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4500130294400889, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:21,114] Trial 3 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9031458743315879, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:21,271] Trial 4 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4397225545574282, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:21,427] Trial 5 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.1618807679986324, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:21,566] Trial 6 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6092196116297752, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:21,718] Trial 7 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.007884294296271962, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:21,869] Trial 8 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.06272909342964189, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:22,019] Trial 9 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.288308355696052, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:22,174] Trial 10 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8029243228002051, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:22,323] Trial 11 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6803445547283955, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:22,477] Trial 12 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.2953645876638783, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:22,617] Trial 13 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6506657093010072, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:22,777] Trial 14 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9881603301407453, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:22,932] Trial 15 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.29909352235684106, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:23,087] Trial 16 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.547931078205005, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:23,242] Trial 17 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7801646271082525, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:23,401] Trial 18 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.1467150825088549, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:23,556] Trial 19 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.38943538674968864, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:23,712] Trial 20 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7707699569751538, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:23,868] Trial 21 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5136584568955481, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:24,027] Trial 22 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.38206023024927627, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:24,179] Trial 23 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.17084684507612338, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:24,318] Trial 24 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7068591809286041, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:24,473] Trial 25 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5592308319165865, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:24,630] Trial 26 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4340552495950197, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:24,775] Trial 27 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.20454783749354336, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:24,933] Trial 28 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8618937139160836, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:25,082] Trial 29 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9450190623412991, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:25,233] Trial 30 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6058674506838452, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:25,390] Trial 31 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8986139473494261, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:25,546] Trial 32 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4734371312733078, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:25,693] Trial 33 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8528045523668656, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:25,844] Trial 34 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.07294855746947664, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:25,999] Trial 35 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6141857160557102, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:26,162] Trial 36 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7306758463072623, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:26,319] Trial 37 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.011157285104054226, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:26,467] Trial 38 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.23007802239751096, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:26,820] Trial 39 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.3491901518034165, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:26,973] Trial 40 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8447619394018943, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:27,127] Trial 41 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4570230300256921, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:27,282] Trial 42 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6523558840174459, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:27,446] Trial 43 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.3345215175208707, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:27,590] Trial 44 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4151677021465875, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:27,759] Trial 45 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5242529473980602, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:27,907] Trial 46 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.25683296052938315, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:28,066] Trial 47 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.10729629554054738, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:28,215] Trial 48 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6006678503585813, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:28,361] Trial 49 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5691098143158319, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:28,518] Trial 50 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.979215938110994, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:28,658] Trial 51 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.13363704824656364, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:28,805] Trial 52 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.04307126823949084, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:28,966] Trial 53 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.2861923230449164, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:29,105] Trial 54 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7400335331114613, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:29,265] Trial 55 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.1846163660999635, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:29,419] Trial 56 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4912358934905837, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:29,568] Trial 57 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8153309170912305, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:29,725] Trial 58 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.09546788134392042, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:29,869] Trial 59 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.3616443359297558, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:30,024] Trial 60 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.14714034363564377, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:30,164] Trial 61 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6708251366852427, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:30,318] Trial 62 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9135697602429682, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:30,475] Trial 63 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4213724085711231, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:30,631] Trial 64 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7111032467049314, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:30,787] Trial 65 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7825755541830209, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:30,941] Trial 66 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5485854062134845, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:31,097] Trial 67 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6343925671474561, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:31,231] Trial 68 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.0051702984789532835, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:31,385] Trial 69 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5127742640942624, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:31,539] Trial 70 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4507910970946617, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:31,695] Trial 71 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.04829881888125437, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:31,853] Trial 72 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.06555972596239598, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:31,997] Trial 73 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5816257262055636, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:32,151] Trial 74 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.11082787933765792, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:32,307] Trial 75 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.02690222628182467, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:32,447] Trial 76 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.3130071069435605, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:32,602] Trial 77 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.21588386586527203, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:32,758] Trial 78 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.08516436706795544, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:32,915] Trial 79 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.4053474146774379, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:33,071] Trial 80 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.5357036251186976, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:33,227] Trial 81 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.13364658521850986, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:33,385] Trial 82 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.1621338434908691, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:33,539] Trial 83 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.3843930616577451, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:33,690] Trial 84 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.040613450777658495, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:33,846] Trial 85 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.07296185715903324, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:33,996] Trial 86 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.2535507277063408, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:34,156] Trial 87 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.18585067090200086, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:34,319] Trial 88 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.48467701624767356, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:34,472] Trial 89 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.9970907927722903, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:34,619] Trial 90 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.7493842847139572, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:34,776] Trial 91 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.12047439012242611, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:34,923] Trial 92 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.44098051347374434, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:35,073] Trial 93 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.6774176155014635, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:35,221] Trial 94 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.3124822983218998, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:35,370] Trial 95 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.26843260520539963, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:35,521] Trial 96 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.024151916023205676, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:35,677] Trial 97 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8908214570772762, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:35,832] Trial 98 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.8253411248140275, 'class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:35,987] Trial 99 finished with value: 0.8597323473365851 and parameters: {'alpha': 0.0586006746570821, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.

,number,value,datetime_start,datetime_complete,duration,params_alpha,params_class_weight,state
0,0,0.859732,2026-06-24 19:12:20.496397,2026-06-24 19:12:20.650930,0 days 00:00:00.154533,0.673098,None,COMPLETE
1,1,0.859732,2026-06-24 19:12:20.650930,2026-06-24 19:12:20.805622,0 days 00:00:00.154692,0.097804,None,COMPLETE
2,2,0.859732,2026-06-24 19:12:20.806757,2026-06-24 19:12:20.959898,0 days 00:00:00.153141,0.450013,balanced,COMPLETE
3,3,0.859732,2026-06-24 19:12:20.960900,2026-06-24 19:12:21.114783,0 days 00:00:00.153883,0.903146,None,COMPLETE
4,4,0.859732,2026-06-24 19:12:21.115783,2026-06-24 19:12:21.271082,0 days 00:00:00.155299,0.439723,balanced,COMPLETE

##### Tryout best params

In [29]:
ridge_recall_optimized_model = RidgeClassifier(alpha=0.039558, class_weight='balanced', random_state=random_state)
ridge_recall_optimized_model.fit(X_train_scaled, y_train)
y_pred = ridge_recall_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Ridge Classifier (Recall Optimized)')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

##### F1 optimized

In [30]:
def objective(trial):
    alpha = trial.suggest_float("alpha", 0.001, 1.0)
    class_weight = trial.suggest_categorical("class_weight", ['balanced', None])
    
    model = RidgeClassifier(
        class_weight=class_weight,
        alpha=alpha,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

ridge_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_ridge_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_ridge_unscaled_f1_optuna_results)

[I 2026-06-24 19:12:36,039] A new study created in memory with name: no-name-6c11b74c-ceca-40c8-a20a-bd91ae168e5c
[I 2026-06-24 19:12:36,200] Trial 0 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.689934173857699, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:36,361] Trial 1 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7965228709472622, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:36,508] Trial 2 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4382108651422037, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:36,649] Trial 3 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3420221630051275, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:36,804] Trial 4 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.36059324066283044, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:36,938] Trial 5 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.02483038306004215, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:37,092] Trial 6 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5168247589073839, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:37,242] Trial 7 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6613927287241935, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:37,383] Trial 8 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5441874773773159, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:37,524] Trial 9 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8027316753690019, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:37,681] Trial 10 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9409890444810218, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:37,834] Trial 11 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8085492665359484, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:37,993] Trial 12 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.712149074223983, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:38,148] Trial 13 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9360664892797337, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:38,304] Trial 14 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6262375932307942, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:38,456] Trial 15 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.2002988411494223, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:38,603] Trial 16 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7862738037081398, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:38,759] Trial 17 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9909669013806699, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:38,911] Trial 18 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8729065164268113, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:39,071] Trial 19 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6101713563937414, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:39,225] Trial 20 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7409570517336621, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:39,382] Trial 21 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3866685412122662, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:39,536] Trial 22 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.47692154055323016, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:39,676] Trial 23 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.20146026125970917, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:39,836] Trial 24 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.45451068217587925, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:39,994] Trial 25 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5877389916568977, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:40,152] Trial 26 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6948502706960944, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:40,306] Trial 27 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.25266433399390936, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:40,448] Trial 28 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8700849994421849, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:40,603] Trial 29 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.42973193773233576, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:40,745] Trial 30 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3020359443708544, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:40,902] Trial 31 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3361806620405242, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:41,059] Trial 32 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.0011812454048210075, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:41,210] Trial 33 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.38848643062556093, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:41,366] Trial 34 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.10457463042151788, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:41,523] Trial 35 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5467837085559208, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:41,679] Trial 36 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5073715240387576, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:41,835] Trial 37 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.2903504376028803, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:41,991] Trial 38 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6688058940680669, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:42,146] Trial 39 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.10114844023848579, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:42,306] Trial 40 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7482274081014431, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:42,463] Trial 41 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3409122030146669, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:42,606] Trial 42 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5391091781792374, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:42,756] Trial 43 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4061179385939622, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:42,915] Trial 44 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8661213513621284, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:43,073] Trial 45 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.2294544509423478, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:43,219] Trial 46 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.36254242370426326, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:43,368] Trial 47 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.45818747330672316, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:43,523] Trial 48 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8219054060216573, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:43,679] Trial 49 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6558584650345141, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:43,819] Trial 50 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5883106046383789, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:43,978] Trial 51 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.10572652501014373, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:44,132] Trial 52 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9357531074544495, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:44,273] Trial 53 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.0452766058309228, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:44,428] Trial 54 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5022639030990595, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:44,568] Trial 55 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.17667336060886682, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:44,723] Trial 56 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7849783151255438, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:44,884] Trial 57 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.1593825830899771, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:45,030] Trial 58 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.30063598530926133, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:45,181] Trial 59 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.2657078041402805, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:45,331] Trial 60 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.42834467655188396, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:45,492] Trial 61 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7196240522937337, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:45,651] Trial 62 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5269029353802458, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:45,802] Trial 63 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8318577051386981, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:45,952] Trial 64 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5672506113458987, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:46,097] Trial 65 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6456447790439236, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:46,253] Trial 66 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4622577959514601, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:46,407] Trial 67 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.345569833771854, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:46,549] Trial 68 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9126081609220742, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:46,700] Trial 69 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.9875225221876636, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:46,857] Trial 70 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7730410549587029, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:47,007] Trial 71 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6221735234866004, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:47,158] Trial 72 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.703609620167147, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:47,311] Trial 73 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4306734676074146, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:47,446] Trial 74 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7501850274277391, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:47,602] Trial 75 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6748410285618316, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:47,751] Trial 76 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3849674682604702, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:47,908] Trial 77 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.48582657812397, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:48,066] Trial 78 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5948466949022718, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:48,221] Trial 79 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6385982971063905, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:48,376] Trial 80 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.723074642946269, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:48,531] Trial 81 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5485349381678515, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:48,686] Trial 82 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6870445416451215, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:48,819] Trial 83 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5104667074584186, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:48,975] Trial 84 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5661529037328912, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:49,132] Trial 85 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4141845562505948, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:49,288] Trial 86 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.4716603607593347, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:49,446] Trial 87 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.3216399399665723, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:49,602] Trial 88 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.36883772835382983, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:49,762] Trial 89 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.2683891950236168, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:49,922] Trial 90 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.6074844546318218, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:50,069] Trial 91 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8093894649192053, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:50,216] Trial 92 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8499399527306596, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:50,370] Trial 93 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.8957115518643252, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:50,525] Trial 94 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7647590712511811, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:50,664] Trial 95 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.0033560566576333085, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:50,821] Trial 96 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7947316683566042, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:50,975] Trial 97 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.43551496411369534, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:51,118] Trial 98 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.5177114494923282, 'class_weight': None}. Best is trial 0 with value: 0.8769665578707571.
[I 2026-06-24 19:12:51,275] Trial 99 finished with value: 0.8769665578707571 and parameters: {'alpha': 0.7316791692461905, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8769665578707571.

,number,value,datetime_start,datetime_complete,duration,params_alpha,params_class_weight,state
0,0,0.876967,2026-06-24 19:12:36.040531,2026-06-24 19:12:36.200983,0 days 00:00:00.160452,0.689934,balanced,COMPLETE
1,1,0.876967,2026-06-24 19:12:36.201985,2026-06-24 19:12:36.361259,0 days 00:00:00.159274,0.796523,balanced,COMPLETE
2,2,0.876967,2026-06-24 19:12:36.362260,2026-06-24 19:12:36.508678,0 days 00:00:00.146418,0.438211,None,COMPLETE
3,3,0.876967,2026-06-24 19:12:36.509670,2026-06-24 19:12:36.649810,0 days 00:00:00.140140,0.342022,balanced,COMPLETE
4,4,0.876967,2026-06-24 19:12:36.650810,2026-06-24 19:12:36.804060,0 days 00:00:00.153250,0.360593,None,COMPLETE

##### Tryout best params

In [31]:
ridge_f1_optimized_model = RidgeClassifier(alpha=0.364826, class_weight='balanced', random_state=random_state)
ridge_f1_optimized_model.fit(X_train_scaled, y_train)
y_pred = ridge_f1_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Ridge Classifier (F1 Optimized)')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

#### Lasso Logistic Regression

In [32]:
# We can only tune the C (float) and Class_weight to tryout balanced.

In [33]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        penalty='l1', # Lasso
        class_weight=class_weight,
        C=c,
        solver='liblinear',
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=15, n_jobs=-1)

lasso_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_lasso_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_lasso_unscaled_recall_optuna_results)

[I 2026-06-24 19:12:51,343] A new study created in memory with name: no-name-5a8dc142-81ff-41cf-add3-8d5b9a676055
[I 2026-06-24 19:12:51,663] Trial 0 finished with value: 0.8597323473365851 and parameters: {'C': 0.07036797644008005, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:51,890] Trial 3 finished with value: 0.8597323473365851 and parameters: {'C': 0.14525305415291648, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,060] Trial 4 finished with value: 0.8597323473365851 and parameters: {'C': 0.09409652652837042, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,304] Trial 2 finished with value: 0.8597323473365851 and parameters: {'C': 0.4861290807464944, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,308] Trial 1 finished with value: 0.8597323473365851 and parameters: {'C': 0.6843107347808559, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,447] Trial 11 finished with value: 0.8597323473365851 and parameters: {'C': 0.7300594998083497, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,463] Trial 5 finished with value: 0.8597323473365851 and parameters: {'C': 0.49931768819499817, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,466] Trial 9 finished with value: 0.8597323473365851 and parameters: {'C': 0.44503537370703855, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,511] Trial 6 finished with value: 0.8597323473365851 and parameters: {'C': 0.7437247745445134, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,512] Trial 7 finished with value: 0.8597323473365851 and parameters: {'C': 0.8740286073878162, 'Class_weight': None}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,541] Trial 10 finished with value: 0.8597323473365851 and parameters: {'C': 0.5274529821850911, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,543] Trial 14 finished with value: 0.8597323473365851 and parameters: {'C': 0.24953039104369049, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,573] Trial 12 finished with value: 0.8597323473365851 and parameters: {'C': 0.3342535835957048, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,588] Trial 13 finished with value: 0.8597323473365851 and parameters: {'C': 0.7265989096542429, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.
[I 2026-06-24 19:12:52,591] Trial 8 finished with value: 0.8597323473365851 and parameters: {'C': 0.7340826878088378, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8597323473365851.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
0,0,0.859732,2026-06-24 19:12:51.344571,2026-06-24 19:12:51.663344,0 days 00:00:00.318773,0.070368,None,COMPLETE
1,1,0.859732,2026-06-24 19:12:51.346780,2026-06-24 19:12:52.308409,0 days 00:00:00.961629,0.684311,None,COMPLETE
2,2,0.859732,2026-06-24 19:12:51.348286,2026-06-24 19:12:52.304581,0 days 00:00:00.956295,0.486129,None,COMPLETE
3,3,0.859732,2026-06-24 19:12:51.350391,2026-06-24 19:12:51.890184,0 days 00:00:00.539793,0.145253,None,COMPLETE
4,4,0.859732,2026-06-24 19:12:51.353392,2026-06-24 19:12:52.060142,0 days 00:00:00.706750,0.094097,balanced,COMPLETE

In [34]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        penalty='l1', # Lasso
        class_weight=class_weight,
        C=c,
        solver='liblinear',
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=15)

lasso_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_lasso_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_lasso_unscaled_f1_optuna_results)

[I 2026-06-24 19:12:52,609] A new study created in memory with name: no-name-e69eff02-d889-4033-9ebc-4b89d0aa2e58
[I 2026-06-24 19:12:52,853] Trial 0 finished with value: 0.8771824847322993 and parameters: {'C': 0.4450858226672189, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:53,103] Trial 1 finished with value: 0.8771824847322993 and parameters: {'C': 0.47373705419000345, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:53,381] Trial 2 finished with value: 0.8771824847322993 and parameters: {'C': 0.834919925338008, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:53,586] Trial 3 finished with value: 0.8771824847322993 and parameters: {'C': 0.14639735881640423, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:53,789] Trial 4 finished with value: 0.8771824847322993 and parameters: {'C': 0.24827151389902724, 'Class_weight': None}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:54,027] Trial 5 finished with value: 0.8771824847322993 and parameters: {'C': 0.5131646174342829, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:54,289] Trial 6 finished with value: 0.8771824847322993 and parameters: {'C': 0.7533358476740413, 'Class_weight': None}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:54,567] Trial 7 finished with value: 0.8771824847322993 and parameters: {'C': 0.582069887450217, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:54,773] Trial 8 finished with value: 0.8771824847322993 and parameters: {'C': 0.1556425196701488, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:55,058] Trial 9 finished with value: 0.8771824847322993 and parameters: {'C': 0.8778102278367457, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:55,256] Trial 10 finished with value: 0.8771824847322993 and parameters: {'C': 0.31342239492688784, 'Class_weight': None}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:55,471] Trial 11 finished with value: 0.8771824847322993 and parameters: {'C': 0.39129339065803065, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:55,725] Trial 12 finished with value: 0.8771824847322993 and parameters: {'C': 0.62433294176638, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:55,977] Trial 13 finished with value: 0.8771824847322993 and parameters: {'C': 0.4485748365949789, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8771824847322993.
[I 2026-06-24 19:12:56,208] Trial 14 finished with value: 0.8771824847322993 and parameters: {'C': 0.03762707394155751, 'Class_weight': None}. Best is trial 0 with value: 0.8771824847322993.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
0,0,0.877182,2026-06-24 19:12:52.609233,2026-06-24 19:12:52.853672,0 days 00:00:00.244439,0.445086,balanced,COMPLETE
1,1,0.877182,2026-06-24 19:12:52.854672,2026-06-24 19:12:53.103783,0 days 00:00:00.249111,0.473737,balanced,COMPLETE
2,2,0.877182,2026-06-24 19:12:53.103783,2026-06-24 19:12:53.381007,0 days 00:00:00.277224,0.834920,balanced,COMPLETE
3,3,0.877182,2026-06-24 19:12:53.382008,2026-06-24 19:12:53.586640,0 days 00:00:00.204632,0.146397,balanced,COMPLETE
4,4,0.877182,2026-06-24 19:12:53.587680,2026-06-24 19:12:53.789747,0 days 00:00:00.202067,0.248272,None,COMPLETE

##### Tryout best params

In [35]:
lasso_recall_optimized_model = LogisticRegression(
    penalty='l1', # Lasso
    C=0.248927, 
    class_weight=None,
    solver='saga',
    random_state=random_state
)
lasso_recall_optimized_model.fit(X_train_scaled, y_train)
y_pred = lasso_recall_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Lasso Classifier (Recall Optimized)')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [36]:
lasso_f1_optimized_model = LogisticRegression(
    penalty='l1', # Lasso
    C=0.496023, 
    class_weight=None,
    solver='saga',
    random_state=random_state
)
lasso_f1_optimized_model.fit(X_train_scaled, y_train)
y_pred = lasso_f1_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Lasso Classifier (F1 Optimized)')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.88      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

### Conclusions

In [37]:
pd.concat(classification_reports, keys=classification_report_keys)

                                                      precision    recall  \
Baseline Logistic Regression            0              1.000000  0.007722
                                        1              0.501697  1.000000
                                        accuracy       0.503621  0.503621
                                        macro avg      0.750848  0.503861
                                        weighted avg   0.750969  0.503621
Baseline Ridge Classifier               0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563
Baseline L1 (Lasso) Logistic Regression 0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563
Logistic Regression (Recall Optimized)  0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563
Logistic Regression (F1 Optimized)      0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563
Ridge Classifier (Recall Optimized)     0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563
Ridge Classifier (F1 Optimized)         0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563
Lasso Classifier (Recall Optimized)     0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563
Lasso Classifier (F1 Optimized)         0              0.880839  0.891892
                                        1              0.890411  0.879227
                                        accuracy       0.885563  0.885563
                                        macro avg      0.885625  0.885559
                                        weighted avg   0.885623  0.885563

                                                      f1-score      support
Baseline Logistic Regression            0             0.015326  1036.000000
                                        1             0.668173  1035.000000
                                        accuracy      0.503621     0.503621
                                        macro avg     0.341749  2071.000000
                                        weighted avg  0.341592  2071.000000
Baseline Ridge Classifier               0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000
Baseline L1 (Lasso) Logistic Regression 0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000
Logistic Regression (Recall Optimized)  0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000
Logistic Regression (F1 Optimized)      0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000
Ridge Classifier (Recall Optimized)     0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000
Ridge Classifier (F1 Optimized)         0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000
Lasso Classifier (Recall Optimized)     0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000
Lasso Classifier (F1 Optimized)         0             0.886331  1036.000000
                                        1             0.884784  1035.000000
                                        accuracy      0.885563     0.885563
                                        macro avg     0.885557  2071.000000
                                        weighted avg  0.885558  2071.000000

The lasso and ridge both overcome poor initial performance of the logistic regression model

The logistic reg performance could have been poor due to severe multicollinearity or imbalanced feature scaling

In [38]:
import numpy as np

pd.set_option('display.max_rows', None)

coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Ridge_Coef': ridge_f1_optimized_model.coef_,
})

# Sort features by the absolute size of their coefficients
coef_df['Abs_Coefficient'] = np.abs(coef_df['Ridge_Coef'])
coef_df = coef_df.sort_values(by='Abs_Coefficient', ascending=False)
coef_df

                                      Feature  Ridge_Coef  Abs_Coefficient
94                         Payment Format_ACH    0.439854         0.439854
97                      Payment Format_Cheque   -0.244206         0.244206
101                              Account_Same   -0.235530         0.235530
98                 Payment Format_Credit Card   -0.225024         0.225024
72             Receiving Currency_Saudi Riyal    0.203327         0.203327
87               Payment Currency_Saudi Riyal   -0.165397         0.165397
100                       Payment Format_Wire   -0.123514         0.123514
96                        Payment Format_Cash   -0.118390         0.118390
74             Receiving Currency_Swiss Franc   -0.108524         0.108524
89               Payment Currency_Swiss Franc    0.095514         0.095514
67         Receiving Currency_Canadian Dollar   -0.090633         0.090633
64       Receiving Currency_Australian Dollar   -0.086653         0.086653
73                  Receiving Currency_Shekel   -0.078412         0.078412
76               Receiving Currency_US Dollar    0.077406         0.077406
79         Payment Currency_Australian Dollar    0.076721         0.076721
82           Payment Currency_Canadian Dollar    0.075526         0.075526
91                 Payment Currency_US Dollar   -0.073041         0.073041
69            Receiving Currency_Mexican Peso   -0.063691         0.063691
84              Payment Currency_Mexican Peso    0.059802         0.059802
99                Payment Format_Reinvestment    0.052168         0.052168
88                    Payment Currency_Shekel    0.050805         0.050805
66             Receiving Currency_Brazil Real   -0.050621         0.050621
81               Payment Currency_Brazil Real    0.045302         0.045302
71                   Receiving Currency_Rupee   -0.042474         0.042474
65                 Receiving Currency_Bitcoin    0.038831         0.038831
86                     Payment Currency_Rupee    0.038793         0.038793
102                                 Bank_Same   -0.034873         0.034873
80                   Payment Currency_Bitcoin   -0.031638         0.031638
95                     Payment Format_Bitcoin   -0.031638         0.031638
1                                 Amount Paid    0.029493         0.029493
93                      Payment Currency_Yuan   -0.025268         0.025268
0                             Amount Received   -0.021862         0.021862
3                             Amount_Paid_USD   -0.020045         0.020045
78                    Receiving Currency_Yuan    0.015604         0.015604
75                Receiving Currency_UK Pound   -0.014676         0.014676
92                       Payment Currency_Yen    0.010980         0.010980
83                      Payment Currency_Euro    0.008701         0.008701
77                     Receiving Currency_Yen   -0.008651         0.008651
2                         Amount_Received_USD    0.008275         0.008275
90                  Payment Currency_UK Pound    0.006565         0.006565
68                    Receiving Currency_Euro    0.005976         0.005976
85                     Payment Currency_Ruble   -0.002826         0.002826
70                   Receiving Currency_Ruble   -0.002826         0.002826
38              UK Pound_Amount_Received_Mean    0.000000         0.000000
37                UK Pound_Amount_Paid_Median    0.000000         0.000000
36                  UK Pound_Amount_Paid_Mean    0.000000         0.000000
31                 Yen_Amount_Received_Median    0.000000         0.000000
30                   Yen_Amount_Received_Mean    0.000000         0.000000
29                     Yen_Amount_Paid_Median    0.000000         0.000000
28                       Yen_Amount_Paid_Mean    0.000000         0.000000
27               Rupee_Amount_Received_Median    0.000000         0.000000
26                 Rupee_Amount_Received_Mean    0.000000         0.000000
25                   Rupee_Amount_Paid_Median    0.000000         0.000000
24                     Rupee_Amount_Paid_Mean    0.000000         0.000000
23                Yuan_Amount_Received_Median    0.000000         0.000000
22                  Yuan_Amount_Received_Mean    0.000000         0.000000
21                    Yuan_Amount_Paid_Median    0.000000         0.000000
20                      Yuan_Amount_Paid_Mean    0.000000         0.000000
19   Australian Dollar_Amount_Received_Median    0.000000         0.000000
18     Australian Dollar_Amount_Received_Mean    0.000000         0.000000
17       Australian Dollar_Amount_Paid_Median    0.000000         0.000000
16         Australian Dollar_Amount_Paid_Mean    0.000000         0.000000
15                Euro_Amount_Received_Median    0.000000         0.000000
14                  Euro_Amount_Received_Mean    0.000000         0.000000
13                    Euro_Amount_Paid_Median    0.000000         0.000000
12                      Euro_Amount_Paid_Mean    0.000000         0.000000
11             Bitcoin_Amount_Received_Median    0.000000         0.000000
10               Bitcoin_Amount_Received_Mean    0.000000         0.000000
9                  Bitcoin_Amount_Paid_Median    0.000000         0.000000
8                    Bitcoin_Amount_Paid_Mean    0.000000         0.000000
7            US Dollar_Amount_Received_Median    0.000000         0.000000
6              US Dollar_Amount_Received_Mean    0.000000         0.000000
5                US Dollar_Amount_Paid_Median    0.000000         0.000000
4                  US Dollar_Amount_Paid_Mean    0.000000         0.000000
35        Mexican Peso_Amount_Received_Median    0.000000         0.000000
34          Mexican Peso_Amount_Received_Mean    0.000000         0.000000
33            Mexican Peso_Amount_Paid_Median    0.000000         0.000000
32              Mexican Peso_Amount_Paid_Mean    0.000000         0.000000
63              Shekel_Amount_Received_Median    0.000000         0.000000
55         Brazil Real_Amount_Received_Median    0.000000         0.000000
56               Saudi Riyal_Amount_Paid_Mean    0.000000         0.000000
57             Saudi Riyal_Amount_Paid_Median    0.000000         0.000000
58           Saudi Riyal_Amount_Received_Mean    0.000000         0.000000
59         Saudi Riyal_Amount_Received_Median    0.000000         0.000000
60                    Shekel_Amount_Paid_Mean    0.000000         0.000000
61                  Shekel_Amount_Paid_Median    0.000000         0.000000
62                Shekel_Amount_Received_Mean    0.000000         0.000000
46       Canadian Dollar_Amount_Received_Mean    0.000000         0.000000
45         Canadian Dollar_Amount_Paid_Median    0.000000         0.000000
44           Canadian Dollar_Amount_Paid_Mean    0.000000         0.000000
43               Ruble_Amount_Received_Median    0.000000         0.000000
42                 Ruble_Amount_Received_Mean    0.000000         0.000000
41                   Ruble_Amount_Paid_Median    0.000000         0.000000
40                     Ruble_Amount_Paid_Mean    0.000000         0.000000
47     Canadian Dollar_Amount_Received_Median    0.000000         0.000000
39            UK Pound_Amount_Received_Median    0.000000         0.000000
48               Swiss Franc_Amount_Paid_Mean    0.000000         0.000000
49             Swiss Franc_Amount_Paid_Median    0.000000         0.000000
50           Swiss Franc_Amount_Received_Mean    0.000000         0.000000
51         Swiss Franc_Amount_Received_Median    0.000000         0.000000
52               Brazil Real_Amount_Paid_Mean    0.000000         0.000000
53             Brazil Real_Amount_Paid_Median    0.000000         0.000000
54           Brazil Real_Amount_Received_Mean    0.000000         0.000000

In [39]:
len(coef_df[coef_df['Abs_Coefficient'] == 0])

60

We can see 60 features coefs get shrunk to 0 by the Ridge model. These all consist of the _Mean and _Median computed features which aimed to give a summary of average transactions for a given currency. This shows these features did not add additional information to the model and can be safely dropped

In [40]:
coefficients = lasso_f1_optimized_model.coef_[0]

# 3. Create a DataFrame to map features to their coefficients
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': coefficients
})

# 4. VIEW RETAINED FEATURES (Coefficient is NOT 0)
selected_features = coef_df[coef_df['Coefficient'] != 0]
print("Features Selected by Lasso:")
print(selected_features)

# 5. VIEW REJECTED FEATURES (Coefficient is exactly 0)
dropped_features = coef_df[coef_df['Coefficient'] == 0]
print("\nFeatures Ignored by Lasso:")
print(dropped_features['Feature'].tolist())

Features Selected by Lasso:
                                  Feature  Coefficient
0                         Amount Received     0.017789
1                             Amount Paid     0.017961
2                     Amount_Received_USD    -0.016400
3                         Amount_Paid_USD    -0.016484
64   Receiving Currency_Australian Dollar    -0.038141
65             Receiving Currency_Bitcoin    -0.011198
66         Receiving Currency_Brazil Real    -0.017142
67     Receiving Currency_Canadian Dollar    -0.053279
68                Receiving Currency_Euro     0.033876
69        Receiving Currency_Mexican Peso    -0.008931
70               Receiving Currency_Ruble    -0.007914
71               Receiving Currency_Rupee    -0.014150
72         Receiving Currency_Saudi Riyal     0.141448
73              Receiving Currency_Shekel    -0.074872
74         Receiving Currency_Swiss Franc    -0.049205
75            Receiving Currency_UK Pound    -0.023084
76           Receiving Currency_US Dollar     0.047903
77                 Receiving Currency_Yen     0.001072
80               Payment Currency_Bitcoin    -0.009094
82       Payment Currency_Canadian Dollar    -0.006525
83                  Payment Currency_Euro     0.062219
85                 Payment Currency_Ruble    -0.007914
87           Payment Currency_Saudi Riyal     0.096084
88                Payment Currency_Shekel    -0.061002
92                   Payment Currency_Yen     0.016499
93                  Payment Currency_Yuan    -0.032862
94                     Payment Format_ACH     1.286779
95                 Payment Format_Bitcoin    -0.009094
96                    Payment Format_Cash    -0.233711
97                  Payment Format_Cheque    -0.538026
98             Payment Format_Credit Card    -0.516595
99            Payment Format_Reinvestment    -0.302329
100                   Payment Format_Wire    -0.610864
101                          Account_Same    -0.733760
102                             Bank_Same    -0.223158

Features Ignored by Lasso:
['US Dollar_Amount_Paid_Mean', 'US Dollar_Amount_Paid_Median', 'US Dollar_Amount_Received_Mean', 'US Dollar_Amount_Received_Median', 'Bitcoin_Amount_Paid_Mean', 'Bitcoin_Amount_Paid_Median', 'Bitcoin_Amount_Received_Mean', 'Bitcoin_Amount_Received_Median', 'Euro_Amount_Paid_Mean', 'Euro_Amount_Paid_Median', 'Euro_Amount_Received_Mean', 'Euro_Amount_Received_Median', 'Australian Dollar_Amount_Paid_Mean', 'Australian Dollar_Amount_Paid_Median', 'Australian Dollar_Amount_Received_Mean', 'Australian Dollar_Amount_Received_Median', 'Yuan_Amount_Paid_Mean', 'Yuan_Amount_Paid_Median', 'Yuan_Amount_Received_Mean', 'Yuan_Amount_Received_Median', 'Rupee_Amount_Paid_Mean', 'Rupee_Amount_Paid_Median', 'Rupee_Amount_Received_Mean', 'Rupee_Amount_Received_Median', 'Yen_Amount_Paid_Mean', 'Yen_Amount_Paid_Median', 'Yen_Amount_Received_Mean', 'Yen_Amount_Received_Median', 'Mexican Peso_Amount_Paid_Mean', 'Mexican Peso_Amount_Paid_Median', 'Mexican Peso_Amount_Received_Mean', 'Mexican Peso_Amount_Received_Median', 'UK Pound_Amount_Paid_Mean', 'UK Pound_Amount_Paid_Median', 'UK Pound_Amount_Received_Mean', 'UK Pound_Amount_Received_Median', 'Ruble_Amount_Paid_Mean', 'Ruble_Amount_Paid_Median', 'Ruble_Amount_Received_Mean', 'Ruble_Amount_Received_Median', 'Canadian Dollar_Amount_Paid_Mean', 'Canadian Dollar_Amount_Paid_Median', 'Canadian Dollar_Amount_Received_Mean', 'Canadian Dollar_Amount_Received_Median', 'Swiss Franc_Amount_Paid_Mean', 'Swiss Franc_Amount_Paid_Median', 'Swiss Franc_Amount_Received_Mean', 'Swiss Franc_Amount_Received_Median', 'Brazil Real_Amount_Paid_Mean', 'Brazil Real_Amount_Paid_Median', 'Brazil Real_Amount_Received_Mean', 'Brazil Real_Amount_Received_Median', 'Saudi Riyal_Amount_Paid_Mean', 'Saudi Riyal_Amount_Paid_Median', 'Saudi Riyal_Amount_Received_Mean', 'Saudi Riyal_Amount_Received_Median', 'Shekel_Amount_Paid_Mean', 'Shekel_Amount_Paid_Median', 'Shekel_Amount_Received_Mean', 'Shekel_Amount_Received_Median', 'Receiving Currency_Yuan', 'Payment Currency_Australian Dollar', 'Payment Currency_Brazil Real', 'Payment Currency_Mexican Peso', 'Payment Currency_Rupee', 'Payment Currency_Swiss Franc', 'Payment Currency_UK Pound', 'Payment Currency_US Dollar']

We can see Lasso also removed some features during feature selection. The features consist of the same summary statistic features which Ridge shrunk the coefficients of.